import {test,expect} from '@playwright/test';
test('local API renders chosen comparison from web controls and downloads playable MP4', async({page})=>{
  test.skip(!process.env.LAB_AB_API_URL || !process.env.LAB_AB_JOB || !process.env.LAB_COMPONENT_TEST_URL,'explicit local fixture required');
  test.setTimeout(120000);
  const api=process.env.LAB_AB_API_URL!,origin=process.env.LAB_COMPONENT_TEST_URL!,job=process.env.LAB_AB_JOB!;
  const response=await page.request.get(`${api}/api/evaluations/${job}/report`);
  expect(response.ok()).toBe(true);
  const report=await response.json();
  await page.route(`${origin}/export-test`,r=>r.fulfill({contentType:'text/html',body:'<div id="test-root"></div>'}));
  await page.goto(`${origin}/export-test`);
  await page.evaluate(report=>{(window as any).exportReport=report},report);
  await page.addScriptTag({type:'module',content:`
    import React from '/node_modules/.vite/deps/react.js';
    import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';
    import {ComparisonExport} from '/src/ComparisonExport.tsx';
    const report=window.exportReport;
    ReactDOM.createRoot(document.getElementById('test-root')).render(React.createElement(ComparisonExport,{report,run:report.manifest.runs[0]}));
  `});
  await page.getByText('Exportar video, audio y figura',{exact:true}).click();
  await page.getByLabel('Fotogramas/s',{exact:true}).fill('10');
  await page.getByLabel('Ancho total',{exact:true}).fill('640');
  await page.getByLabel('Alto',{exact:true}).fill('360');
  await page.getByLabel('Formato',{exact:true}).selectOption('mp4');
  const configuration=page.waitForEvent('download');
  await page.getByRole('button',{name:'Guardar configuración de exportación'}).click();
  expect((await configuration).suggestedFilename()).toBe('comparison-export-settings.json');
  const posted=page.waitForResponse(r=>r.url().includes(`/evaluations/${job}/exports/0`) && r.request().method()==='POST');
  await page.getByRole('button',{name:'Exportar comparación elegida'}).click();
  const accepted=await posted;expect(accepted.ok()).toBe(true);
  const id=(await accepted.json()).id;
  const link=page.locator(`a[href="/api/comparison-exports/${id}/artifacts/comparison.mp4"]`);
  await expect(link).toBeVisible({timeout:90000});
  const download=page.waitForEvent('download');await link.click();
  expect((await download).suggestedFilename()).toBe('comparison.mp4');
  await page.evaluate(id=>{const v=document.createElement('video');v.src=`/api/comparison-exports/${id}/artifacts/comparison.mp4`;v.muted=true;v.controls=true;document.body.appendChild(v)},id);
  await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);
  await page.locator('video').evaluate(async v=>{await v.play()});
  await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(.1);
  await page.locator('video').evaluate(v=>v.pause());
  await expect(page.getByRole('alert')).toHaveCount(0);
});
