import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
test('optional transport archives survive closing a tab without replay or automatic POST',async({page,context})=>{
 test.skip(!process.env.LAB_COMPONENT_TEST_URL,'isolated API/Vite required');const origin=process.env.LAB_COMPONENT_TEST_URL!;
 const protocol=await page.request.post(`${origin}/api/research/r10/protocols`,{data:{protocol:{config:{conditions:['video_only','sound_only']},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'test',reference:'synthetic-declaration',start_s:0,end_s:2}]}}});expect(protocol.ok(),await protocol.text()).toBeTruthy();const id=(await protocol.json()).id;
 const manifest=await page.request.get(`${origin}/api/research/r10/protocols/${id}/artifacts/manifest.json`);
 const raw=JSON.stringify({schema_version:1,protocol_id:id,protocol_manifest_sha256:createHash('sha256').update(await manifest.body()).digest('hex'),trial_id:'trial-0001',duration_s:2,video_enabled:true,audio_enabled:false,events:[{sequence:0,monotonic_s:0,elapsed_s:0,epoch:0,kind:'prepared',video:null,audio:null},{sequence:1,monotonic_s:1,elapsed_s:1,epoch:0,kind:'closed',video:null,audio:null}]});
 await context.route(`${origin}/r10-archives-test`,route=>route.fulfill({contentType:'text/html',body:'<div id="test-root"></div>'}));
 let posts=0;context.on('request',r=>{if(r.method()==='POST')posts++});
 const mount=async(p:Page)=>{await p.goto(`${origin}/r10-archives-test`);await p.addScriptTag({type:'module',content:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {ExperienceTransportsPanel} from '/src/ExperienceTransportsPanel.tsx';const api=async(path,body)=>{const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));return v};ReactDOM.createRoot(document.getElementById('test-root')).render(React.createElement(ExperienceTransportsPanel,{api}));`})};
 await mount(page);await page.evaluate(raw=>{sessionStorage.setItem('weaver.r10.transport.draft.v1',raw);window.dispatchEvent(new Event('weaver-r10-transport-draft-changed'))},raw);
 const archives=page.getByRole('region',{name:'Archivo local de transportes R10',exact:true});
 await archives.getByRole('button',{name:'Conservar borrador en navegador R10'}).click();await expect(archives.getByRole('status')).toBeVisible();
 const archiveId=(await archives.getByRole('status').innerText()).split(': ').at(-1)!;
 await archives.getByRole('button',{name:'Conservar borrador en navegador R10'}).click();await expect(archives.getByRole('button',{name:/^Restaurar borrador local /})).toHaveCount(1);expect(posts).toBe(0);
 await page.close();const reopened=await context.newPage();await mount(reopened);
 const saved=reopened.getByRole('region',{name:'Archivo local de transportes R10',exact:true});
 await expect(saved.getByRole('button',{name:`Restaurar borrador local ${archiveId}`,exact:true})).toBeVisible();
 expect(await reopened.evaluate(()=>sessionStorage.getItem('weaver.r10.transport.draft.v1'))).toBeNull();expect(posts).toBe(0);await expect(reopened.locator('audio,video')).toHaveCount(0);
 const download=reopened.waitForEvent('download');await saved.getByRole('button',{name:`Exportar borrador local ${archiveId}`,exact:true}).click();expect(await readFile((await(await download).path())!,'utf8')).toBe(raw);
 const frozenPending='{"unchanged":"pending"}';await reopened.evaluate(value=>sessionStorage.setItem('weaver.r10.transport.pending.v1',value),frozenPending);
 await saved.getByRole('button',{name:`Restaurar borrador local ${archiveId}`,exact:true}).click();
 await expect.poll(()=>reopened.evaluate(()=>sessionStorage.getItem('weaver.r10.transport.draft.v1'))).toBe(raw);
 expect(await reopened.evaluate(()=>sessionStorage.getItem('weaver.r10.transport.pending.v1'))).toBe(frozenPending);expect(posts).toBe(0);
 await reopened.evaluate(()=>{sessionStorage.removeItem('weaver.r10.transport.pending.v1');window.dispatchEvent(new Event('weaver-r10-transport-changed'))});
 const publishing=reopened.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/research/r10/transports'));
 await reopened.getByRole('button',{name:'Guardar borrador de transporte R10',exact:true}).click();const published=await publishing;expect(published.ok()).toBeTruthy();const publishedId=(await published.json()).id;await expect.poll(()=>posts).toBe(1);
 await expect(reopened.locator(`a[href$="/${publishedId}/artifacts/trace.json"]`)).toBeVisible();
 await reopened.evaluate(id=>new Promise<void>((resolve,reject)=>{const r=indexedDB.open('weaver-r10-transport-archives',1);r.onsuccess=()=>{const db=r.result,tx=db.transaction('archives','readwrite'),store=tx.objectStore('archives'),get=store.get(id);get.onsuccess=()=>store.put({...get.result,raw:get.result.raw+' '});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)};r.onerror=()=>reject(r.error)}),archiveId);
 await saved.getByRole('button',{name:`Exportar borrador local ${archiveId}`,exact:true}).click();await expect(saved.getByRole('alert')).toContainText('modificado');
 await saved.getByRole('button',{name:`Borrar archivo local ${archiveId}`,exact:true}).click();await expect(saved.getByRole('button',{name:/^Restaurar borrador local /})).toHaveCount(0);expect(posts).toBe(1);
 await reopened.close();
});
