import {test,expect} from '@playwright/test';
test('trial player condition gates paused seeks and nominal playback',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{conditions:['video_only','sound_only','audiovisual','desynchronized'],desynchronization_s:-.5},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});expect(response.ok()).toBeTruthy();await page.goto(url);
 await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).click();const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});
 const prepare=async(id:string)=>{await panel.getByLabel('Ensayo para reproducir R10').selectOption(id);await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();};
 await prepare('trial-0001');expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBeTruthy();await expect(panel.locator('audio')).toHaveCount(0);
 await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.7');await expect.poll(async()=>panel.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(1,1);expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBeTruthy();
 await prepare('trial-0002');await expect(panel.locator('video')).toHaveCount(0);await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();
 await prepare('trial-0003');await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.3);
 await prepare('trial-0004');await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.2');await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await page.waitForTimeout(100);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();await expect.poll(async()=>panel.locator('audio').evaluate((a:HTMLAudioElement)=>!a.paused)).toBeTruthy();await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();
 const sent:any[]=[];let dropped=false;await page.route('**/api/research/r10/transports',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}sent.push(route.request().postDataJSON());const result=await route.fetch();if(!dropped){dropped=true;await route.abort('failed');}else await route.fulfill({response:result});});
 await panel.getByRole('button',{name:'Guardar transporte R10',exact:true}).click();await expect(page.getByRole('button',{name:'Recuperar envío de transporte R10'})).toBeVisible();await page.reload();await expect(page.getByRole('region',{name:'Player de ensayo R10'})).toHaveCount(0);await page.getByRole('button',{name:'Recuperar envío de transporte R10'}).click();await expect(page.getByRole('button',{name:'Recuperar envío de transporte R10'})).toHaveCount(0);expect(sent).toHaveLength(2);expect(sent[1]).toEqual(sent[0]);const records=await page.request.get(url+'/api/research/r10/transports');expect(records.ok()).toBeTruthy();const rows=await records.json();expect(rows).toHaveLength(1);const stored=await page.request.get(url+`/api/research/r10/transports/${rows[0].id}/artifacts/trace.json`);const telemetry=await stored.json();expect(telemetry.trial_id).toBe('trial-0004');expect(telemetry.events.some((e:any)=>e.kind==='seek')).toBeTruthy();expect(telemetry.events.some((e:any)=>e.kind==='play_requested')).toBeTruthy();expect(telemetry.events.some((e:any)=>e.kind==='snapshot')).toBeTruthy();expect(telemetry.events.every((e:any,i:number)=>e.sequence===i)).toBeTruthy();
 await page.reload();await expect(page.getByRole('region',{name:'Player de ensayo R10'})).toHaveCount(0);
});

test('positive audio offset does not restart exhausted sound and buffering pauses clock',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{conditions:['audiovisual','desynchronized'],desynchronization_s:.5},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});expect(response.ok()).toBeTruthy();const saved=await response.json();await page.goto(url);
 await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).locator('..').filter({hasText:saved.id}).getByRole('button',{name:'Abrir protocolo congelado R10'}).click();const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});
 await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.1);
 await panel.locator('video').evaluate(v=>v.dispatchEvent(new Event('waiting')));await expect(panel.getByRole('status')).toContainText('Pausado por buffering');const paused=await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue();await page.waitForTimeout(150);expect(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue()).toBe(paused);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();await panel.locator('video').evaluate(v=>v.dispatchEvent(new Event('canplay')));await expect(panel.getByRole('button',{name:'Pausar ensayo R10'})).toBeDisabled();
 await panel.getByLabel('Ensayo para reproducir R10').selectOption('trial-0002');await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;(a as any).starts=0;a.addEventListener('play',()=>{(a as any).starts++;});});await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.6');await expect.poll(async()=>panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeCloseTo(1.1,1);await expect.poll(async()=>panel.locator('video').evaluate((v:HTMLVideoElement)=>v.seeking)).toBeFalsy();await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect(panel.getByRole('status')).toContainText('Fin del transporte nominal');expect(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue()).toBe('1.2');expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>(a as any).starts)).toBe(1);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();
});

test('metadata resolved after player unmount cannot revive media',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});const saved=await response.json();await page.goto(url);await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).locator('..').filter({hasText:saved.id}).getByRole('button',{name:'Abrir protocolo congelado R10'}).click();
 let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});let captured!:()=>void;const seen=new Promise<void>(r=>{captured=r;});
 await page.route('**/trials/*/media-info',async route=>{const result=await route.fetch();captured();await gate;await route.fulfill({response:result});});
 const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await seen;await page.getByLabel('Protocolo JSON R10').fill('{}');await expect(panel).toHaveCount(0);release();await page.waitForTimeout(100);await expect(page.locator('video')).toHaveCount(0);await expect(page.locator('audio')).toHaveCount(0);
});

test('invalid transport pending can be exported unchanged and explicitly discarded',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 await page.goto(url);await page.evaluate(()=>sessionStorage.setItem('weaver.r10.transport.pending.v1','{broken-json'));await page.reload();
 const panel=page.getByRole('region',{name:'Registros de transporte R10',exact:true});await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.getByRole('button',{name:'Recuperar envío de transporte R10'})).toHaveCount(0);
 const downloaded=page.waitForEvent('download');await panel.getByRole('button',{name:'Exportar envío pendiente R10'}).click();const download=await downloaded;const stream=await download.createReadStream();let contents='';for await(const chunk of stream!)contents+=chunk.toString();expect(contents).toBe('{broken-json');
 await panel.getByRole('button',{name:'Descartar envío pendiente R10'}).click();await expect(panel.getByRole('button',{name:'Exportar envío pendiente R10'})).toHaveCount(0);expect(await page.evaluate(()=>sessionStorage.getItem('weaver.r10.transport.pending.v1'))).toBeNull();await page.reload();await expect(panel.getByRole('alert')).toHaveCount(0);
});

test('response accepted with lost reply recovers frozen content after reload',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const created=await page.request.post(url+'/api/research/r10/protocols',{data:{protocol:{config:{},participant_slot:'synthetic-response',role:'observer',order_index:0,stimuli:[{id:'clip',reference:'synthetic',start_s:0,end_s:2}]}}});expect(created.ok()).toBeTruthy();const saved=await created.json();await page.goto(url);await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).locator('..').filter({hasText:saved.id}).getByRole('button',{name:'Abrir protocolo congelado R10'}).click();
 const panel=page.getByRole('region',{name:'Respuestas guardadas R10',exact:true});await expect(panel.getByRole('button',{name:'Guardar respuesta R10',exact:true})).toBeEnabled();const original=JSON.parse(await page.getByLabel('Respuesta JSON R10').inputValue());original.ratings.pleasure=75;await page.getByLabel('Respuesta JSON R10').fill(JSON.stringify(original));
 const sent:any[]=[];let dropped=false;await page.route('**/api/research/r10/responses',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}sent.push(route.request().postDataJSON());const result=await route.fetch();if(!dropped){dropped=true;await route.abort('failed');}else await route.fulfill({response:result});});await panel.getByRole('button',{name:'Guardar respuesta R10',exact:true}).click();await expect(panel.getByRole('button',{name:'Recuperar envío de respuesta R10'})).toBeVisible();await page.reload();await panel.getByRole('button',{name:'Recuperar envío de respuesta R10'}).click();await expect(panel.getByRole('button',{name:'Recuperar envío de respuesta R10'})).toHaveCount(0);expect(sent).toHaveLength(2);expect(sent[1]).toEqual(sent[0]);const listed=await page.request.get(url+'/api/research/r10/responses');const rows=await listed.json();expect(rows).toHaveLength(1);const artifact=await page.request.get(url+`/api/research/r10/responses/${rows[0].id}/artifacts/result.json`);const result=await artifact.json();expect(result.validated.response.ratings.pleasure).toBe(75);expect(result.validated.response.ratings.beauty).toBeNull();expect(result.transport).toBeNull();await expect(panel).toContainText(rows[0].id);
 const analysis=page.getByRole('region',{name:'Análisis descriptivo R10',exact:true});await analysis.getByRole('button',{name:'Actualizar selección de respuestas R10'}).click();const selected=analysis.getByLabel(`Seleccionar respuesta R10 ${rows[0].id}`);await selected.check();await analysis.getByRole('button',{name:'Analizar respuestas seleccionadas R10'}).click();await expect(analysis).toContainText('1 registros seleccionados');const table=analysis.getByRole('table');await expect(table).toContainText('75');const beauty=table.getByRole('row').filter({hasText:'¿Qué belleza percibiste?'});await expect(beauty).toContainText('—');const downloading=page.waitForEvent('download');await analysis.getByRole('button',{name:'Exportar análisis descriptivo R10'}).click();const download=await downloading;const stream=await download.createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const exported=JSON.parse(text);expect(exported.sources[0].id).toBe(rows[0].id);expect(exported.groups[0].items.find((i:any)=>i.id==='beauty').median).toBeNull();const analyses=page.getByRole('region',{name:'Análisis congelados R10',exact:true});let lost=false;const submissions:any[]=[];await page.route('**/api/research/r10/analyses',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}submissions.push(route.request().postDataJSON());const response=await route.fetch();if(!lost){lost=true;await route.abort('failed');}else await route.fulfill({response});});await analyses.getByRole('button',{name:'Guardar análisis congelado R10'}).click();await expect(analyses.getByRole('button',{name:'Recuperar envío de análisis R10'})).toBeVisible();await page.reload();await analyses.getByRole('button',{name:'Recuperar envío de análisis R10'}).click();await expect(analyses.getByRole('button',{name:'Recuperar envío de análisis R10'})).toHaveCount(0);expect(submissions).toHaveLength(2);expect(submissions[1]).toEqual(submissions[0]);await analyses.getByRole('button',{name:'Abrir análisis congelado R10'}).click();await expect(analysis).toContainText('Resultado de análisis guardado');await expect(analysis.getByRole('table')).toContainText('75');const savedAnalyses=await page.request.get(url+'/api/research/r10/analyses');expect(await savedAnalyses.json()).toHaveLength(1);
 let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});let seen!:()=>void;const captured=new Promise<void>(r=>{seen=r;});await page.route('**/api/research/r10/analyses/*/artifacts/result.json',async route=>{const response=await route.fetch();seen();await gate;await route.fulfill({response});});await analyses.getByRole('button',{name:'Abrir análisis congelado R10'}).click();await captured;await selected.uncheck();release();await expect(analyses.getByRole('button',{name:'Abrir análisis congelado R10'})).toBeEnabled();await expect(analysis.getByRole('table')).toHaveCount(0);await expect(analysis.getByRole('button',{name:'Analizar respuestas seleccionadas R10'})).toBeDisabled();

});

test('explicit web pairs preserve direction and unanswered ratings',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const listed=await page.request.get(url+'/api/research/r10/responses');const rows=await listed.json();expect(rows).toHaveLength(1);const artifact=await page.request.get(url+`/api/research/r10/responses/${rows[0].id}/artifacts/result.json`);const existing=await artifact.json();const body=existing.request;body.response.trial_id='trial-0002';body.response.ratings.pleasure=100;const second=await page.request.post(url+'/api/research/r10/responses',{data:body});expect(second.ok()).toBeTruthy();const target=await second.json();await page.goto(url);
 const panel=page.getByRole('region',{name:'Contrastes pareados R10',exact:true});await panel.getByLabel('Referencia del par R10').selectOption(rows[0].id);await panel.getByLabel('Destino del par R10').selectOption(target.id);await panel.getByRole('button',{name:'Agregar par R10'}).click();await panel.getByRole('button',{name:'Calcular pares R10'}).click();const table=panel.getByRole('table',{name:'Diferencias del par R10 1'});await expect(table.getByRole('row').filter({hasText:'pleasure'})).toContainText('25');await expect(table.getByRole('row').filter({hasText:'beauty'})).toContainText('unanswered');
 const downloading=page.waitForEvent('download');await panel.getByRole('button',{name:'Exportar pares R10'}).click();const download=await downloading;const stream=await download.createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const result=JSON.parse(text);expect(result.pairs[0].reference_id).toBe(rows[0].id);expect(result.pairs[0].target_id).toBe(target.id);expect(result.pairs[0].items.find((i:any)=>i.id==='pleasure').target_minus_reference).toBe(25);await panel.getByLabel('Pares JSON R10').fill('{"pairs":[]}');await expect(panel.getByRole('table')).toHaveCount(0);
});
