import {test,expect} from '@playwright/test';
test('trial player condition gates paused seeks and nominal playback',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{conditions:['video_only','sound_only','audiovisual','desynchronized'],desynchronization_s:-.5},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});expect(response.ok()).toBeTruthy();await page.goto(url);
 await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).click();const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});
 const prepare=async(id:string)=>{await panel.getByLabel('Ensayo para reproducir R10').selectOption(id);await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();};
 await prepare('trial-0001');expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBeTruthy();await expect(panel.locator('audio')).toHaveCount(0);
 await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.7');await expect.poll(async()=>panel.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(1,1);expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBeTruthy();
 await prepare('trial-0002');await expect(panel.locator('video')).toHaveCount(0);await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();
 await prepare('trial-0003');await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.15);await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();expect(await panel.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.3);
 await prepare('trial-0004');await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.2');await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await page.waitForTimeout(100);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();await expect.poll(async()=>panel.locator('audio').evaluate((a:HTMLAudioElement)=>!a.paused)).toBeTruthy();await panel.getByRole('button',{name:'Pausar ensayo R10'}).click();
 const sent:any[]=[];let dropped=false;await page.route('**/api/research/r10/transports',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}sent.push(route.request().postDataJSON());const result=await route.fetch();if(!dropped){dropped=true;await route.abort('failed');}else await route.fulfill({response:result});});
 await panel.getByRole('button',{name:'Guardar transporte R10',exact:true}).click();await expect(page.getByRole('button',{name:'Recuperar envío de transporte R10'})).toBeVisible();await page.reload();await expect(page.getByRole('region',{name:'Player de ensayo R10'})).toHaveCount(0);await page.getByRole('button',{name:'Recuperar envío de transporte R10'}).click();await expect(page.getByRole('button',{name:'Recuperar envío de transporte R10'})).toHaveCount(0);expect(sent).toHaveLength(2);expect(sent[1]).toEqual(sent[0]);const records=await page.request.get(url+'/api/research/r10/transports');expect(records.ok()).toBeTruthy();const rows=await records.json();expect(rows).toHaveLength(1);const stored=await page.request.get(url+`/api/research/r10/transports/${rows[0].id}/artifacts/trace.json`);const telemetry=await stored.json();expect(telemetry.trial_id).toBe('trial-0004');expect(telemetry.events.some((e:any)=>e.kind==='seek')).toBeTruthy();expect(telemetry.events.some((e:any)=>e.kind==='play_requested')).toBeTruthy();expect(telemetry.events.some((e:any)=>e.kind==='snapshot')).toBeTruthy();expect(telemetry.events.every((e:any,i:number)=>e.sequence===i)).toBeTruthy();
 await page.reload();await expect(page.getByRole('region',{name:'Player de ensayo R10'})).toHaveCount(0);
});

test('positive audio offset does not restart exhausted sound and buffering pauses clock',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{conditions:['audiovisual','desynchronized'],desynchronization_s:.5},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});expect(response.ok()).toBeTruthy();const saved=await response.json();await page.goto(url);
 await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).locator('..').filter({hasText:saved.id}).getByRole('button',{name:'Abrir protocolo congelado R10'}).click();const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});
 await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;});await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect.poll(async()=>Number(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue())).toBeGreaterThan(.1);
 await panel.locator('video').evaluate(v=>v.dispatchEvent(new Event('waiting')));await expect(panel.getByRole('status')).toContainText('Pausado por buffering');const paused=await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue();await page.waitForTimeout(150);expect(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue()).toBe(paused);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();await panel.locator('video').evaluate(v=>v.dispatchEvent(new Event('canplay')));await expect(panel.getByRole('button',{name:'Pausar ensayo R10'})).toBeDisabled();
 await panel.getByLabel('Ensayo para reproducir R10').selectOption('trial-0002');await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await expect(panel.getByRole('button',{name:'Reproducir ensayo R10'})).toBeEnabled();await panel.locator('audio').evaluate((a:HTMLAudioElement)=>{a.muted=true;(a as any).starts=0;a.addEventListener('play',()=>{(a as any).starts++;});});await panel.getByLabel('Tiempo nominal del ensayo R10').fill('0.6');await expect.poll(async()=>panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeCloseTo(1.1,1);await expect.poll(async()=>panel.locator('video').evaluate((v:HTMLVideoElement)=>v.seeking)).toBeFalsy();await panel.getByRole('button',{name:'Reproducir ensayo R10'}).click();await expect(panel.getByRole('status')).toContainText('Fin del transporte nominal');expect(await panel.getByLabel('Tiempo nominal del ensayo R10').inputValue()).toBe('1.2');expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>(a as any).starts)).toBe(1);expect(await panel.locator('audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBeTruthy();
});

test('metadata resolved after player unmount cannot revive media',async({page})=>{
 test.skip(!process.env.LAB_R10_PLAYER_URL,'experience-stimulus fixture required');const url=process.env.LAB_R10_PLAYER_URL!;
 const response=await page.request.post(url+'/api/research/r10/r05-protocols',{data:{config:{},participant_slot:'synthetic',role:'observer',order_index:0,stimuli:[{id:'clip',r05_id:'b'.repeat(32),arm:'single'}]}});const saved=await response.json();await page.goto(url);await page.getByRole('button',{name:'Abrir protocolo congelado R10'}).locator('..').filter({hasText:saved.id}).getByRole('button',{name:'Abrir protocolo congelado R10'}).click();
 let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});let captured!:()=>void;const seen=new Promise<void>(r=>{captured=r;});
 await page.route('**/trials/*/media-info',async route=>{const result=await route.fetch();captured();await gate;await route.fulfill({response:result});});
 const panel=page.getByRole('region',{name:'Player de ensayo R10',exact:true});await panel.getByRole('button',{name:'Preparar reproducción R10'}).click();await seen;await page.getByLabel('Protocolo JSON R10').fill('{}');await expect(panel).toHaveCount(0);release();await page.waitForTimeout(100);await expect(page.locator('video')).toHaveCount(0);await expect(page.locator('audio')).toHaveCount(0);
});
