import {test,expect} from '@playwright/test';
test('production application loads research on demand and runs all R13 controls',async({page})=>{
 test.skip(!process.env.LAB_FULL_UI_URL,'explicit isolated full application fixture required');
 const origin=process.env.LAB_FULL_UI_URL!;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));
 const requested:string[]=[];page.on('request',r=>requested.push(r.url()));
 await page.goto(origin);
 await expect(page.getByRole('heading',{name:'Weaver / laboratorio corporal'})).toBeVisible();
 expect(requested.some(url=>url.includes('ResearchPanel-'))).toBe(false);
 await page.getByRole('button',{name:'Investigación',exact:true}).click();
 const panel=page.getByRole('region',{name:'Transferencia reservada R13'});
 await expect(panel).toBeVisible();
 expect(requested.some(url=>url.includes('ResearchPanel-'))).toBe(true);
 await panel.getByRole('button',{name:'Cargar control sintético R13'}).click();
 await panel.getByLabel('Control: mezclar objetivos de entrenamiento',{exact:true}).check();
 await panel.getByLabel('Prefijo de adaptación (0 = sin adaptar)',{exact:true}).fill('30');
 await panel.getByLabel('Adaptación R13',{exact:true}).selectOption('prefix_only');
 const posted=page.waitForResponse(r=>r.url().endsWith('/api/research/r13')&&r.request().method()==='POST');
 await panel.getByRole('button',{name:'Correr transferencia R13'}).click();
 const accepted=await posted;expect(accepted.ok()).toBe(true);const id=(await accepted.json()).id;
 const table=panel.getByRole('table',{name:`Resultados transferencia ${id}`});
 await expect(table).toBeVisible({timeout:15000});
 await expect(table.getByRole('columnheader')).toHaveCount(12);
 const response=await page.request.get(`${origin}/api/research/r13/${id}/artifacts/result.json`);
 expect(response.ok()).toBe(true);const result=await response.json();
 expect(result.models.reserved.training_sequences).toEqual(['reserved:prefix']);
 expect(Object.keys(result.results[0].mean_mse)).toHaveLength(9);
 expect(result.results[0].common_count).toBe(149);
 await expect(panel.getByRole('alert')).toHaveCount(0);
 await page.getByRole('button',{name:'Instrumento',exact:true}).click();
 await expect(panel).toHaveCount(0);
 expect(errors).toEqual([]);
});
