import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('paired-camera reconstruction, explicit failures and portable settings with real API',async({page})=>{
 test.skip(!process.env.LAB_COMPONENT_TEST_URL,'isolated API/Vite required');
 const origin=process.env.LAB_COMPONENT_TEST_URL!;
 await page.route(`${origin}/multiview-test`,route=>route.fulfill({contentType:'text/html',body:'<div id="test-root"></div>'}));await page.goto(`${origin}/multiview-test`);
 await page.addScriptTag({type:'module',content:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {SpatialPanel} from '/src/SpatialPanel.tsx';
 const api=async(path,body)=>{const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(JSON.stringify(value));return value};ReactDOM.createRoot(document.getElementById('test-root')).render(React.createElement(SpatialPanel,{api}));`});
 const panel=page.getByRole('region',{name:'Reconstrucción multivista R09',exact:true});
 await panel.getByRole('button',{name:'Cargar control sintético multivista R09'}).click();
 const input=panel.getByRole('textbox',{name:'Pares y calibración JSON R09',exact:true});await expect(input).toHaveValue(/"calibration_kind": "synthetic"/);const original=JSON.parse(await input.inputValue());
 expect(original.calibration_kind).toBe('synthetic');let calculations=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/research/r09/multiview'))calculations++});
 await panel.getByRole('button',{name:'Reconstruir pares multivista R09'}).click();
 await expect(panel.getByText('Multivista R09: 5 puntos inferidos; 0 faltantes.',{exact:false})).toBeVisible();
 await expect(panel.getByRole('table',{name:'Diagnóstico multivista R09'})).toBeVisible();
 const exported=page.waitForEvent('download');await panel.getByRole('button',{name:'Exportar resultado multivista R09'}).click();
 const result=JSON.parse(await readFile((await(await exported).path())!,'utf8'));
 expect(result.stream.frames[0].points[0].position[2]).toBeCloseTo(4,8);expect(result.stream.frames[0].points[0].state).toBe('inferred');expect(result.request.left_camera).toEqual(original.left_camera);
 const settingsExport=page.waitForEvent('download');await panel.getByRole('button',{name:'Exportar ajustes multivista R09'}).click();
 const portable=JSON.parse(await readFile((await(await settingsExport).path())!,'utf8'));
 expect(Object.keys(portable).sort()).toEqual(['schema_version','settings']);expect(Object.keys(portable.settings)).toHaveLength(4);
 await panel.getByRole('spinbutton',{name:'Paralaje mínimo multivista (grados)'}).fill('89');
 await panel.getByRole('button',{name:'Reconstruir pares multivista R09'}).click();
 await expect(panel.getByText('Multivista R09: 0 puntos inferidos; 5 faltantes.',{exact:false})).toBeVisible();await expect(panel.getByRole('table')).toContainText('insufficient_parallax');
 await panel.getByLabel('Importar ajustes multivista R09').setInputFiles({name:'settings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(portable))});
 await expect(panel.getByRole('spinbutton',{name:'Paralaje mínimo multivista (grados)'})).toHaveValue('1');
 expect(calculations).toBe(2);expect(JSON.parse(await input.inputValue()).left_camera).toEqual(original.left_camera);
 await panel.getByRole('button',{name:'Reconstruir pares multivista R09'}).click();await expect(panel.getByText('Multivista R09: 5 puntos inferidos; 0 faltantes.',{exact:false})).toBeVisible();
 await panel.getByRole('button',{name:'Usar stream multivista declarado R09'}).click();
 await page.getByRole('button',{name:'Procesar observaciones R09',exact:true}).click();await expect(page.getByText('Contrato validado: calibrated_multiview · 3D · metres',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Guardar stream declarado R09',exact:true}).click();await expect(page.getByRole('button',{name:'Abrir conversión R09',exact:true})).toBeVisible();
});
