import {test,expect} from '@playwright/test';

test('R12 delayed archived loads and native inspections preserve the current protocol',async({page})=>{
 test.skip(!process.env.LAB_R12_CONTEXT_URL,'isolated production laboratory required');
 const origin=process.env.LAB_R12_CONTEXT_URL!;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(origin);const before=await(await page.request.get(`${origin}/api/state`)).json();
 await page.getByRole('button',{name:'Investigación',exact:true}).click();
 const panel=page.getByRole('region',{name:'Mediciones y tarea R12'});
 const editor=panel.getByLabel('Mediciones y protocolo JSON R12',{exact:true});
 await expect(editor).toBeVisible();
 const base=JSON.parse(await editor.inputValue());
 const metadata={...base,task:'Archived CSV task'};delete metadata.samples;delete metadata.schema_version;delete metadata.line;
 const savedResponse=await page.request.post(`${origin}/api/research/r12/csv/imports`,{data:{metadata,csv_text:'index,time_s,hr,power\n0,0,60,2\n1,1,70,2\n2,2,80,2\n',mapping:{delimiter:',',index_column:'index',time_column:'time_s',time_units:'seconds',channel_columns:{hr:'hr',p:'power'}}}});
 expect(savedResponse.ok(),await savedResponse.text()).toBe(true);const saved=await savedResponse.json();
 await panel.getByText('Importar tabla CSV R12',{exact:true}).click();
 await panel.getByRole('button',{name:'Actualizar imports CSV R12',exact:true}).click();
 const load=panel.getByRole('button',{name:`Usar import CSV R12 ${saved.id}`,exact:true});await expect(load).toBeVisible();
 const loadURL=`${origin}/api/research/r12/csv/imports/${saved.id}/artifacts/result.json`;
 let release!:()=>void;let reached=false;const held=new Promise<void>(resolve=>release=resolve);
 await page.route(loadURL,async route=>{const result=await route.fetch();reached=true;await held;await route.fulfill({response:result})});
 await load.click();await expect.poll(()=>reached).toBe(true);
 const changed={...base,task:'Edited while CSV was loading'};await editor.fill(JSON.stringify(changed));release();
 await expect(panel.getByRole('alert').filter({hasText:'contexto CSV cambió durante la carga'})).toBeVisible();
 expect(JSON.parse(await editor.inputValue())).toEqual(changed);
 await page.unroute(loadURL);await load.click();await expect.poll(async()=>JSON.parse(await editor.inputValue()).task).toBe('Archived CSV task');
 // Start a native inspection, then apply a different archived CSV while its real response is held.
 await editor.fill(JSON.stringify(base));
 let releaseInspect!:()=>void;let inspectReached=false;const inspectHeld=new Promise<void>(resolve=>releaseInspect=resolve);
 const inspectURL=`${origin}/api/research/r12/inspect`;
 await page.route(inspectURL,async route=>{const result=await route.fetch();expect(result.ok()).toBe(true);inspectReached=true;await inspectHeld;await route.fulfill({response:result})});
 await panel.getByRole('button',{name:'Analizar mediciones R12',exact:true}).click();await expect.poll(()=>inspectReached).toBe(true);
 await load.click();await expect.poll(async()=>JSON.parse(await editor.inputValue()).task).toBe('Archived CSV task');releaseInspect();
 await expect(panel.getByRole('alert').filter({hasText:'El protocolo R12 cambió durante la carga'})).toBeVisible();
 await expect(panel.getByRole('table',{name:'Resultados R12 control'})).toHaveCount(0);
 await expect(panel.getByRole('button',{name:'Guardar corrida R12',exact:true})).toBeDisabled();
 await page.unroute(inspectURL);
 await panel.getByRole('button',{name:'Analizar mediciones R12',exact:true}).click();
 const table=panel.getByRole('table',{name:'Resultados R12 control'});await expect(table).toBeVisible();
 await expect(table.getByRole('row').nth(1)).toContainText('70');
 await expect(panel.getByRole('button',{name:'Guardar corrida R12',exact:true})).toBeEnabled();
 const stored=page.waitForResponse(r=>r.url()===`${origin}/api/research/r12/measurements`&&r.request().method()==='POST');
 await panel.getByRole('button',{name:'Guardar corrida R12',exact:true}).click();const nativeResponse=await stored;
 expect(nativeResponse.ok()).toBe(true);const native=await nativeResponse.json();
 const nativeURL=`${origin}/api/research/r12/measurements/${native.id}/artifacts/result.json`;
 await editor.fill(JSON.stringify(base));
 let releaseNative!:()=>void;let nativeReached=false;const nativeHeld=new Promise<void>(resolve=>releaseNative=resolve);
 await page.route(nativeURL,async route=>{const response=await route.fetch();nativeReached=true;await nativeHeld;await route.fulfill({response})});
 await panel.getByRole('button',{name:'Abrir corrida R12',exact:true}).click();await expect.poll(()=>nativeReached).toBe(true);
 await load.click();await expect.poll(async()=>JSON.parse(await editor.inputValue()).task).toBe('Archived CSV task');releaseNative();
 await expect(panel.getByRole('alert').filter({hasText:'El protocolo R12 cambió durante la carga'})).toBeVisible();
 await expect(table).toHaveCount(0);await expect(panel.getByRole('button',{name:'Guardar corrida R12',exact:true})).toBeDisabled();
 await page.unroute(nativeURL);await panel.getByRole('button',{name:'Abrir corrida R12',exact:true}).click();
 await expect(table.getByRole('row').nth(1)).toContainText('70');
 const after=await(await page.request.get(`${origin}/api/state`)).json();expect(after.preset).toEqual(before.preset);expect(after.source).toEqual(before.source);expect(after.calibration).toEqual(before.calibration);expect(errors).toEqual([]);
});
