import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('R12 ISO CSV explicit origin, real archive, exact UTF8 bytes and native measurement analysis',async({page})=>{
 test.skip(!process.env.LAB_COMPONENT_TEST_URL,'isolated API/Vite proxy required');
 const origin=process.env.LAB_COMPONENT_TEST_URL!;
 await page.route(`${origin}/r12-csv-test`,r=>r.fulfill({contentType:'text/html',body:'<div id="test-root"></div>'}));
 await page.goto(`${origin}/r12-csv-test`);
 await page.addScriptTag({type:'module',content:`
 import React from '/node_modules/.vite/deps/react.js';
 import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';
 import {PhysiologyPanel} from '/src/PhysiologyPanel.tsx';
 const api=async(path,body)=>{const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(JSON.stringify(value));return value};
 ReactDOM.createRoot(document.getElementById('test-root')).render(React.createElement(PhysiologyPanel,{api}));
 `});
 await page.getByText('Importar tabla CSV R12',{exact:true}).click();
 const raw='\uFEFFidx;t_ms;hr;power;ignored\r\n0;2026-10-03T12:00:00Z;60;2;a\r\n1;2026-10-03T09:00:01-03:00;;2;b\r\n2;2026-10-03T12:00:02Z;80;2;c\r\n3;2026-10-03T12:00:03Z;90;2;d\r\n';
 await page.getByLabel('Archivo CSV R12',{exact:true}).setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(raw)});
 const mapping={delimiter:';',index_column:'idx',time_column:'t_ms',time_units:'milliseconds',channel_columns:{hr:'hr',p:'power'},missing_tokens:[''],missing_cause:'declared_csv_missing'};
 await page.getByLabel('Mapeo CSV R12 JSON',{exact:true}).fill(JSON.stringify(mapping));
 await page.getByLabel('Formato temporal CSV R12').selectOption('iso8601');
 await page.getByLabel('Origen ISO CSV R12').fill('2026-10-03T12:00:00Z');
 await page.getByRole('button',{name:'Inspeccionar CSV R12',exact:true}).click();
 await expect(page.getByText('CSV R12: 4 muestras',{exact:false})).toBeVisible();
 const accepted=page.waitForResponse(r=>r.url().endsWith('/api/research/r12/csv/imports')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Guardar y usar conversión CSV en análisis R12',exact:true}).click();
 const response=await accepted;expect(response.ok()).toBe(true);const saved=await response.json();
 const archived=await page.request.get(`${origin}/api/research/r12/csv/imports/${saved.id}/artifacts/source.csv`);
 expect((await archived.body()).equals(Buffer.from(raw))).toBe(true);
 const request=JSON.parse(await page.getByLabel('Mediciones y protocolo JSON R12',{exact:true}).inputValue());
 expect(request.samples).toHaveLength(4);
 expect(request.samples.map((row:any)=>row.source_time_s)).toEqual([0,1,2,3]);
 expect(request.samples[1].missing_causes).toEqual({hr:'declared_csv_missing'});
 expect(request.provider).toBe('synthetic');
 expect(request.clock.source_clock).toBe('synthetic');
 await page.getByRole('button',{name:'Analizar mediciones R12',exact:true}).click();
 const table=page.getByRole('table',{name:'Resultados R12 control'});
 await expect(table.getByRole('row').nth(1)).toContainText('85');
 await expect(table.getByRole('row').nth(2)).toContainText('6');
 await expect(page.getByRole('button',{name:`Usar import CSV R12 ${saved.id}`})).toBeVisible();
 const settingsDownload=page.waitForEvent('download');
 await page.getByRole('button',{name:'Exportar mapeo CSV R12',exact:true}).click();
 const downloaded=await settingsDownload;expect(downloaded.suggestedFilename()).toBe('r12-csv-mapping.json');
 const portable=JSON.parse(await readFile((await downloaded.path())!,'utf8'));
 expect(portable.schema_version).toBe(2);expect(portable.time_units).toBe('iso8601');expect(portable.time_origin).toBeUndefined();
 await page.getByLabel('Importar mapeo CSV R12',{exact:true}).setInputFiles({name:'map.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...portable,time_origin:'2026-10-03T12:00:00Z'}))});
 await expect(page.getByLabel('Origen ISO CSV R12')).toHaveValue('');
 await page.getByLabel('Origen ISO CSV R12').fill('2026-10-03T12:00:00Z');
 await expect(page.getByRole('alert')).toHaveCount(0);
 await page.route('**/api/research/r12/csv/inspect',async route=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,300));await route.fulfill({response})});
 const inFlight=page.waitForRequest(r=>r.url().endsWith('/api/research/r12/csv/inspect'));
 await page.getByRole('button',{name:'Inspeccionar CSV R12',exact:true}).click();
 await inFlight;
 const changed={...request,task:'Changed during inspection'};
 await page.getByLabel('Mediciones y protocolo JSON R12',{exact:true}).fill(JSON.stringify(changed));
 await expect(page.getByRole('alert')).toContainText('contexto CSV cambió');
 await expect(page.getByRole('button',{name:'Guardar y usar conversión CSV en análisis R12',exact:true})).toHaveCount(0);
});
