import {test,expect} from '@playwright/test';
test('R05 optional modulation and f1/2 series survive portable UI configuration and verified worker',async({page})=>{
 test.skip(!process.env.LAB_R05_NETWORK_URL,'explicit synthetic HTTP fixture required');
 const origin=process.env.LAB_R05_NETWORK_URL!;await page.goto(origin);
 await page.getByRole('checkbox',{name:'Comparar con mapeo de amplitud R05',exact:true}).check();
 await page.getByRole('checkbox',{name:'Modular frecuencia del mapeo R05',exact:true}).check();
 await page.getByLabel('Modulación depth R05',{exact:true}).fill('.4');
 await page.getByLabel('Modulación smoothing_s R05',{exact:true}).fill('.02');
 await page.getByRole('button',{name:'Serie f1/2 R05',exact:true}).click();
 await page.getByRole('button',{name:'Exportar configuración R05',exact:true}).click();
 const text=page.getByLabel('Configuración R05 JSON',{exact:true});await expect(text).not.toHaveValue('');
 const config=JSON.parse(await text.inputValue());
 expect(config.resonators.ratios).toEqual([.5,1,1.5,2,2.5,3]);
 expect(config.mapping.frequency_modulation).toEqual({depth:.4,smoothing_s:.02});
 await page.getByRole('checkbox',{name:'Modular frecuencia del mapeo R05',exact:true}).uncheck();
 await page.getByRole('button',{name:'Importar configuración R05',exact:true}).click();
 await expect(page.getByRole('checkbox',{name:'Modular frecuencia del mapeo R05',exact:true})).toBeChecked();
 await expect(page.getByLabel('Modulación depth R05',{exact:true})).toHaveValue('0.4');
 const evaluations=await(await page.request.get(`${origin}/api/evaluations`)).json();
 const {schema_version,...parameters}=config;
 const response=await page.request.post(`${origin}/api/research/r05`,{data:{...parameters,resonators:{...config.resonators,sample_rate:8000},selection:{evaluation_id:evaluations[0].id,run_index:0,signal_id:'zone.1.speed',start_s:.2,end_s:2}}});
 expect(response.status()).toBe(200);const id=(await response.json()).id;
 await expect(page.getByRole('button',{name:`Explorar figura R05 ${id}`,exact:true})).toBeVisible({timeout:15000});
 const report=await(await page.request.get(`${origin}/api/research/r05/${id}/artifacts/result.json`)).json();
 expect(report.mapping_preparation.mapping.frequency_modulation).toEqual({depth:.4,smoothing_s:.02});
 expect(report.mapping_preparation.frequency_target_updates.length).toBeGreaterThan(1);
 const pcm=await page.request.get(`${origin}/api/research/r05/${id}/artifacts/mapped-sum.wav`);expect(pcm.status()).toBe(200);
 await page.getByRole('button',{name:`Explorar figura R05 ${id}`,exact:true}).click();
 await page.getByRole('combobox',{name:/^Brazo de proyección R05/}).selectOption('mapped');
 await page.getByRole('button',{name:'Leer ventana de proyección R05',exact:true}).click();
 await expect(page.getByText('Ventana congelada:',{exact:false})).toContainText('6 voces');
});
