import {test,expect} from '@playwright/test';
for(const paired of [false,true])test(`R05 ${paired?'mapped pair':'single'} verified source video follows audio crop, pause, seek, loop and tail`,async({page})=>{
 test.skip(!process.env.LAB_R05_VIDEO_URL,'explicit HTTP fixture with generated MP4 required');
 const origin=process.env.LAB_R05_VIDEO_URL!;await page.goto(origin);
 const evaluations=await(await page.request.get(`${origin}/api/evaluations`)).json();
 const response=await page.request.post(`${origin}/api/research/r05`,{data:{selection:{evaluation_id:evaluations[0].id,run_index:0,signal_id:'zone.1.speed',start_s:.2,end_s:2},resonators:{sample_rate:8000},excitation:{high:.1,low:.02},render:{tail_s:.5},...(paired?{mapping:{}}:{})}});
 expect(response.status()).toBe(200);const id=(await response.json()).id;
 const explore=page.getByRole('button',{name:`Explorar figura R05 ${id}`,exact:true});
 await expect(explore).toBeVisible({timeout:15000});await explore.click();
 if(paired)await page.getByRole('combobox',{name:/^Brazo de proyección R05/}).selectOption('mapped');
 await page.getByRole('button',{name:'Mostrar video de origen R05',exact:true}).click();
 const video=page.getByLabel('Video de origen R05',{exact:true});
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.2,1);
 await page.getByRole('button',{name:'Cargar audio R05',exact:true}).click();
 const audio=page.getByLabel('Reproductor de vista R05',{exact:true});
 await expect.poll(()=>audio.evaluate((a:HTMLAudioElement)=>a.readyState)).toBeGreaterThanOrEqual(2);
 await audio.evaluate((a:HTMLAudioElement)=>{a.muted=true;a.currentTime=.5;});
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.7,1);
 expect(await video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);
 const offset=page.getByLabel('Desfase video/audio R05 (s)',{exact:true});
 const audioSrc=await audio.getAttribute('src');
 await offset.fill('.25');
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.95,1);
 expect(await audio.getAttribute('src')).toBe(audioSrc);
 await page.getByRole('button',{name:'Exportar proyección R05',exact:true}).click();
 const preset=page.getByLabel('Preset de proyección R05 JSON',{exact:true});
 await expect(preset).not.toHaveValue('');
 expect(JSON.parse(await preset.inputValue()).playback.video_offset_s).toBe(.25);
 await offset.fill('-.25');
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.45,1);
 await offset.fill('0');
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.7,1);
 await page.getByRole('button',{name:'Cargar pose congelada R05',exact:true}).click();
 const skeleton=page.getByLabel('Pose congelada R05',{exact:true});
 await expect(skeleton).toBeVisible();
 await expect(skeleton.locator('circle')).toHaveCount(17);
 await audio.evaluate((a:HTMLAudioElement)=>{a.currentTime=.84;});
 await expect(page.getByLabel('Diagnóstico pose R05',{exact:true})).toContainText('ausente');
 await expect(skeleton).toHaveCount(0);
 await audio.evaluate((a:HTMLAudioElement)=>{a.currentTime=.515;});
 await page.getByLabel('Antigüedad máxima pose R05 (s)',{exact:true}).fill('.001');
 await expect(page.getByLabel('Diagnóstico pose R05',{exact:true})).toContainText('Gap');
 await expect(skeleton).toHaveCount(0);
 await page.getByLabel('Antigüedad máxima pose R05 (s)',{exact:true}).fill('.1');
 await expect(skeleton).toBeVisible();
 await page.getByRole('checkbox',{name:'Mostrar pose R05',exact:true}).uncheck();
 await expect(skeleton).toHaveCount(0);
 await page.getByRole('checkbox',{name:'Mostrar pose R05',exact:true}).check();
 await expect(skeleton).toBeVisible();
 const frames=await video.evaluate((v:HTMLVideoElement)=>v.getVideoPlaybackQuality().totalVideoFrames);
 await audio.evaluate((a:HTMLAudioElement)=>a.play());
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.getVideoPlaybackQuality().totalVideoFrames)).toBeGreaterThan(frames+3);
 await audio.evaluate((a:HTMLAudioElement)=>a.pause());
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);
 const t=await audio.evaluate((a:HTMLAudioElement)=>a.currentTime);
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(.2+t,1);
 await audio.evaluate((a:HTMLAudioElement)=>{a.currentTime=2;});
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(2,1);
 await audio.evaluate((a:HTMLAudioElement)=>a.play());
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);
 await page.getByRole('checkbox',{name:'Loop de audio R05',exact:true}).check();
 await audio.evaluate((a:HTMLAudioElement)=>{a.currentTime=2.25;});
 await expect.poll(()=>audio.evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeLessThan(.4);
 await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(false);
 await audio.evaluate((a:HTMLAudioElement)=>a.pause());
 await page.getByRole('button',{name:'Importar proyección R05',exact:true}).click();
 await expect(offset).toHaveValue('0.25');
 await expect(audio).toHaveCount(0);
 await page.getByRole('button',{name:'Ocultar video de origen R05',exact:true}).click();
 await expect(video).toHaveCount(0);
 await expect(page.getByRole('alert').filter({hasText:/decode|decodificar|Error/})).toHaveCount(0);
});
