import {test,expect} from '@playwright/test';
test('R08 configurable candidate overlay keeps annotation draft unchanged',async({page})=>{
 test.skip(!process.env.LAB_R08_MASK_URL,'isolated HTTP fixture required');
 const origin=process.env.LAB_R08_MASK_URL!;
 await page.goto(origin);
 await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Preparar anotación R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 const draft=page.getByLabel('Anotación R08 JSON');const before=await draft.inputValue();
 const settings=page.getByLabel('Configuración de candidatos R08');
 await settings.fill('{invalid');
 await page.getByRole('button',{name:'Calcular candidatos R08',exact:true}).click();
 await expect(page.getByRole('alert')).toBeVisible();
 await expect(page.getByRole('button',{name:'Calcular candidatos R08',exact:true})).toBeEnabled();
 const config={target_rgb:[255,255,255],distance_rgb:442,roi:[0,0,.5,1],min_component_px:1,max_components:32,max_runs:10000};
 await settings.fill(JSON.stringify(config));
 await page.getByRole('button',{name:'Calcular candidatos R08',exact:true}).click();
 await expect(page.getByText(/Candidatos: 1\/1/)).toBeVisible();
 await expect(page.locator('svg rect')).toHaveCount(120);
 const first=page.locator('svg rect').first();
 await expect(first).toHaveAttribute('x','0');await expect(first).toHaveAttribute('width','0.5');
 await expect(draft).toHaveValue(before);
 expect(await(await page.request.get(`${origin}/api/research/r08`)).json()).toEqual([]);
 await page.getByRole('button',{name:'Ocultar candidatos R08',exact:true}).click();
 await expect(page.locator('svg rect')).toHaveCount(0);
 await expect(draft).toHaveValue(before);
 await page.getByLabel('Frame R08',{exact:true}).fill('1');
 await expect(page.getByText(/Tiempo fuente: 0.1 s. Imagen decodificada/)).toBeVisible();
 await expect(page.locator('svg rect')).toHaveCount(0);
});
