import {test,expect} from '@playwright/test';
test('R08 compare persisted curves preserves missing support and restores artifacts',async({page})=>{
 test.skip(!process.env.LAB_R08_COMPARE_URL,'isolated HTTP fixture required');
 const origin=process.env.LAB_R08_COMPARE_URL!;
 const media=await(await page.request.post(`${origin}/api/research/r08/probe`,{data:{media_id:'synthetic'}})).json();
 const frame=(index:number,y:number)=>({frame_index:index,time_s:media.frame_times_s[index],state:'observed',visible_segments:[[{x:0,y},{x:1,y}]]});
 const base={media_sha256:media.media_sha256,width_px:media.width_px,height_px:media.height_px};
 const reference=await(await page.request.post(`${origin}/api/research/r08`,{data:{media_id:'synthetic',annotation:{...base,frames:[frame(0,0),frame(1,0)]}}})).json();
 const candidate=await(await page.request.post(`${origin}/api/research/r08`,{data:{media_id:'synthetic',annotation:{...base,frames:[frame(0,.2)]}}})).json();
 await page.goto(origin);
 await page.getByRole('combobox',{name:'Referencia R08',exact:true}).selectOption(reference.id);
 await page.getByRole('combobox',{name:'Candidata R08',exact:true}).selectOption(candidate.id);
 await page.getByLabel('Muestras por tramo R08',{exact:true}).fill('16');
 await page.getByRole('button',{name:'Comparar revisiones R08',exact:true}).click();
 await expect(page.getByText('Soporte: 1/2 frames de referencia. Sin soporte: 1.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Ver comparación R08',exact:true})).toHaveCount(1);
 const jobs=await(await page.request.get(`${origin}/api/research/r08/comparisons`)).json();
 const url=`${origin}/api/research/r08/comparisons/${jobs[0].id}/artifacts/result.json`;
 const response=await page.request.get(url);expect(response.ok()).toBeTruthy();
 const result=await response.json();
 expect(result.request.samples_per_segment).toBe(16);
 expect(result.rows[0].sampled_hausdorff_px).toBeCloseTo(24,8);
 expect(result.rows[1].sampled_hausdorff_px).toBeNull();
 await page.reload();
 await expect(page.getByRole('button',{name:'Ver comparación R08',exact:true})).toHaveCount(1);
 await page.getByRole('button',{name:'Ver comparación R08',exact:true}).click();
 await expect(page.getByText('Soporte: 1/2 frames de referencia. Sin soporte: 1.',{exact:true})).toBeVisible();
 expect(await(await page.request.get(url)).body()).toEqual(await response.body());
 const download=page.locator(`a[href="/api/research/r08/comparisons/${jobs[0].id}/artifacts/manifest.json"]`);
 const event=page.waitForEvent('download');await download.click();expect((await event).suggestedFilename()).toBe('manifest.json');
});
