import {test,expect} from '@playwright/test';
test('R08 guided candidate requires explicit incorporation and frame application',async({page})=>{
 test.skip(!process.env.LAB_R08_PATH_URL,'isolated HTTP fixture required');
 const origin=process.env.LAB_R08_PATH_URL!;
 const m=await(await page.request.post(`${origin}/api/research/r08/probe`,{data:{media_id:'synthetic'}})).json();
 await page.request.post(`${origin}/api/research/r08/masks`,{data:{media_id:'synthetic',request:{media_sha256:m.media_sha256,width_px:m.width_px,height_px:m.height_px,frame_index:0,time_s:0,settings:{distance_rgb:442,min_component_px:1,roi:[0,0,.5,1]}}}});
 await page.goto(origin);
 await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Preparar anotación R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 const draft=page.getByLabel('Anotación R08 JSON');const before=await draft.inputValue();
 await page.getByRole('button',{name:'Proponer curva guiada R08',exact:true}).click();
 await expect(page.getByText(/Curva candidata R08: seed_outside_selected_component/)).toBeVisible();
 await expect(page.getByRole('button',{name:'Usar curva candidata como tramo R08',exact:true})).toBeDisabled();
 await page.getByLabel('Configuración de curva guiada R08').fill(JSON.stringify({component_id:1,start:{x:.1,y:.5},stop:{x:.4,y:.5},max_visited:100000,max_points:4096}));
 await page.getByRole('button',{name:'Proponer curva guiada R08',exact:true}).click();
 await expect(page.getByTestId('rope-candidate-path')).toHaveCount(1);
 await expect(draft).toHaveValue(before);
 await page.getByRole('button',{name:'Usar curva candidata como tramo R08',exact:true}).click();
 await expect(page.getByTestId('rope-candidate-path')).toHaveCount(0);
 await expect(draft).toHaveValue(before);
 await page.getByRole('button',{name:'Aplicar frame al borrador',exact:true}).click();
 const annotation=JSON.parse(await draft.inputValue());expect(annotation.frames).toHaveLength(1);
 expect(annotation.frames[0].visible_segments[0]).toHaveLength(49);
 expect(annotation.frames[0].curve_sources[0].relation).toBe('exact');
 expect(annotation.frames[0].curve_sources[0].path_manifest_sha256).toMatch(/^[a-f0-9]{64}$/);
 const svg=page.locator('svg');const box=(await svg.boundingBox())!;
 await svg.click({position:{x:box.width*.2,y:box.height*.6}});
 await page.getByRole('button',{name:'Aplicar frame al borrador',exact:true}).click();
 const edited=JSON.parse(await draft.inputValue());
 expect(edited.frames[0].visible_segments[0]).toHaveLength(50);
 expect(edited.frames[0].curve_sources[0].relation).toBe('edited');
 await page.getByRole('button',{name:'Guardar revisión R08',exact:true}).click();
 await expect(page.getByRole('button',{name:'Abrir revisión R08',exact:true})).toHaveCount(1);
 await page.reload();
 await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Abrir revisión R08',exact:true}).click();
 await expect.poll(async()=>{const t=await draft.inputValue();return t?JSON.parse(t).frames:null;}).toEqual(edited.frames);
 await page.getByRole('button',{name:'Verificar video R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 const pathId=edited.frames[0].curve_sources[0].path_run_id;
 const recover=page.getByRole('button',{name:'Recuperar curva candidata R08',exact:true});
 await expect(recover).toHaveCount(2);
 const cards=await recover.evaluateAll(nodes=>nodes.map(node=>node.parentElement!.textContent));
 await recover.nth(cards.findIndex(text=>text!.includes(pathId))).click();
 await expect(page.getByTestId('rope-candidate-path')).toHaveCount(1);
 expect(JSON.parse(await draft.inputValue()).frames).toEqual(edited.frames);
 const result=await(await page.request.get(`${origin}/api/research/r08/paths/${pathId}/artifacts/result.json`)).json();
 expect(result.points).toHaveLength(49);

});
