import {test,expect} from '@playwright/test';
test('explicit web recomputation reports source match without rewriting artifacts',async({page})=>{
 test.skip(!process.env.LAB_R08_FLOW_VERIFY_URL,'isolated fixture required');
 const origin=process.env.LAB_R08_FLOW_VERIFY_URL!;
 const media=await(await page.request.post(`${origin}/api/research/r08/probe`,{data:{media_id:'synthetic'}})).json();
 const request={media_sha256:media.media_sha256,width_px:media.width_px,height_px:media.height_px,start_frame_index:0,frame_times_s:media.frame_times_s.slice(0,3),seeds:[{x:.5,y:.5}]};
 const job=await(await page.request.post(`${origin}/api/research/r08/flow`,{data:{media_id:'synthetic',request}})).json();
 await expect.poll(async()=> (await(await page.request.get(`${origin}/api/research/r08/flow/${job.id}`)).json()).status).toBe('complete');
 const urls=['request.json','result.json','manifest.json'].map(name=>`${origin}/api/research/r08/flow/${job.id}/artifacts/${name}`);
 const before=await Promise.all(urls.map(async url=>(await page.request.get(url)).body()));
 await page.goto(origin);await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Preparar anotación R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 const draft=await page.getByLabel('Anotación R08 JSON').inputValue();
 await expect(page.getByText(/Coincidió contra la fuente en este recálculo/)).toHaveCount(0);
 await page.getByRole('button',{name:'Recalcular corrida temporal R08',exact:true}).click();
 await expect(page.getByText(/Recálculo temporal R08: complete.*Coincidió contra la fuente/)).toBeVisible();
 await page.getByText('Evidencia del recálculo temporal R08',{exact:true}).click();
 await expect(page.getByText(/Manifest ligado al recálculo/)).toBeVisible();
 for(const [i,url] of urls.entries())expect(await(await page.request.get(url)).body()).toEqual(before[i]);
 await expect(page.getByLabel('Anotación R08 JSON')).toHaveValue(draft);
 await page.reload();await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Preparar anotación R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 await expect(page.getByText(/Coincidió contra la fuente en este recálculo/)).toHaveCount(0);
});
