import {test,expect} from '@playwright/test';
test('R08 real decoded frame drawing revision and restoration',async({page})=>{
 test.skip(!process.env.LAB_R08_NETWORK_URL,'isolated HTTP fixture required');
 const origin=process.env.LAB_R08_NETWORK_URL!;
 expect(await(await page.request.get(`${origin}/api/research/r08`)).json()).toEqual([]);
 await page.goto(origin);
 await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 await page.getByRole('button',{name:'Preparar anotación R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 const svg=page.locator('svg');const box=(await svg.boundingBox())!;
 await svg.click({position:{x:box.width*.2,y:box.height*.3}});
 await svg.click({position:{x:box.width*.6,y:box.height*.5}});
 await page.getByRole('button',{name:'Aplicar frame al borrador',exact:true}).click();
 const draft=page.getByLabel('Anotación R08 JSON');
 let annotation=JSON.parse(await draft.inputValue());
 expect(annotation.frames[0].frame_index).toBe(0);
 expect(annotation.frames[0].visible_segments[0]).toHaveLength(2);
 expect(annotation.frames[0].visible_segments[0][0].x).toBeCloseTo(.2,2);
 await page.getByLabel('Frame R08', {exact:true}).fill('2');
 await expect(page.getByText(/Tiempo fuente: 0.2 s. Imagen decodificada/)).toBeVisible();
 await page.getByLabel('Estado R08').selectOption('unidentifiable');
 await page.getByLabel('occlusion',{exact:true}).check();
 await page.getByRole('button',{name:'Aplicar frame al borrador',exact:true}).click();
 annotation=JSON.parse(await draft.inputValue());
 expect(annotation.frames[1]).toMatchObject({frame_index:2,time_s:.2,state:'unidentifiable',visible_segments:[],causes:['occlusion']});
 await page.getByRole('button',{name:'Guardar revisión R08',exact:true}).click();
 await expect(page.getByRole('button',{name:'Abrir revisión R08',exact:true})).toHaveCount(1);
 await page.reload();
 await expect(page.getByRole('button',{name:'Abrir revisión R08',exact:true})).toHaveCount(1);
 await page.getByRole('button',{name:'Abrir revisión R08',exact:true}).click();
 await expect.poll(async()=>{const t=await draft.inputValue();return t?JSON.parse(t).frames:null;}).toEqual(annotation.frames);
 await page.getByLabel('Video de biblioteca R08').selectOption('synthetic');
 // Choosing a source explicitly resets the draft; recover the stored revision afterwards.
 await page.getByRole('button',{name:'Abrir revisión R08',exact:true}).click();
 await page.getByRole('button',{name:'Verificar video R08',exact:true}).click();
 await expect(page.getByText(/Imagen decodificada/)).toBeVisible();
 await page.getByRole('button',{name:'Guardar revisión R08',exact:true}).click();
 await expect(page.getByRole('button',{name:'Abrir revisión R08',exact:true})).toHaveCount(2);
 const jobs=await(await page.request.get(`${origin}/api/research/r08`)).json();
 expect(jobs.some((j:any)=>j.parent_manifest_sha256)).toBeTruthy();
});
