import {test,expect} from '@playwright/test';
test('external 3D stream persists and compares with explicit inferred support',async({page})=>{
 test.skip(!process.env.LAB_R09_EXTERNAL_URL,'isolated fixture required');const url=process.env.LAB_R09_EXTERNAL_URL!;await page.goto(url);
 const panel=page.getByRole('region',{name:'Observaciones espaciales R09',exact:true});
 const stream={source_id:'synthetic-3d',subject_slot:'slot',provider:'monocular_3d',dimensions:3,coordinate_frame:'model',units:'model_units',clock:{source_clock:'pts',common_clock:'session',offset_s:0,rate:1,uncertainty_s:.01,method:'declared_assumption'},frames:[{index:0,source_time_s:0,points:[{label:'hand',state:'inferred',position:[.1,.2,.3]}]}]};
 await panel.getByLabel('Modalidad R09').selectOption('validate');await panel.getByLabel('Observaciones JSON R09').fill(JSON.stringify(stream));await panel.getByRole('button',{name:'Procesar observaciones R09'}).click();
 const attempts:any[]=[];let first=true;await page.route('**/api/research/r09/conversions',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}attempts.push(route.request().postDataJSON());if(first){first=false;await route.fetch();await route.abort('failed');}else await route.continue();});
 await panel.getByRole('button',{name:'Guardar stream declarado R09'}).click();await expect(panel.getByRole('button',{name:'Recuperar guardado R09'})).toBeVisible();await page.reload();await panel.getByRole('button',{name:'Recuperar guardado R09'}).click();expect(attempts[1]).toEqual(attempts[0]);await panel.getByRole('button',{name:'Abrir conversión R09'}).click();await expect(panel.getByText(/inferidos 1/)).toBeVisible();await expect(panel.getByLabel('Puntos proyectados R09').locator('circle')).toHaveAttribute('fill','none');
 const rows=await(await page.request.get(url+'/api/research/r09/conversions')).json();expect(rows).toHaveLength(1);
 const compare=page.getByRole('region',{name:'Comparación espacial R09',exact:true});await compare.getByLabel('Origen de comparación R09').selectOption('saved');await compare.getByRole('button',{name:'Actualizar conversiones para comparar R09'}).click();await compare.getByLabel('Referencia guardado R09').selectOption(rows[0].id);await compare.getByLabel('Candidato guardado R09').selectOption(rows[0].id);await compare.getByLabel('Etiquetas de comparación R09').fill('["hand"]');await compare.getByRole('button',{name:'Guardar comparación espacial R09'}).click();await expect(compare.getByText(/Soporte espacial: 0\/0/)).toBeVisible();await compare.getByLabel('Admitir puntos inferidos R09').check();await compare.getByRole('button',{name:'Guardar comparación espacial R09'}).click();await expect(compare.getByText(/Soporte espacial: 1\/1/)).toBeVisible();await expect(compare.getByText(/Error medio sobre soporte: 0;/)).toBeVisible();
});
