'use strict';
const $=s=>document.querySelector(s), canvas=$('#body'), ctx=canvas.getContext('2d');
const edges=[[5,6],[5,7],[7,9],[6,8],[8,10],[5,11],[6,12],[11,12],[11,13],[13,15],[12,14],[14,16],[0,1],[0,2],[1,3],[2,4]];
let payload=null, revision=-1, pending=false, lastCapture=null, history=[], selected=0, soloRestore=null, muteRestore=1, generation=0, lastSuccess=0, built=false, lastError='';
const cards={};
function build(data){for(let n=1;n<=6;n++){const card=$('#zone-template').content.firstElementChild.cloneNode(true);card.style.setProperty('--color',data.colors[n-1]);card.dataset.n=n;card.querySelector('h3').textContent=data.labels[n-1];card.querySelector('.zone-number').textContent=`F${n}`;card.addEventListener('pointerdown',()=>{selected=n;highlight()});for(const input of card.querySelectorAll('input')){input.addEventListener('input',()=>{if(input.type==='range'){card.querySelector(`[data-value="${input.dataset.field}"]`).textContent=Number(input.value).toFixed(2);if(performance.now()-(input.lastSent||0)>60){input.lastSent=performance.now();send({zones:{[n]:{[input.dataset.field]:Number(input.value)}}})}}});input.addEventListener('change',()=>send({zones:{[n]:{[input.dataset.field]:Number(input.value)}}}))}card.querySelector('.isolate').addEventListener('click',()=>solo(n));$('#zones').append(card);cards[n]=card;const voice=document.createElement('div');voice.className='voice';voice.id=`voice-${n}`;voice.style.setProperty('--color',data.colors[n-1]);voice.innerHTML=`<b>F${n}</b><span>${data.labels[n-1]}</span><span class="value">—</span>`;$('#spectrum').append(voice)}built=true}
function highlight(){for(let n=1;n<=6;n++)cards[n].classList.toggle('selected',n===selected)}
function reflect(settings){for(const key of ['core_falloff','master','snap','trail_ms','f1','phase_depth','pluck_enabled','attack_ms','tail_ms','impulse_threshold']){if(document.activeElement!==$(`#${key}`))$(`#${key}`).value=settings[key];$(`#out-${key}`).textContent=key==='trail_ms'?`${settings[key]} ms`:Number(settings[key]).toFixed(2)}for(let n=1;n<=6;n++){const z=settings.zones[n];for(const [field,value] of Object.entries(z)){const input=cards[n].querySelector(`[data-field="${field}"]`);if(document.activeElement!==input)input.value=value;const out=cards[n].querySelector(`[data-value="${field}"]`);if(out)out.textContent=Number(value).toFixed(2)}const m=z.sensitivity/(1+settings.core_falloff*z.distance);cards[n].querySelector('.effective').textContent=m?`Respuesta ×${m.toFixed(2)} · rango efectivo ${(z.speed_range/m).toFixed(2)} T/s · ${(z.accel_range/m).toFixed(1)} T/s²`:'Silenciado';}$('#mute').textContent=settings.master===0?'Restaurar sonido':'Silenciar'}
let writeQueue=Promise.resolve();
function send(patch){pending=true;lastError='';const mine=++generation;$('#saved').textContent='Aplicando…';writeQueue=writeQueue.catch(()=>{}).then(async()=>{try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok)throw Error(d.error);if(mine===generation){$('#saved').textContent='Guardado · aplicando al cuerpo';revision=-1}}catch(e){lastError=e.message;$('#saved').textContent=e.message}finally{if(mine===generation)pending=false}});return writeQueue}
async function solo(n){if(!payload)return;if(soloRestore){await send({zones:soloRestore});soloRestore=null;Object.values(cards).forEach(c=>c.querySelector('.isolate').textContent='Solo');return}soloRestore=structuredClone(payload.settings.zones);const zones={};for(let i=1;i<=6;i++)zones[i]={sensitivity:i===n?soloRestore[i].sensitivity:0};await send({zones});cards[n].querySelector('.isolate').textContent='Todos'}
for(const input of document.querySelectorAll('[data-global]')){input.addEventListener('input',()=>{$(`#out-${input.id}`).textContent=input.id==='trail_ms'?`${input.value} ms`:Number(input.value).toFixed(2);if(performance.now()-(input.lastSent||0)>60){input.lastSent=performance.now();send({[input.id]:Number(input.value)})}});input.addEventListener('change',()=>send({[input.id]:Number(input.value)}))}
$('#mute').addEventListener('click',()=>{if(!payload)return;const current=payload.settings.master;if(current>0)muteRestore=current;send({master:current>0?0:muteRestore})});
$('#reset').addEventListener('click',()=>{soloRestore=null;Object.values(cards).forEach(c=>c.querySelector('.isolate').textContent='Solo');send({pluck_enabled:1,attack_ms:80,tail_ms:700,impulse_threshold:.15,core_falloff:.75,snap:0,master:1,trail_ms:320,f1:40.4,phase_depth:45,zones:Object.fromEntries([0,1,1,2,2,3].map((d,i)=>[i+1,{sensitivity:1,distance:d,speed_range:.6,accel_range:6}]))})});
async function poll(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();const data=await r.json();lastSuccess=performance.now();payload=data;if(!built)build(data);if(!pending&&revision!==data.revision){reflect(data.settings);revision=data.revision}if(!pending&&!lastError&&data.applied_revision===data.revision)$('#saved').textContent='Guardado · aplicado';const s=data.state,key=`${s.stream_id}:${s.slot_id}`;if(history.length&&history[history.length-1].key!==key){history=[];lastCapture=null}if(s.captured_at_us!==lastCapture&&s.skeleton?.length){lastCapture=s.captured_at_us;history.push({key,t:performance.now(),skeleton:s.skeleton});history=history.slice(-24)}const active=s.zones.filter(z=>z.active).length;$('#voice-count').textContent=`${active} ${active===1?'voz':'voces'}`;$('#status').textContent=s.slot_id===null?'Sin persona activa':'Tracking conectado';$('#status-dot').classList.toggle('live',s.slot_id!==null);$('#performer').textContent=s.slot_id===null?'Esperando tracking':`Persona · slot ${s.slot_id}`;for(let n=1;n<=6;n++){const z=s.zones.find(z=>z.n===n),c=cards[n];c.querySelector('.freq').textContent=z?.active?`${z.freq.toFixed(1)} Hz`:'Silencio';c.querySelector('.meter div').style.width=`${Math.min(100,(z?.gain||0)/.45*100)}%`;c.querySelector('.speed').textContent=`v ${(z?.speed||0).toFixed(2)} T/s`;c.querySelector('.accel').textContent=`a ${(z?.acceleration||0).toFixed(1)} T/s²`;c.querySelector('.phase').textContent=`φ ${(z?.phase_deg||0).toFixed(0)}°`;c.querySelector('.observed').textContent=z?.samples?`Observado p95: v ${z.speed_p95.toFixed(2)} · a ${z.acceleration_p95.toFixed(1)} (${z.samples} muestras)`:'Movete para medir tus rangos';const v=$(`#voice-${n}`);v.classList.toggle('sounding',!!z?.active);v.querySelector('.value').textContent=z?.active?`${z.freq.toFixed(1)} Hz`:'—'}}catch{if(performance.now()-lastSuccess>1000){$('#status').textContent='Instrumento desconectado';$('#status-dot').classList.remove('live')}}finally{setTimeout(poll,50)}}
function draw(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=box.width,h=box.height;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const state=payload?.state;const live=performance.now()-lastSuccess<1000&&state?.skeleton?.length;const scale=Math.min(h*.9,w/(16/9)),ox=(w-scale*16/9)/2,oy=(h-scale)/2;const point=p=>[ox+scale*(16/9-p.x),oy+scale*p.y];function skeleton(points,alpha){ctx.globalAlpha=alpha;ctx.strokeStyle='#90b0b4';ctx.lineWidth=1.7;ctx.beginPath();for(const [a,b] of edges){if(points[a]?.observed&&points[b]?.observed){ctx.moveTo(...point(points[a]));ctx.lineTo(...point(points[b]))}}ctx.stroke();ctx.globalAlpha=1}const now=performance.now(),trail=payload?.settings.trail_ms||0;history=history.filter(x=>now-x.t<Math.max(trail,50));if(live){if(trail)for(const sample of history.slice(0,-1).filter((_,i)=>i%2===0))skeleton(sample.skeleton,.12*(1-(now-sample.t)/trail));// Connect successive measured positions of each joint; never bridge missing observations.
for(const z of state.zones){for(const joint of z.points||[]){let previous=null;for(const sample of history){const p=sample.skeleton[joint.index];if(!p?.observed){previous=null;continue}if(previous&&trail){const fade=Math.max(0,1-(now-sample.t)/trail);ctx.strokeStyle=z.color;ctx.globalAlpha=.75*fade;ctx.lineWidth=1+3*fade;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(...point(previous));ctx.lineTo(...point(p));ctx.stroke()}previous=p}}}ctx.globalAlpha=1;skeleton(state.skeleton,.35);for(const z of state.zones){for(const p of z.points||[]){if(!p.observed)continue;const [x,y]=point(p),energy=z.active?Math.min(1,z.gain/.45)*Math.min(1,p.speed/Math.max(z.speed,.0001)):0;ctx.strokeStyle=z.color;ctx.fillStyle=z.color;ctx.globalAlpha=.35+.65*energy;const radius=5+9*Math.sqrt(energy);if(energy>0){const g=ctx.createRadialGradient(x,y,2,x,y,radius*3);g.addColorStop(0,z.color+'60');g.addColorStop(1,z.color+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,radius*3,0,2*Math.PI);ctx.fill();ctx.fillStyle=z.color}ctx.beginPath();ctx.arc(x,y,radius,0,2*Math.PI);energy>0?ctx.fill():ctx.stroke();ctx.globalAlpha=1;ctx.font='11px system-ui';ctx.fillText(`F${z.n}`,x+radius+10,y+3)}}}else{ctx.textAlign='center';ctx.fillStyle='#819b9f';ctx.font='16px system-ui';ctx.fillText('Tu movimiento aparece acá',w/2,h/2);ctx.font='12px system-ui';ctx.fillText('Iniciá HarMoCAP y ubicá el cuerpo frente a la cámara',w/2,h/2+26);ctx.textAlign='left'}requestAnimationFrame(draw)}
poll();draw();
