import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function ActivationPanel({api,run}:Data){
 const [settings,setSettings]=useState<Data|null>(null),[arrays,setArrays]=useState<Data>({}),[text,setText]=useState(''),[jobs,setJobs]=useState<Data[]>([]),[result,setResult]=useState<Data|null>(null),[condition,setCondition]=useState('rational'),[sample,setSample]=useState(0),[traceMedium,setTraceMedium]=useState('base'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;void api('research/r06/configuration',{}).then((v:Data)=>{if(live)setSettings(v.settings);}).catch((e:any)=>{if(live)setError(String(e));});const poll=async()=>{try{const value=await api('research/r06');if(live)setJobs(value);}catch(e){if(live)setError(String(e));}};void poll();const timer=setInterval(poll,1000);return()=>{live=false;clearInterval(timer);};},[api]);
 const config=()=>{if(!settings)throw Error('Configuración R06 todavía no cargada');const value=structuredClone(settings);for(const [key,text] of Object.entries(arrays)){if(key==='medium_controls')value[key]=JSON.parse(text as string);else value.medium[key]=JSON.parse(text as string);}return {schema_version:1,settings:value};};
 const edit=(key:string,value:any)=>setSettings({...settings,[key]:value});
 const active=busy || jobs.some(j=>j.worker_active || ['queued','running'].includes(j.status));
 const traceConditions=traceMedium==='base'?result?.conditions:result?.medium_controls?.[+traceMedium]?.conditions;
 const rows=traceConditions?.[condition]?.trace || [],row=rows[sample];
 return <section><h2>R06 · Banco de activación</h2><p>Cuatro calendarios sobre el mismo medio, cero inicial e igual cantidad/norma de impulsos. Las diferencias de distribución temporal y del medio no prueban privilegio de phi, eficacia corporal ni HIT. No modifica el instrumento live.</p>
 {error && <p role="alert">{error}</p>}
 {settings && <><fieldset><legend>Calendario y cálculo R06</legend>{Object.entries(settings).filter(([k])=>k!=='medium').map(([key,value])=><label key={key}>{key} R06{typeof value==='number'?<input type="number" step={['event_count','seed','block_size','trace_stride'].includes(key)?1:'any'} value={value} onChange={e=>edit(key,+e.target.value)}/>:<textarea aria-label={`${key} R06`} value={arrays[key] ?? JSON.stringify(value)} onChange={e=>setArrays({...arrays,[key]:e.target.value})}/>}</label>)}</fieldset>
 <fieldset><legend>Medio R06</legend>{Object.entries(settings.medium).map(([key,value])=><label key={key}>medium.{key} R06{typeof value==='number'?<input type="number" step={key==='sample_rate'?1:'any'} value={value} onChange={e=>edit('medium',{...settings.medium,[key]:+e.target.value})}/>:key==='topology'?<select aria-label={`medium.${key} R06`} value={value as string} onChange={e=>edit('medium',{...settings.medium,[key]:e.target.value})}>{['isolated','chain','ring','complete','custom'].map(v=><option key={v}>{v}</option>)}</select>:<textarea aria-label={`medium.${key} R06`} value={arrays[key] ?? JSON.stringify(value)} onChange={e=>setArrays({...arrays,[key]:e.target.value})}/>}</label>)}</fieldset>
 <label><input type="checkbox" checked={!!settings.medium_controls} onChange={e=>{const next={...settings};if(e.target.checked)next.medium_controls=[structuredClone(settings.medium)];else delete next.medium_controls;setSettings(next);setArrays(Object.fromEntries(Object.entries(arrays).filter(([k])=>k!=='medium_controls')));}}/>Comparar medios R06</label>
 <p>Comparar medios crea una copia explícita del medio actual, editable en medium_controls como lista JSON de hasta cuatro medios. Mantener f1/ratios/sample rate; cambiar damping, coupling o grafo. Mismos eventos/dosis, diferencias control menos base; no ranking de eficacia. La copia no sigue cambios posteriores del medio base.</p>
 <p>Ratios/damping: 6–32 voces y una entrada por voz. Adjacency sólo custom: matriz simétrica 0–1, diagonal cero. Calendarios digitales cuantizados; colisiones se rechazan. Trace decimado ≤14400 puntos por condición; métricas usan todas las muestras. Semilla sólo cambia random.</p>
 <button disabled={active} onClick={()=>run(async()=>{setBusy(true);try{const validated=await api('research/r06/configuration',config());await api('research/r06',validated.settings);setJobs(await api('research/r06'));}finally{setBusy(false);}})}>Correr banco R06</button>
 <button onClick={()=>run(async()=>setText(JSON.stringify(await api('research/r06/configuration',config()),null,2)))}>Exportar configuración R06</button>
 <textarea aria-label="Configuración R06 JSON" value={text} onChange={e=>setText(e.target.value)}/>
 <button onClick={()=>run(async()=>{const value=await api('research/r06/configuration',JSON.parse(text));setSettings(value.settings);setArrays({});})}>Importar configuración R06</button><p>Preset portable sin corrida, fuente, persona ni calibración. Importar no ejecuta.</p></>}
 {jobs.map(j=><div key={j.id}><p>{j.id} · {j.status} · {j.error_type || j.error || ''}</p>{['queued','running'].includes(j.status) && <button onClick={()=>run(async()=>{await api(`research/r06/${j.id}/cancel`,{});setJobs(await api('research/r06'));})}>Cancelar R06 {j.id}</button>}{j.status==='complete' && <><button onClick={()=>run(async()=>{const report=await api(`research/r06/${j.id}/artifacts/result.json`);setResult(report);setCondition('rational');setTraceMedium('base');setSample(0);})}>Ver resultado R06 {j.id}</button>{['request.json','result.json','manifest.json'].map(name=><a key={name} href={`/api/research/r06/${j.id}/artifacts/${name}`} download>{name} </a>)}</>}</div>)}
 {result && <><table aria-label="Comparación R06"><thead><tr><th>Calendario</th><th>Norma entrada²</th><th>RMS mezcla</th><th>Pico mezcla</th><th>Integral norma estado</th><th>RMS cola</th></tr></thead><tbody>{Object.entries(result.conditions).map(([name,c]:[string,any])=><tr key={name}><td>{name}</td><td>{c.input_squared_norm}</td><td>{c.metrics.rms}</td><td>{c.metrics.peak_abs}</td><td>{c.metrics.state_norm_time_integral}</td><td>{c.metrics.tail_rms ?? 'sin cola'}</td></tr>)}</tbody></table>
 {result.medium_controls && <table aria-label="Contraste de medios R06"><thead><tr><th>Medio</th><th>Calendario</th><th>RMS</th><th>Δ RMS vs base</th><th>Δ norma final²</th><th>Δ RMS cola</th></tr></thead><tbody>{result.medium_controls.flatMap((v:Data)=>Object.entries(v.conditions).map(([name,c]:[string,any])=><tr key={`${v.index}.${name}`}><td>{v.index+1}</td><td>{name}</td><td>{c.metrics.rms}</td><td>{v.metric_difference_vs_base[name].rms}</td><td>{v.metric_difference_vs_base[name].final_state_norm_squared}</td><td>{v.metric_difference_vs_base[name].tail_rms ?? 'sin cola'}</td></tr>))}</tbody></table>}
 <label>Medio de traza R06<select aria-label="Medio de traza R06" value={traceMedium} onChange={e=>{setTraceMedium(e.target.value);setSample(0);}}><option value="base">Base</option>{(result.medium_controls || []).map((v:Data)=><option key={v.index} value={v.index}>Control {v.index+1}</option>)}</select></label>
 <label>Calendario de traza R06<select aria-label="Calendario de traza R06" value={condition} onChange={e=>{setCondition(e.target.value);setSample(0);}}>{Object.keys(result.conditions).map(k=><option key={k}>{k}</option>)}</select></label>
 <label>Muestra de traza R06<input type="range" min={0} max={Math.max(0,rows.length-1)} value={sample} onChange={e=>setSample(+e.target.value)}/></label>
 {row && <p aria-label="Traza R06">t={row.time_s} s · muestra {row.sample_index} · suma {row.sum} · norma² {row.state_norm_squared} · {row.instrument_tail?'cola del instrumento':'ventana de excitación'}</p>}
 <details><summary>Configuración, calendarios y límites congelados R06</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}
 </section>;
}
