import {useEffect,useState} from 'react';
export function ExperienceAnalysisRecords({api,result,beginOpen,paired=false}:{api:any,result:any,beginOpen:()=>((r:any)=>void),paired?:boolean}){
 const resource=paired?'pairs':'analyses',noun=paired?'pares':'análisis',key=paired?'weaver.r10.pairs.pending.v1':'weaver.r10.analysis.pending.v1';
 const [rows,setRows]=useState<any[]>([]),[pending,setPending]=useState<any>(null),[raw,setRaw]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>setRows(await api(`research/r10/${resource}`));
 useEffect(()=>{try{const text=sessionStorage.getItem(key);setRaw(text);if(text){if(text.length>256*1024)throw Error('Pendiente de análisis demasiado grande');const p=JSON.parse(text);if(!Array.isArray(paired?p.pairs:p.response_ids)||!(paired?p.pairs:p.response_ids).length||!Array.isArray(p.expected_sources)||(paired?p.pairs:p.response_ids).length>(paired?128:256))throw Error('Pendiente de análisis inválido');setPending(p);}}catch(e){setError(String(e));}void refresh().catch(e=>setError(String(e)));},[api]);
 const save=async(retry:boolean)=>{setBusy(true);setError('');try{const body=retry?pending:(paired?{pairs:result.input.selection.pairs,expected_sources:result.input.analysis.sources.map((s:any)=>({id:s.id,manifest_sha256:s.manifest_sha256}))}:{response_ids:result.selection.response_ids,expected_sources:result.sources.map((s:any)=>({id:s.id,manifest_sha256:s.manifest_sha256}))});if(!body)throw Error('Sin análisis pendiente');const text=JSON.stringify(body);sessionStorage.setItem(key,text);setPending(body);setRaw(text);await api(`research/r10/${resource}`,body);sessionStorage.removeItem(key);setPending(null);setRaw(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const open=async(id:string)=>{const complete=beginOpen();setBusy(true);setError('');try{const r=await api(`research/r10/${resource}/${id}/artifacts/result.json`);complete(r);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const exportPending=()=>{if(raw===null)return;const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=paired?'r10-pending-pairs.json':'r10-pending-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label={paired?"Pares congelados R10":"Análisis congelados R10"}><h3>{paired?"Pares guardados":"Análisis guardados"}</h3><button disabled={busy||!result||raw!==null} onClick={()=>void save(false)}>{paired?"Guardar pares congelados R10":"Guardar análisis congelado R10"}</button>{error&&<p role="alert">{error}</p>}{raw!==null&&<><p>Envío de {noun} pendiente; conserva selección y hashes originales.</p>{pending&&<button disabled={busy} onClick={()=>void save(true)}>Recuperar envío de {noun} R10</button>}<button disabled={busy} onClick={exportPending}>Exportar envío de {noun} pendiente R10</button><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(key);setRaw(null);setPending(null);setError('');}catch(e){setError(String(e));}}}>Descartar envío de {noun} pendiente R10</button></>}<button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>{paired?"Actualizar pares congelados R10":"Actualizar análisis congelados R10"}</button>{rows.map(r=><div key={r.id}>{r.id} · {r.read_verification}<button disabled={busy} onClick={()=>void open(r.id)}>{paired?"Abrir pares congelados R10":"Abrir análisis congelado R10"}</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r10/${resource}/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}</section>;
}
