import {ExperienceTransportsPanel} from './ExperienceTransportsPanel';
import {ExperiencePlayer} from './ExperiencePlayer';
import {ExperienceSourcesPanel} from './ExperienceSourcesPanel';
import {useEffect,useState} from 'react';
export function ExperiencePanel({api}:{api:any}){
 const receiptKey='weaver.r10.protocol.pending.v1';
 const [opened,setOpened]=useState('');
 const [runs,setRuns]=useState<any[]>([]),[pending,setPending]=useState<any>(null);
 useEffect(()=>{void api('research/r10/protocols').then(setRuns).catch(()=>{});try{const raw=sessionStorage.getItem(receiptKey);if(raw){if(raw.length>4*1024*1024)throw Error('oversize');const p=JSON.parse(raw);if(!p.protocol||!/^[a-f0-9]{32}$/.test(p.idempotency_key))throw Error('invalid');setPending(p);}}catch{sessionStorage.removeItem(receiptKey);}},[api]);
 const [presets,setPresets]=useState<any[]>([]),[name,setName]=useState('Experiencia audiovisual');
 useEffect(()=>{let live=true;void api('research/r10/presets').then((r:any[])=>{if(live)setPresets(r);}).catch(()=>{});return()=>{live=false;};},[api]);
 const [text,setText]=useState(JSON.stringify({config:{conditions:['video_only','sound_only','audiovisual'],repetitions:1,preview_gain:1,desynchronization_s:.5,scale_min:0,scale_max:100},participant_slot:'',role:'observer',order_index:0,stimuli:[]},null,2));
 const [response,setResponse]=useState('{"trial_id":"trial-0001","ratings":{},"note":""}'),[result,setResult]=useState<any>(null),[validated,setValidated]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const saveProtocol=async()=>{const body=pending||{protocol:result.request,idempotency_key:crypto.randomUUID().replaceAll('-','')};sessionStorage.setItem(receiptKey,JSON.stringify(body));setPending(body);try{await api('research/r10/protocols',body);}catch(e){const status=(e as any)?.status;if(status>=400&&status<500){sessionStorage.removeItem(receiptKey);setPending(null);}throw e;}sessionStorage.removeItem(receiptKey);setPending(null);setRuns(await api('research/r10/protocols'));};
 const openProtocol=async(id:string)=>{setResult(null);setValidated(null);setOpened('');const r=await api(`research/r10/protocols/${id}/artifacts/result.json`);setOpened(id);setText(JSON.stringify(r.request,null,2));setResult(r);setValidated(null);setResponse(JSON.stringify({trial_id:r.trials[0].trial_id,ratings:Object.fromEntries(r.request.config.items.map((i:any)=>[i.id,null])),note:''},null,2));};
 const download=(value:any,name:string)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Protocolo de experiencia R10"><ExperienceTransportsPanel api={api}/><h2>R10 · Experiencia declarada</h2><p>Planificar condiciones y preguntas para practicantes u observadores. Vista previa no reproduce estímulos, registra exposición ni guarda respuestas. Referencias, niveles y offsets son declaraciones; requieren verificación física.</p>
 <label>Protocolo JSON R10<textarea disabled={busy} rows={14} value={text} onChange={e=>{setText(e.target.value);setResult(null);setValidated(null);}}/></label>
 <button disabled={busy} onClick={()=>void act(async()=>{setResult(null);setValidated(null);const r=await api('research/r10/preview',JSON.parse(text));setResult(r);setResponse(JSON.stringify({trial_id:r.trials[0].trial_id,ratings:Object.fromEntries(r.request.config.items.map((i:any)=>[i.id,null])),note:''},null,2));})}>Preparar protocolo R10</button>
 <label>Nombre preset R10<input disabled={busy} value={name} onChange={e=>setName(e.target.value)}/></label>
 <button disabled={busy||!result} onClick={()=>void act(async()=>{await api('research/r10/presets',{name,config:result.request.config});setPresets(await api('research/r10/presets'));})}>Guardar configuración R10</button>
 <label>Importar configuración R10<input disabled={busy} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{if(f.size>65536)throw Error('Preset supera 64 KiB');const value=JSON.parse(await f.text());await api('research/r10/presets',value.config?value:{name:f.name.slice(0,80),config:value});setPresets(await api('research/r10/presets'));});e.target.value='';}}/></label>
 <p>Aplicar un preset conserva participante, rol, orden y estímulos; limpia la vista previa y no ejecuta el protocolo.</p>
 {presets.map(p=><div key={p.id}>{p.name}<button disabled={busy} onClick={()=>void act(async()=>{const protocol=JSON.parse(text);setText(JSON.stringify({...protocol,config:p.config},null,2));setResult(null);setValidated(null);})}>Aplicar configuración R10</button><a href={`/api/research/r10/presets/${p.id}`} download>Exportar preset R10</a></div>)}
 <button disabled={busy||!!pending||!result} onClick={()=>void act(saveProtocol)}>Guardar protocolo congelado R10</button>
 {pending&&<p role="status">Protocolo pendiente de confirmar. <button disabled={busy} onClick={()=>void act(saveProtocol)}>Recuperar protocolo R10</button></p>}
 {runs.map(r=><div key={r.id}>{r.id} · {r.read_verification==='recomputed'?'Calendario recalculado':'Histórico: sólo integridad'}<button disabled={busy} onClick={()=>void act(async()=>openProtocol(r.id))}>Abrir protocolo congelado R10</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r10/protocols/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 {error&&<p role="alert">{error}</p>}{result&&<><p>{result.trials.length} ensayos planificados · ciclo de órdenes: {result.order_cycle_size}. Balance sólo si se completa el ciclo; esto no prueba participación.</p><table aria-label="Orden de ensayos R10"><thead><tr><th>Ensayo</th><th>Estímulo</th><th>Condición</th><th>Offset nominal</th></tr></thead><tbody>{result.trials.map((t:any)=><tr key={t.trial_id}><td>{t.trial_id}</td><td>{t.stimulus_id}</td><td>{t.condition}</td><td>{t.nominal_audio_offset_s}</td></tr>)}</tbody></table><button onClick={()=>download(result,'r10-protocol-preview.json')}>Exportar protocolo R10</button><button onClick={()=>download(result.request.config,'r10-configuration.json')}>Exportar configuración portable R10</button><details><summary>Contrato y límites R10</summary><pre>{JSON.stringify(result,null,2)}</pre></details>
 <label>Respuesta JSON R10<textarea disabled={busy} rows={8} value={response} onChange={e=>{setResponse(e.target.value);setValidated(null);}}/></label><p>Preguntas independientes; null significa sin respuesta. No inferimos placer, belleza o agencia desde fisiología.</p><button disabled={busy} onClick={()=>void act(async()=>{setValidated(null);setValidated(await api('research/r10/validate-response',{protocol:result.request,response:JSON.parse(response)}));})}>Validar respuesta declarada R10</button>{validated&&<><p>Respuesta declarada válida · rol {validated.role}. No acredita exposición ni participación verificada.</p><pre>{JSON.stringify(validated,null,2)}</pre><button onClick={()=>download(validated,'r10-declared-response.json')}>Exportar respuesta declarada R10</button></>}</>}
 {opened&&result?.sources&&<ExperiencePlayer key={opened+JSON.stringify(result.request)} api={api} protocolId={opened} trials={result.trials}/>}
 <ExperienceSourcesPanel api={api} onSaved={async()=>setRuns(await api('research/r10/protocols'))}/>
 </section>;
}
