import {useEffect,useRef,useState} from 'react';
export function ExperiencePairDesignPanel({api,onPairs}:{api:any,onPairs:(pairs:any[])=>void}){
 const [rows,setRows]=useState<any[]>([]),[presets,setPresets]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[text,setText]=useState(JSON.stringify({contrasts:[{reference_condition:'video_only',target_condition:'audiovisual'}]},null,2)),[name,setName]=useState('Contrastes por condición'),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const refresh=async()=>{const r=await api('research/r10/responses');setRows(r);setSelected(s=>s.filter(id=>r.some((row:any)=>row.id===id)));setPresets(await api('research/r10/pair-design-presets'));};
 useEffect(()=>{void act(refresh);return()=>{generation.current++;};},[api]);
 const edit=(value:string)=>{generation.current++;setText(value);setPreview(null);};
 const prepare=async()=>{const token=++generation.current;setPreview(null);const r=await api('research/r10/pair-design-preview',{response_ids:selected,config:JSON.parse(text)});if(token===generation.current)setPreview(r);};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema_version:1,name,config:JSON.parse(text)},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r10-pair-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Diseños portables de contrastes R10"><h3>Diseños portables</h3><p>Guarda condiciones y dirección, sin personas, respuestas, fuentes o calibración. Aplicar configura pares; no calcula ni reproduce.</p><label>Diseño JSON R10<textarea rows={7} disabled={busy} value={text} onChange={e=>edit(e.target.value)}/></label><label>Nombre de diseño R10<input value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><button disabled={busy} onClick={()=>void act(async()=>{await api('research/r10/pair-design-presets',{name,config:JSON.parse(text)});setPresets(await api('research/r10/pair-design-presets'));})}>Guardar diseño portable R10</button><button disabled={busy} onClick={()=>void act(async()=>download())}>Exportar diseño portable R10</button><label>Importar diseño portable R10<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void act(async()=>{if(file.size>65536)throw Error('Diseño excede 64 KiB');const value=JSON.parse(await file.text());if(value.config){if(Object.keys(value).some(k=>!['schema_version','name','config'].includes(k))||value.schema_version!==1)throw Error('Wrapper portable inválido');edit(JSON.stringify(value.config,null,2));setName(value.name);}else edit(JSON.stringify(value,null,2));});}}/></label>{presets.map(p=><div key={p.id}>{p.name}<button disabled={busy} onClick={()=>{edit(JSON.stringify(p.config,null,2));setName(p.name);}}>Aplicar diseño guardado R10</button><a href={`/api/research/r10/pair-design-presets/${p.id}`} download>Exportar preset de contraste R10</a></div>)}<button disabled={busy} onClick={()=>void act(async()=>{generation.current++;setPreview(null);await refresh();})}>Actualizar fuentes de diseño R10</button>{rows.map(r=><label key={r.id}><input type="checkbox" disabled={busy} aria-label={`Respuesta para diseño R10 ${r.id}`} checked={selected.includes(r.id)} onChange={e=>{generation.current++;setPreview(null);setSelected(s=>e.target.checked?[...s,r.id]:s.filter(id=>id!==r.id));}}/>{r.id}</label>)}<button disabled={busy||!selected.length} onClick={()=>void act(prepare)}>Preparar pares desde diseño R10</button>{error&&<p role="alert">{error}</p>}{preview&&<><p>{preview.pairs.length} pares disponibles · {preview.missing.length} contrastes sin soporte seleccionado.</p><button disabled={busy||!preview.pairs.length} onClick={()=>onPairs(preview.pairs)}>Usar pares del diseño R10</button><details><summary>Soporte y fuentes del diseño R10</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></>}</section>;
}
