import {useEffect,useRef,useState} from 'react';
export function ExperienceAnalysisPanel({api}:{api:any}){
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 const refresh=async()=>{setBusy(true);setError('');const token=++generation.current;setResult(null);try{const r=await api('research/r10/responses');if(token!==generation.current)return;setRows(r);setSelected(s=>s.filter(id=>r.some((v:any)=>v.id===id)));}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[api]);
 const analyze=async()=>{setBusy(true);setError('');setResult(null);const token=++generation.current;try{const r=await api('research/r10/analysis-preview',{response_ids:selected});if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const download=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r10-descriptive-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Análisis descriptivo R10"><h3>Análisis descriptivo de respuestas</h3><p>Elegí registros explícitamente. Una corrección por ensayo; preguntas/escalas y roles distintos se separan. Los conteos son registros, no participantes independientes ni exposición verificada.</p><button disabled={busy} onClick={()=>void refresh()}>Actualizar selección de respuestas R10</button>{rows.map(r=><label key={r.id}><input type="checkbox" disabled={busy} aria-label={`Seleccionar respuesta R10 ${r.id}`} checked={selected.includes(r.id)} onChange={e=>{generation.current++;setResult(null);setSelected(s=>e.target.checked?[...s,r.id]:s.filter(id=>id!==r.id));}}/>{r.id} · {r.read_verification}</label>)}<button disabled={busy||!selected.length} onClick={()=>void analyze()}>Analizar respuestas seleccionadas R10</button>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.sources.length} registros seleccionados · {result.groups.length} grupos compatibles. Vista previa sin manifest de publicación.</p>{result.groups.map((g:any)=><div key={g.questionnaire_sha256+g.role+g.condition}><p>{g.role} · {g.condition} · escala {g.questionnaire.scale_min}–{g.questionnaire.scale_max}</p><table aria-label={`Resumen R10 ${g.role} ${g.condition}`}><thead><tr><th>Pregunta</th><th>Respondidos</th><th>Sin respuesta</th><th>Mediana</th><th>Mínimo</th><th>Máximo</th></tr></thead><tbody>{g.items.map((i:any)=><tr key={i.id}><td>{g.questionnaire.items.find((q:any)=>q.id===i.id)?.question}</td><td>{i.answered_count}</td><td>{i.unanswered_count}</td><td>{i.median??'—'}</td><td>{i.min??'—'}</td><td>{i.max??'—'}</td></tr>)}</tbody></table></div>)}<button onClick={download}>Exportar análisis descriptivo R10</button><details><summary>Fuentes y límites del análisis R10</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</section>;
}
