import {useEffect,useState} from 'react';
const key='weaver.r10.analysis.pending.v1';
export function ExperienceAnalysisRecords({api,result,onOpen}:{api:any,result:any,onOpen:(r:any)=>void}){
 const [rows,setRows]=useState<any[]>([]),[pending,setPending]=useState<any>(null),[raw,setRaw]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>setRows(await api('research/r10/analyses'));
 useEffect(()=>{try{const text=sessionStorage.getItem(key);setRaw(text);if(text){if(text.length>256*1024)throw Error('Pendiente de análisis demasiado grande');const p=JSON.parse(text);if(!Array.isArray(p.response_ids)||!p.response_ids.length||!Array.isArray(p.expected_sources)||p.response_ids.length>256)throw Error('Pendiente de análisis inválido');setPending(p);}}catch(e){setError(String(e));}void refresh().catch(e=>setError(String(e)));},[api]);
 const save=async(retry:boolean)=>{setBusy(true);setError('');try{const body=retry?pending:{response_ids:result.selection.response_ids,expected_sources:result.sources.map((s:any)=>({id:s.id,manifest_sha256:s.manifest_sha256}))};if(!body)throw Error('Sin análisis pendiente');const text=JSON.stringify(body);sessionStorage.setItem(key,text);setPending(body);setRaw(text);await api('research/r10/analyses',body);sessionStorage.removeItem(key);setPending(null);setRaw(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const open=async(id:string)=>{setBusy(true);setError('');try{const r=await api(`research/r10/analyses/${id}/artifacts/result.json`);onOpen(r);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const exportPending=()=>{if(raw===null)return;const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r10-pending-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Análisis congelados R10"><h3>Análisis guardados</h3><button disabled={busy||!result||raw!==null} onClick={()=>void save(false)}>Guardar análisis congelado R10</button>{error&&<p role="alert">{error}</p>}{raw!==null&&<><p>Envío de análisis pendiente; conserva selección y hashes originales.</p>{pending&&<button disabled={busy} onClick={()=>void save(true)}>Recuperar envío de análisis R10</button>}<button disabled={busy} onClick={exportPending}>Exportar envío de análisis pendiente R10</button><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(key);setRaw(null);setPending(null);setError('');}catch(e){setError(String(e));}}}>Descartar envío de análisis pendiente R10</button></>}<button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>Actualizar análisis congelados R10</button>{rows.map(r=><div key={r.id}>{r.id} · {r.read_verification}<button disabled={busy} onClick={()=>void open(r.id)}>Abrir análisis congelado R10</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r10/analyses/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}</section>;
}
