import {ExperienceAnalysisRecords} from './ExperienceAnalysisRecords';
import {useEffect,useRef,useState} from 'react';
export function ExperiencePairsPanel({api}:{api:any}){
 const [rows,setRows]=useState<any[]>([]),[reference,setReference]=useState(''),[target,setTarget]=useState(''),[text,setText]=useState('{"pairs":[]}'),[result,setResult]=useState<any>(null),[opened,setOpened]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 const refresh=async()=>{setBusy(true);setError('');try{setRows(await api('research/r10/responses'));}catch(e){setError(String(e));}finally{setBusy(false);}};
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[api]);
 const change=(value:string)=>{generation.current++;setText(value);setResult(null);setOpened(false);};
 const add=()=>{try{const selection=JSON.parse(text);change(JSON.stringify({pairs:[...selection.pairs,{reference_id:reference,target_id:target}]},null,2));setError('');}catch(e){setError(String(e));}};
 const calculate=async()=>{setBusy(true);setError('');setResult(null);setOpened(false);const token=++generation.current;try{const r=await api('research/r10/pairs-preview',JSON.parse(text));if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const download=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r10-paired-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Contrastes pareados R10"><h3>Comparar pares explícitos</h3><p>Destino menos referencia. Mismo protocolo, estímulo y repetición; condiciones distintas. No verifica identidad ni exposición. Pares pueden compartir respuestas: no son observaciones independientes.</p><button disabled={busy} onClick={()=>void refresh()}>Actualizar respuestas para pares R10</button><label>Referencia del par R10<select disabled={busy} value={reference} onChange={e=>setReference(e.target.value)}><option value="">Elegir</option>{rows.map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label><label>Destino del par R10<select disabled={busy} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Elegir</option>{rows.map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label><button disabled={busy||!reference||!target||reference===target} onClick={add}>Agregar par R10</button><label>Pares JSON R10<textarea rows={8} disabled={busy} value={text} onChange={e=>change(e.target.value)}/></label><button disabled={busy} onClick={()=>void calculate()}>Calcular pares R10</button>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.pairs.length} pares declarados. {opened?'Resultado pareado guardado; manifest en el listado.':'Vista previa, sin manifest guardado.'}</p>{result.pairs.map((p:any,index:number)=><div key={index}><p>{p.reference_condition} → {p.target_condition} · {p.stimulus_id} · repetición {p.repetition}</p><table aria-label={`Diferencias del par R10 ${index+1}`}><thead><tr><th>Pregunta</th><th>Referencia</th><th>Destino</th><th>Diferencia</th><th>Soporte</th></tr></thead><tbody>{p.items.map((i:any)=><tr key={i.id}><td>{i.id}</td><td>{i.reference??'—'}</td><td>{i.target??'—'}</td><td>{i.target_minus_reference??'—'}</td><td>{i.support}</td></tr>)}</tbody></table></div>)}<button onClick={download}>Exportar pares R10</button><details><summary>Fuentes y límites de pares R10</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}<ExperienceAnalysisRecords paired api={api} result={result} beginOpen={()=>{const token=++generation.current;setResult(null);setOpened(false);return r=>{if(token!==generation.current)return;setResult(r);setOpened(true);setText(JSON.stringify(r.input.selection,null,2));};}}/></section>;
}
