import {useEffect,useState} from 'react';
const key='weaver.r10.response.pending.v1';
export function ExperienceResponsesPanel({api,protocolId,manifestHash,response}:{api:any,protocolId:string,manifestHash:string,response:string}){
 const [rows,setRows]=useState<any[]>([]),[pending,setPending]=useState<any>(null),[raw,setRaw]=useState<string|null>(null),[transport,setTransport]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>setRows(await api('research/r10/responses'));
 useEffect(()=>{try{const text=sessionStorage.getItem(key);setRaw(text);if(text){if(text.length>1024*1024)throw Error('Respuesta pendiente demasiado grande');const p=JSON.parse(text);if(!/^[a-f0-9]{32}$/.test(p.protocol_id)||!/^[a-f0-9]{64}$/.test(p.protocol_manifest_sha256)||!p.response)throw Error('Respuesta pendiente inválida');setPending(p);}}catch(e){setError(String(e));}void refresh().catch(e=>setError(String(e)));},[api]);
 const send=async(retry:boolean)=>{setBusy(true);setError('');try{const body=retry?pending:{protocol_id:protocolId,protocol_manifest_sha256:manifestHash,response:JSON.parse(response),transport_id:transport||null};if(!body)throw Error('Sin respuesta pendiente');const text=JSON.stringify(body);sessionStorage.setItem(key,text);setRaw(text);setPending(body);await api('research/r10/responses',body);sessionStorage.removeItem(key);setRaw(null);setPending(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const exportPending=()=>{if(raw===null)return;const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r10-pending-response.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Respuestas guardadas R10"><h3>Guardar respuestas declaradas</h3><p>Usa el JSON de respuesta del protocolo abierto. Transporte opcional: copiá su ID si corresponde al mismo ensayo. No acredita escucha ni identidad; correcciones generan registros nuevos.</p><label>Registro de transporte opcional R10<input value={transport} disabled={busy} onChange={e=>setTransport(e.target.value)}/></label><button disabled={busy||raw!==null||!protocolId||!manifestHash} onClick={()=>void send(false)}>Guardar respuesta R10</button>{error&&<p role="alert">{error}</p>}{raw!==null&&<><p>Respuesta pendiente conservada; recuperar no usa el JSON que estés editando.</p>{pending&&<button disabled={busy} onClick={()=>void send(true)}>Recuperar envío de respuesta R10</button>}<button disabled={busy} onClick={exportPending}>Exportar envío de respuesta pendiente R10</button><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(key);setPending(null);setRaw(null);setError('');}catch(e){setError(String(e));}}}>Descartar envío de respuesta pendiente R10</button><p>Descartar sólo elimina la copia de esta pestaña, no registros aceptados.</p></>}<button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>Actualizar respuestas R10</button>{rows.map(r=><div key={r.id}>{r.id} · {r.read_verification} {['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r10/responses/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}</section>;
}
