import {useEffect,useState} from 'react';
type Data=Record<string,any>;
function download(value:any,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function HeldoutPanel({api}:{api:any}){
 const [text,setText]=useState(''),[jobs,setJobs]=useState<Data[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [comparisonIds,setComparisonIds]=useState<string[]>([]),[comparison,setComparison]=useState<Data|null>(null);
 const [evaluation,setEvaluation]=useState(''),[runIndex,setRunIndex]=useState(0),[report,setReport]=useState<Data|null>(null),[start,setStart]=useState(0),[end,setEnd]=useState(1),[signals,setSignals]=useState<string[]>([]),[role,setRole]=useState('train'),[sequenceId,setSequenceId]=useState('source-1'),[subject,setSubject]=useState('declare-subject-group'),[task,setTask]=useState('declare-task');
 useEffect(()=>{let live=true;const poll=()=>api('research/r13').then((rows:Data[])=>{if(live)setJobs(rows)}).catch((e:any)=>{if(live)setError(String(e))});void poll();const timer=setInterval(poll,1000);return()=>{live=false;clearInterval(timer)}},[api]);
 const action=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work()}catch(e){setError(String(e))}finally{setBusy(false)}};
 let request:Data|null=null;try{request=JSON.parse(text)}catch{}
 const edit=(work:(r:Data)=>void)=>{try{const r=JSON.parse(text);work(r);setText(JSON.stringify(r,null,2));setError('')}catch(e){setError(String(e))}};
 const active=jobs.some(j=>j.status==='running');
 const selected=report?.manifest.runs[runIndex];
 return <section aria-label="Transferencia reservada R13"><h2>R13 · Predicción en fuentes reservadas</h2><p>Congela entrenamiento, normalización, base y predictores. Compara baselines congelados, adaptación y shuffle opcionales sobre los mismos objetivos. Esto no demuestra aprendizaje humano, eficacia, HIT ni beneficio de prótesis. Grupos, tarea y equivalencias deben declararse; no se infiere identidad.</p>
 <button disabled={busy} onClick={()=>void action(async()=>setText(JSON.stringify(await api('research/r13/template'),null,2)))}>Cargar control sintético R13</button>
 <button disabled={busy} onClick={()=>void action(async()=>setText(JSON.stringify(await api('research/r13/template?kind=quadratic'),null,2)))}>Cargar recurrencia cuadrática R13</button>
 <label>Importar experimento R13<input type="file" disabled={busy} accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>16*1024*1024)throw Error('Máximo 16 MiB');setText(JSON.stringify(JSON.parse(await file.text()),null,2))})}}/></label>
 {request && <div><label>Reserva R13<select aria-label="Reserva R13" disabled={busy} value={request.reservation} onChange={e=>edit(r=>r.reservation=e.target.value)}>{['within_take','take','subject','task'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Equivalencia funcional R13<input disabled={busy} value={request.functional_equivalence} onChange={e=>edit(r=>r.functional_equivalence=e.target.value)}/></label>
 <label>Restricciones R13<input disabled={busy} value={request.constraints} onChange={e=>edit(r=>r.constraints=e.target.value)}/></label>
 {([['history_steps','Historia (muestras)',1,8,1],['horizon_steps','Horizonte (muestras)',1,30,1],['components','Componentes del predictor',1,16,1],['ridge','Ridge R13',.000001,100,.01],['max_gap_s','Gap máximo R13 (s)',.001,5,.01],['embargo_s','Embargo temporal R13 (s)',0,60,.1],['shuffle_seed','Semilla shuffle train',0,2147483647,1],['adaptation_prefix_samples','Prefijo de adaptación (0 = sin adaptar)',0,1200,1]] as const).map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" disabled={busy} min={min} max={max} step={step} value={request?.settings?.[key]??''} onChange={e=>edit(r=>r.settings[key]=+e.target.value)}/></label>)}
 <label><input type="checkbox" disabled={busy} checked={request.settings?.shuffle_training_targets??false} onChange={e=>edit(r=>r.settings.shuffle_training_targets=e.target.checked)}/>Control: mezclar objetivos de entrenamiento</label>
 <label><input type="checkbox" disabled={busy} checked={request.settings?.quadratic_control??false} onChange={e=>edit(r=>r.settings.quadratic_control=e.target.checked)}/>Control no lineal: ridge cuadrático R13</label>
 {request.settings?.quadratic_control&&<p>Incluye cuadrados y productos de la historia normalizada sólo con entrenamiento. Máximo 24 coordenadas de historia (features × muestras), 324 regresores. Más capacidad no garantiza mejor predicción; mismo ridge no iguala complejidad.</p>}
 <label>Adaptación R13<select aria-label="Adaptación R13" disabled={busy} value={request.settings?.adaptation_mode??'pooled_prefix'} onChange={e=>edit(r=>r.settings.adaptation_mode=e.target.value)}><option value="pooled_prefix">Train + prefijo</option><option value="prefix_only">Sólo prefijo (modelo específico)</option></select></label>
 <label>Normalización R13<select aria-label="Normalización R13" disabled={busy} value={request.settings?.normalization} onChange={e=>edit(r=>r.settings.normalization=e.target.value)}><option value="center_train">Centrar con entrenamiento</option><option value="standardize_train">Estandarizar con entrenamiento</option></select></label>
 <p>{request.feature_ids?.join(', ')} · unidad {request.unit}. Normalización no se reajusta con objetivos reservados. Prefijo positivo ajusta modelos adicionales con train + prefijo o sólo prefijo, conserva los originales y puntúa todos sólo en orígenes posteriores; no es transferencia sin adaptación.</p>
 {(request.sequences||[]).map((s:Data,i:number)=><fieldset key={i}><legend>{s.id} · {s.provider} · {s.observations?.length} observaciones</legend><label>Rol {s.id}<select aria-label={`Rol ${s.id}`} disabled={busy} value={s.role} onChange={e=>edit(r=>r.sequences[i].role=e.target.value)}><option>train</option><option>test</option></select></label>{(['subject_group','task_id','recording_id'] as const).map(k=><label key={k}>{s.id} {k}<input disabled={busy||s.provider==='evaluation_features'&&k==='recording_id'} value={s[k]} onChange={e=>edit(r=>r.sequences[i][k]=e.target.value)}/></label>)}<button disabled={busy} onClick={()=>edit(r=>r.sequences.splice(i,1))}>Quitar secuencia {s.id}</button></fieldset>)}
 <button disabled={busy} onClick={()=>download({schema_version:1,kind:'r13-settings',settings:request?.settings,reservation:request?.reservation},'r13-settings.json')}>Guardar configuración portable R13</button>
 <label>Importar configuración R13<input type="file" disabled={busy} accept="application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>65536)throw Error('Máximo 64 KiB');const config=JSON.parse(await file.text());if(config.schema_version!==1||config.kind!=='r13-settings'||Object.keys(config).some(k=>!['schema_version','kind','settings','reservation'].includes(k)))throw Error('Configuración incompatible');const r=JSON.parse(text);r.settings=config.settings;r.reservation=config.reservation;setText(JSON.stringify(r,null,2))})}}/></label>
 </div>}
 <details><summary>Añadir secuencia desde EVAL verificado</summary><p>Snapshot de features observadas y causales, sin abrir video ni recalcular tracking. Declarar grupo y tarea; mismos IDs ordenados/unidad en todas las secuencias. No cambia calibración. Dos presets del mismo intervalo no son un test reservado.</p><label>Evaluación origen R13<input disabled={busy} value={evaluation} onChange={e=>setEvaluation(e.target.value)}/></label><label>Índice corrida origen R13<input type="number" min={0} disabled={busy} value={runIndex} onChange={e=>{setRunIndex(+e.target.value);setSignals([])}}/></label><button disabled={busy} onClick={()=>void action(async()=>{const r=await api(`evaluations/${evaluation}/report`);setReport(r);const run=r.manifest.runs[runIndex];if(!run)throw Error('Corrida inexistente');const source=r.manifest.request.sources[run.source_index];setStart(source.start_s);setEnd(source.end_s);setSignals([])})}>Cargar catálogo EVAL R13</button>
 {selected&&<><p>Slot congelado: {report!.manifest.request.sources[selected.source_index].person_id}</p>{Object.entries(selected.signals||{}).map(([id,s]:[string,any])=><label key={id}><input type="checkbox" disabled={busy} checked={signals.includes(id)} onChange={e=>setSignals(e.target.checked?[...signals,id]:signals.filter(v=>v!==id))}/>{id} ({s.unit})</label>)}</>}
 {([['ID secuencia R13',sequenceId,setSequenceId],['Grupo sujeto R13',subject,setSubject],['Tarea R13',task,setTask]] as const).map(([label,value,set])=><label key={label}>{label}<input disabled={busy} value={value} onChange={e=>set(e.target.value)}/></label>)}
 <label>Rol nuevo R13<select aria-label="Rol nuevo R13" value={role} disabled={busy} onChange={e=>setRole(e.target.value)}><option>train</option><option>test</option></select></label><label>Inicio origen R13 (s)<input type="number" disabled={busy} value={start} onChange={e=>setStart(+e.target.value)}/></label><label>Fin origen R13 (s)<input type="number" disabled={busy} value={end} onChange={e=>setEnd(+e.target.value)}/></label>
 <button disabled={busy||signals.length<2} onClick={()=>void action(async()=>{const sequence=await api('research/r13/sequence',{id:sequenceId,role,subject_group:subject,task_id:task,selection:{evaluation_id:evaluation,run_index:runIndex,signal_ids:signals,start_s:start,end_s:end,components:Math.min(2,signals.length)}});const r=JSON.parse(text);if(r.sequences.length && (JSON.stringify(r.feature_ids)!==JSON.stringify(signals)||r.unit!==sequence.provenance.unit))throw Error('IDs/unidad distintos: no remapeo silencioso');r.feature_ids=signals;r.unit=sequence.provenance.unit;r.sequences.push(sequence);setText(JSON.stringify(r,null,2))})}>Congelar y añadir secuencia R13</button></details>
 <label>Experimento JSON R13<textarea rows={12} disabled={busy} value={text} onChange={e=>setText(e.target.value)}/></label>
 <button disabled={busy||active||!request} onClick={()=>void action(async()=>{await api('research/r13',JSON.parse(text));setJobs(await api('research/r13'))})}>Correr transferencia R13</button>
 <button disabled={!request} onClick={()=>download(request,'r13-experiment.json')}>Exportar experimento R13</button>
 {error&&<p role="alert">{error}</p>}
 <fieldset><legend>Comparar corridas R13 sobre soporte común</legend><p>Elegí 2–6 corridas con las mismas secuencias congeladas, features y unidades. Sólo pueden variar los parámetros. El orden de selección fija la primera como referencia; se comparan pares idénticos de origen/objetivo, sin rellenar gaps.</p>
 {jobs.filter(j=>j.status==='complete').map(j=><label key={j.id}><input type="checkbox" aria-label={`Comparar R13 ${j.id}`} disabled={busy||(!comparisonIds.includes(j.id)&&comparisonIds.length>=6)} checked={comparisonIds.includes(j.id)} onChange={e=>{setComparison(null);setComparisonIds(e.target.checked?[...comparisonIds,j.id]:comparisonIds.filter(id=>id!==j.id))}}/>{j.id}{comparisonIds.includes(j.id)?` · orden ${comparisonIds.indexOf(j.id)+1}`:''}</label>)}
 <button disabled={busy||comparisonIds.length<2} onClick={()=>void action(async()=>{setComparison(null);setComparison(await api('research/r13/compare',{run_ids:comparisonIds}))})}>Comparar soporte común R13</button>
 {comparison&&<><button onClick={()=>download(comparison,'r13-common-support.json')}>Guardar comparación R13</button>
 {comparison.sequences.map((s:Data)=>{const methods:string[]=Array.from(new Set(s.conditions.flatMap((c:Data)=>Object.keys(c.mean_mse))));return <div key={s.sequence_id}><p>{s.sequence_id}: {s.common_count} pares comunes · {comparison.unit}. {s.common_count===0?'Sin soporte compartido; no hay puntuación.':''}</p><table aria-label={`Soporte común R13 ${s.sequence_id}`}><thead><tr><th>Corrida</th><th>Pares elegibles</th><th>Fuera del común</th>{methods.map(m=><th key={m}>{m} MSE / Δ vs primera</th>)}</tr></thead><tbody>{s.conditions.map((c:Data)=><tr key={c.run_id}><td>{c.run_id}</td><td>{c.eligible_count}</td><td>{c.excluded_from_common}</td>{methods.map(m=><td key={m}>{c.mean_mse[m]??'Sin score'} / {c.mean_delta_mse_vs_first[m]??'Sin comparación'}</td>)}</tr>)}</tbody></table></div>})}
 <details><summary>Soporte, procedencia y límites de comparación R13</summary><pre>{JSON.stringify(comparison,null,2)}</pre></details></>}
 </fieldset>
 {jobs.map(j=><div key={j.id}><p>{j.id} · {j.status} · {j.read_verification||'Sin verificación final'} · {j.error||''}</p>{j.status==='running'&&<button onClick={()=>void action(async()=>{await api(`research/r13/${j.id}/cancel`,{})})}>Cancelar R13</button>}{j.status==='complete'&&<><button disabled={busy||active} onClick={()=>void action(async()=>{await api(`research/r13/${j.id}/repeat`,{});setJobs(await api('research/r13'))})}>Repetir corrida R13</button><button disabled={busy} onClick={()=>void action(async()=>setText(JSON.stringify(await api(`research/r13/${j.id}/artifacts/request.json`),null,2)))}>Abrir experimento R13</button>{['request.json','result.json','predictions.jsonl','manifest.json'].map(n=><a key={n} download href={`/api/research/r13/${j.id}/artifacts/${n}`}>{n} </a>)}<table aria-label={`Resultados transferencia ${j.id}`}><thead><tr><th>Secuencia / proveedor</th><th>Objetivos comunes</th><th>Persistencia MSE</th><th>Media train MSE</th><th>Ridge completo MSE</th><th>Subespacio MSE</th>{Object.keys(j.results?.[0]?.mean_mse||{}).filter(k=>!['persistence','training_mean','full_ridge','subspace_ridge'].includes(k)).map(k=><th key={k}>{k} MSE</th>)}<th>Prefijo adaptación</th></tr></thead><tbody>{(j.results||[]).map((r:Data)=><tr key={r.sequence_id}><td>{r.sequence_id} / {r.provider}</td><td>{r.common_count}</td>{['persistence','training_mean','full_ridge','subspace_ridge'].map(k=><td key={k}>{r.mean_mse[k]??'Sin soporte'}</td>)}{Object.keys(r.mean_mse).filter(k=>!['persistence','training_mean','full_ridge','subspace_ridge'].includes(k)).map(k=><td key={k}>{r.mean_mse[k]??'Sin soporte'}</td>)}<td>{r.adaptation_prefix_samples}</td></tr>)}</tbody></table><details><summary>Procedencia, soporte y límites R13</summary><pre>{JSON.stringify(j,null,2)}</pre></details></>}</div>)}
 </section>;
}
