import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function MembraneReadoutPanel({api}:Data){
 const [preset,setPreset]=useState(''),[cases,setCases]=useState('[]'),[projections,setProjections]=useState<Data[]>([]),[jobs,setJobs]=useState<Data[]>([]);
 const [projection,setProjection]=useState(''),[role,setRole]=useState('train'),[recording,setRecording]=useState(''),[group,setGroup]=useState(''),[targets,setTargets]=useState('');
 const [labelCatalog,setLabelCatalog]=useState<Data|null>(null),[labelSignal,setLabelSignal]=useState(''),[computedLabel,setComputedLabel]=useState<Data|null>(null);
 const [labelSettings,setLabelSettings]=useState(JSON.stringify({signal_ids:[],method:'mean',min_observations:2,min_observed_fraction:1,max_gap_s:.1},null,2));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Data|null>(null),[verification,setVerification]=useState<Data|null>(null),[resultId,setResultId]=useState('');
 const refresh=async()=>{const [p,j]=await Promise.all([api('research/r07'),api('research/r07-readout')]);setProjections(p.filter((r:Data)=>r.status==='complete'));setJobs(j);};
 useEffect(()=>{let live=true;void Promise.all([api('research/r07-readout/configuration',{}),api('research/r07'),api('research/r07-readout')]).then(([c,p,j])=>{if(live){setPreset(JSON.stringify(c,null,2));setProjections(p.filter((r:Data)=>r.status==='complete'));setJobs(j);}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[api]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const parse=(text:string)=>{try{return JSON.parse(text);}catch{return null;}};
 const config=parse(preset), parsedLabel=parse(labelSettings), caseRows=parse(cases);
 const labelConfig=parsedLabel&&Array.isArray(parsedLabel.signal_ids)&&parsedLabel.signal_ids.every((id:any)=>typeof id==='string')?parsedLabel:null;
 const editConfig=(patch:Data)=>setPreset(JSON.stringify({...config,...patch},null,2));
 const editLabel=(patch:Data)=>{const value={...labelConfig,...patch};setLabelSettings(JSON.stringify(value,null,2));if(config)editConfig({label_settings:value.signal_ids?.length?value:undefined});setComputedLabel(null);setTargets('');};
 const editCases=(rows:Data[])=>setCases(JSON.stringify(rows,null,2));
 const exportPreset=()=>{const u=URL.createObjectURL(new Blob([preset],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='r07-readout-preset.json';a.click();URL.revokeObjectURL(u);};
 return <section><h2>R07 · Recuperación de atributos reservados</h2>
 <p>Lee figuras RMS derivadas del PCM, con entrenamiento y prueba separados. Compara campo completo, forma normalizada y magnitud, media de entrenamiento y etiquetas barajadas. Las etiquetas no modifican la figura.</p>
 {error&&<p role="alert">{error}</p>}
 {config?.settings&&<fieldset disabled={busy}><legend>Controles de recuperación R07</legend>
 <label>Reserva R07<select aria-label="Reserva R07" value={config.reservation} onChange={e=>editConfig({reservation:e.target.value})}><option value="within_take">Ventanas de la misma toma</option><option value="take">Tomas diferentes</option><option value="subject">Grupos corporales diferentes</option></select></label>
 <label>Normalización R07<select aria-label="Normalización R07" value={config.settings.normalization} onChange={e=>editConfig({settings:{...config.settings,normalization:e.target.value}})}><option value="center_train">Centrar con entrenamiento</option><option value="standardize_train">Estandarizar con entrenamiento</option></select></label>
 {[['ridge','Regularización R07',.000001,100,'any'],['embargo_s','Separación temporal R07 (s)',0,120,'any'],['shuffle_seed','Semilla de control R07',0,2147483647,1]].map(([key,label,min,max,step])=><label key={String(key)}>{label}<input type="number" value={config.settings[String(key)]} min={min} max={max} step={step} onChange={e=>editConfig({settings:{...config.settings,[String(key)]:+e.target.value}})}/></label>)}
 </fieldset>}
 <label>Preset portable de recuperación R07<textarea disabled={busy} aria-label="Preset portable de recuperación R07" rows={12} value={preset} onChange={e=>setPreset(e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void act(async()=>setPreset(JSON.stringify(await api('research/r07-readout/configuration',JSON.parse(preset)),null,2)))}>Validar preset de recuperación R07</button>
 <button disabled={busy||!preset} onClick={exportPreset}>Exportar preset de recuperación R07</button>
 <p>El preset contiene atributos/unidades, reserva, ridge, normalización, embargo y semilla. Importalo pegando JSON; no contiene fuentes, personas, calibración ni etiquetas.</p>
 <button disabled={busy} onClick={()=>void act(refresh)}>Actualizar figuras disponibles R07</button>
 <label>Figura para recuperar atributos<select disabled={busy} aria-label="Figura para recuperar atributos" value={projection} onChange={e=>{setProjection(e.target.value);setComputedLabel(null);setLabelCatalog(null);setTargets('');}}><option value="">Elegir figura calculada</option>{projections.map(p=><option key={p.id} value={p.id}>{p.id}</option>)}</select></label>
 <button disabled={busy||!projection} onClick={()=>void act(async()=>{setLabelCatalog(null);setLabelCatalog(await api(`research/r07-readout/projections/${projection}/label-signals`));})}>Cargar señales para etiquetas R07</button>
 {labelCatalog&&<><p>Ventana de atributos: [{labelCatalog.start_s}, {labelCatalog.end_s}) s · EVAL {labelCatalog.evaluation_id}, corrida {labelCatalog.run_index}</p><label>Señal para etiqueta R07<select aria-label="Señal para etiqueta R07" value={labelSignal} onChange={e=>setLabelSignal(e.target.value)}><option value="">Elegir señal</option>{Object.entries(labelCatalog.signals).map(([id,v]:[string,any])=><option key={id} value={id}>{id} ({v.unit})</option>)}</select></label><button disabled={busy||!labelSignal} onClick={()=>void act(async()=>{const s=JSON.parse(labelSettings);if(!s.signal_ids.includes(labelSignal))s.signal_ids.push(labelSignal);editLabel({signal_ids:s.signal_ids});})}>Agregar señal a etiquetas R07</button></>}
 {labelConfig&&<fieldset disabled={busy}><legend>Controles de etiquetas R07</legend>
 <label>Resumen de etiqueta R07<select aria-label="Resumen de etiqueta R07" value={labelConfig.method} onChange={e=>editLabel({method:e.target.value})}>{['mean','rms','std','peak_abs'].map(m=><option key={m} value={m}>{m}</option>)}</select></label>
 {[['min_observations','Observaciones mínimas R07',2,14400,1],['min_observed_fraction','Cobertura mínima R07',.000001,1,'any'],['max_gap_s','Gap máximo R07 (s)',.000001,5,'any']].map(([key,label,min,max,step])=><label key={String(key)}>{label}<input type="number" value={labelConfig[String(key)]} min={min} max={max} step={step} onChange={e=>editLabel({[String(key)]:+e.target.value})}/></label>)}
 {(labelConfig.signal_ids||[]).map((id:string)=><div key={id}>{id} <button onClick={()=>editLabel({signal_ids:labelConfig.signal_ids.filter((s:string)=>s!==id)})}>Quitar señal {id}</button></div>)}
 </fieldset>}
 <label>Perfil portable de etiquetas R07<textarea disabled={busy} aria-label="Perfil portable de etiquetas R07" rows={9} value={labelSettings} onChange={e=>{setLabelSettings(e.target.value);const value=parse(e.target.value);if(config&&value&&Array.isArray(value.signal_ids))editConfig({label_settings:value.signal_ids.length?value:undefined});setComputedLabel(null);setTargets('');}}/></label>
 <button disabled={busy} onClick={()=>void act(async()=>{const s=JSON.parse(preset).label_settings;if(!s)throw Error('El preset no contiene label_settings');setLabelSettings(JSON.stringify(s,null,2));setComputedLabel(null);setTargets('');})}>Cargar perfil de etiquetas desde preset R07</button>
 <button disabled={busy||!projection} onClick={()=>void act(async()=>{setComputedLabel(null);setTargets('');const v=await api('research/r07-readout/label',{...JSON.parse(labelSettings),projection_run_id:projection});setComputedLabel(v);setTargets(JSON.stringify(v.targets));const {projection_run_id,...s}=v.request;setPreset(JSON.stringify({...JSON.parse(preset),attribute_ids:v.attribute_ids,attribute_units:v.attribute_units,label_settings:s},null,2));})}>Calcular atributos desde EVAL R07</button>
 <p>Opcional: mean/rms/std/peak_abs sobre señales observadas de la ventana ligada al PCM. Cobertura mínima, cantidad de observaciones y gap se configuran en el perfil; las etiquetas calculadas se verifican de nuevo al congelar casos. No es predicción ni intención inferida.</p>
 {computedLabel&&<p aria-label="Cobertura de etiquetas R07">{computedLabel.coverage.observed}/{computedLabel.coverage.observations} observaciones · fracción {computedLabel.coverage.observed_fraction} · gap máximo {computedLabel.coverage.max_observed_gap_s} s · duplicados excluidos {computedLabel.coverage.duplicate_control_holds_excluded}</p>}
 <label>Rol del caso R07<select aria-label="Rol del caso R07" value={role} onChange={e=>setRole(e.target.value)}><option value="train">Entrenamiento</option><option value="test">Prueba reservada</option></select></label>
 <label>Grabación declarada R07<input value={recording} onChange={e=>setRecording(e.target.value)}/></label>
 <label>Grupo corporal declarado R07<input value={group} onChange={e=>setGroup(e.target.value)}/></label>
 <label>Atributos declarados R07<input disabled={busy} value={targets} placeholder="Array JSON en el orden del preset" onChange={e=>{setTargets(e.target.value);setComputedLabel(null);}}/></label>
 <button disabled={busy||!projection||!recording||!group||!targets} onClick={()=>void act(async()=>{const rows=JSON.parse(cases);if(!Array.isArray(rows))throw Error('Casos debe ser un array');const label= computedLabel?(({projection_run_id,...s})=>s)(computedLabel.request):null;let index=1;while(rows.some((r:Data)=>r.id===`case-${index}`))index++;rows.push({id:`case-${index}`,projection_run_id:projection,role,recording_id:recording,subject_group:group,targets:JSON.parse(targets),...(label?{computed_label:label}:{})});setCases(JSON.stringify(rows,null,2));})}>Agregar caso de recuperación R07</button>
 {Array.isArray(caseRows)&&caseRows.length>0&&caseRows.every((c:Data)=>c&&typeof c.id==='string'&&typeof c.projection_run_id==='string'&&['train','test'].includes(c.role)&&Array.isArray(c.targets))&&<table aria-label="Selección de casos R07"><thead><tr><th>Caso/figura</th><th>Rol</th><th>Atributos</th><th>Acción</th></tr></thead><tbody>{caseRows.map((c:Data,index:number)=><tr key={`${index}.${c.id}`}><td>{c.id} · {c.projection_run_id}</td><td><select disabled={busy} aria-label={`Rol ${c.id}`} value={c.role} onChange={e=>editCases(caseRows.map((r:Data,i:number)=>i===index?{...r,role:e.target.value}:r))}><option value="train">Entrenamiento</option><option value="test">Prueba reservada</option></select></td><td>{JSON.stringify(c.targets)} · {c.computed_label?'calculados':'declarados'}</td><td><button disabled={busy} onClick={()=>editCases(caseRows.filter((_:Data,i:number)=>i!==index))}>Quitar caso {c.id}</button></td></tr>)}</tbody></table>}
 <label>Casos locales de recuperación R07<textarea aria-label="Casos locales de recuperación R07" rows={14} value={cases} onChange={e=>setCases(e.target.value)}/></label>
 <p>Declarar IDs no certifica identidad. Misma toma debe conservar el mismo ID entre renders/presets. Mínimo tres casos de entrenamiento y dos de prueba; mismo medio/grilla. Los datos de esta selección quedan locales en el dataset congelado.</p>
 <button disabled={busy} onClick={()=>void act(async()=>{const c=await api('research/r07-readout/configuration',JSON.parse(preset));await api('research/r07-readout',{...c,cases:JSON.parse(cases)});await refresh();})}>Calcular recuperación R07</button>
 {jobs.map(j=><div key={j.id}>{j.id}<button disabled={busy} onClick={()=>void act(async()=>{const request=await api(`research/r07-readout/${j.id}/request`);const {cases:rows,...c}=request;setPreset(JSON.stringify(c,null,2));editCases(rows);setLabelSettings(JSON.stringify(c.label_settings??{signal_ids:[],method:'mean',min_observations:2,min_observed_fraction:1,max_gap_s:.1},null,2));setProjection('');setLabelCatalog(null);setLabelSignal('');setComputedLabel(null);setTargets('');})}>Recuperar configuración y casos R07</button><button disabled={busy} onClick={()=>void act(async()=>{setResult(null);setVerification(null);setResultId('');const [r,v]=await Promise.all([api(`research/r07-readout/${j.id}/artifacts/result.json`),api(`research/r07-readout/${j.id}/verification`)]);setResult(r);setVerification(v);setResultId(j.id);})}>Ver recuperación R07</button>{['dataset.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r07-readout/${j.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 {result&&<><p>Corrida recuperada: {resultId} · {result.common_count} casos comunes</p>{verification&&<p aria-label="Verificación de recuperación R07">{verification.read_verification==='integrity_only'?'Integridad verificada; sin recalcular':'Recalculado numéricamente con código actual'} · código {verification.implementation_matches?'coincidente':'distinto'} · entorno {verification.environment_matches?'coincidente':'distinto'}</p>}
 <button disabled={busy} onClick={()=>void act(async()=>{setVerification(null);setVerification(await api(`research/r07-readout/${resultId}/verification?recompute=true`));})}>Recalcular verificación de recuperación R07</button>
 <table aria-label="Errores de recuperación R07"><thead><tr><th>Lectura</th>{result.attribute_ids.map((id:string,i:number)=><th key={id}>{id} · MSE ({result.attribute_units[i]})²</th>)}</tr></thead><tbody>{Object.entries(result.mean_squared_error).map(([id,values])=><tr key={id}><td>{id}</td>{(values as number[]).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table>
 <details><summary>Modelos, casos reservados, predicciones y límites</summary><pre>{JSON.stringify(result,null,2)}</pre></details>
 <p>No demuestra HIT, una identidad natural entre gesto y figura, ni validación perceptual. Ajustar parámetros mirando la prueba convierte la comparación en exploratoria.</p></>}
 </section>;
}
