import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function MembraneControlsPanel({api}:Data){
 const [text,setText]=useState(''),[jobs,setJobs]=useState<Data[]>([]),[result,setResult]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[verification,setVerification]=useState<Data|null>(null),[resultId,setResultId]=useState('');
 useEffect(()=>{let live=true;void api('research/r07-controls/configuration',{}).then((v:Data)=>{if(live)setText(JSON.stringify(v,null,2));}).catch((e:any)=>{if(live)setError(String(e));});const poll=async()=>{try{const rows=await api('research/r07-controls');if(live)setJobs(rows);}catch(e){if(live)setError(String(e));}};void poll();const timer=setInterval(poll,1000);return()=>{live=false;clearInterval(timer);};},[api]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const active=busy||jobs.some(j=>j.worker_active||['queued','running'].includes(j.status));
 return <section><h2>R07 · Controles transientes</h2><p>Impulso held, pulso, suma de componentes y ruido con semilla. Mismo medio y estado cero; dosis digitales diferentes, sin normalización automática.</p>{error&&<p role="alert">{error}</p>}
 <label>Preset portable de controles R07<textarea aria-label="Preset portable de controles R07" rows={18} value={text} onChange={e=>setText(e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void act(async()=>setText(JSON.stringify(await api('research/r07-controls/configuration',JSON.parse(text)),null,2)))}>Validar preset de controles R07</button>
 <button disabled={active} onClick={()=>void act(async()=>{const c=await api('research/r07-controls/configuration',JSON.parse(text));await api('research/r07-controls',c.settings);})}>Calcular controles R07</button>
 {jobs.map(j=><div key={j.id}>{j.id} · {j.status}{['queued','running'].includes(j.status)&&<button onClick={()=>void act(async()=>{await api(`research/r07-controls/${j.id}/cancel`,{});})}>Cancelar controles R07</button>}{j.status==='complete'&&<><button disabled={busy} onClick={()=>void act(async()=>{setResult(null);setVerification(null);setResultId('');const [status,report]=await Promise.all([api(`research/r07-controls/${j.id}/verification`),api(`research/r07-controls/${j.id}/artifacts/result.json`)]);setResult(report);setVerification(status);setResultId(j.id);})}>Ver controles R07</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r07-controls/${j.id}/artifacts/${n}`} download>{n} </a>)}</>}</div>)}
 {result&&<><p>Corrida R07 recuperada: {resultId}</p>{verification&&<p aria-label="Verificación de controles R07">{verification.read_verification==='integrity_only'?'Integridad verificada; sin recalcular':'Recalculado numéricamente con código actual'} · código {verification.implementation_matches?'coincidente':'distinto'} · entorno {verification.environment_matches?'coincidente':'distinto'}</p>}<button disabled={busy} onClick={()=>void act(async()=>{setVerification(null);setVerification(await api(`research/r07-controls/${resultId}/verification?recompute=true`));})}>Recalcular verificación de controles R07</button><p>Recalcular compara resultados con tolerancia declarada; no reescribe la corrida ni valida el medio físico.</p><table><thead><tr><th>Entrada</th><th>Dosis Σx²</th><th>Peak entrada</th><th>RMS por punto</th><th>Energía modal proxy final</th></tr></thead><tbody>{Object.entries(result.conditions).map(([name,r]:[string,any])=><tr key={name}><td>{name}</td><td>{r.input_sum_squares}</td><td>{r.input_peak_abs}</td><td>{r.field.rms.join(', ')}</td><td>{r.final_modal_energy_proxy}</td></tr>)}</tbody></table><details><summary>Configuración y límites congelados del banco</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}
 </section>;
}
