import {useEffect,useRef,useState} from 'react';
export function NeuroPanel({api}:{api:any}){
 const [text,setText]=useState('{"channels":[],"samples":[]}'),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 useEffect(()=>()=>{generation.current++;},[]);
 const edit=(value:string)=>{generation.current++;setText(value);setResult(null);};
 const inspect=async()=>{const token=++generation.current;setBusy(true);setError('');setResult(null);try{const r=await api('research/r11/inspect',JSON.parse(text));if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const download=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r11-declared-observations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Observaciones crudas R11"><h2>R11 · Señales crudas declaradas</h2><p>Importar contrato JSON con unidades, referencia y relojes explícitos. Esto no conecta hardware ni calcula SNR/placer/estados mentales; conserva valores y faltantes sin filtrar.</p><label>Observaciones JSON R11<textarea rows={14} value={text} disabled={busy} onChange={e=>edit(e.target.value)}/></label><label>Importar observaciones R11<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void(async()=>{setBusy(true);setError('');try{if(file.size>16*1024*1024)throw Error('Importación excede 16 MiB');const value=JSON.parse(await file.text());edit(JSON.stringify(value,null,2));}catch(e){setError(String(e));}finally{setBusy(false);}})();}}/></label><button disabled={busy} onClick={()=>void inspect()}>Inspeccionar contrato R11</button>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.stream.samples.length} muestras · {result.index_gaps.length} saltos de índice declarados. Rate nominal {result.stream.nominal_sample_rate_hz} Hz; no medición física.</p><table aria-label="Cobertura de canales R11"><thead><tr><th>Canal</th><th>Unidad</th><th>Referencia</th><th>Observados</th><th>Faltantes</th><th>Artefactos anotados</th></tr></thead><tbody>{result.channels.map((c:any)=><tr key={c.id}><td>{c.id}</td><td>{c.units}</td><td>{c.reference}</td><td>{c.observed_count}</td><td>{c.missing_count}</td><td>{c.annotated_artifact_count}</td></tr>)}</tbody></table><button onClick={download}>Exportar inventario R11</button><details><summary>Datos originales y límites R11</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</section>;
}
