import {CSVTimeControls,portableCSVMapping} from './CSVTimeControls';
import {useEffect,useRef,useState} from 'react';
const mappingExample={delimiter:',',skip_rows:0,index_column:'index',time_column:'time_s',time_units:'seconds',channel_columns:{ch1:'channel_1'},missing_tokens:[''],missing_cause:'declared_csv_missing'};
function download(value:any,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function NeuroCSVPanel({api,onConverted}:{api:any,onConverted:(result:any)=>void}){
 const [csv,setCSV]=useState(''),[metadata,setMetadata]=useState('{}'),[mapping,setMapping]=useState(JSON.stringify(mappingExample,null,2)),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0);useEffect(()=>()=>{generation.current++;},[]);
 const [rows,setRows]=useState<any[]>([]),[opened,setOpened]=useState(''),[verification,setVerification]=useState<any>(null);
 const refresh=async()=>setRows(await api('research/r11/csv-imports'));
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));},[api]);
 const body=()=>({schema_version:1,csv_text:csv,metadata:JSON.parse(metadata),mapping:JSON.parse(mapping)});
 const save=async()=>{setBusy(true);setError('');try{const saved=await api('research/r11/csv-imports',body());setOpened(saved.id);setVerification(saved);await refresh();}catch(e){setError(`${String(e)}. Si se perdió la respuesta, actualizá el listado o repetí el guardado con la misma entrada.`);}finally{setBusy(false);}};
 const open=async(id:string)=>{setBusy(true);setError('');setResult(null);try{const frozen=await api(`research/r11/csv-imports/${id}/artifacts/request.json`);const r=await api(`research/r11/csv-imports/${id}/artifacts/result.json`);setCSV(frozen.csv_text);setMetadata(JSON.stringify(frozen.metadata,null,2));setMapping(JSON.stringify(frozen.mapping,null,2));setResult(r);setOpened(id);setVerification(null);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const recheck=async()=>{setBusy(true);setError('');try{setVerification(await api(`research/r11/csv-imports/${opened}/verification?recompute=true`));}catch(e){setError(String(e));}finally{setBusy(false);}};
 const clear=()=>{generation.current++;setResult(null);setOpened('');setVerification(null);setError('');};
 const convert=async()=>{const token=++generation.current;setBusy(true);setResult(null);setOpened('');setVerification(null);setError('');try{const r=await api('research/r11/import-csv',{schema_version:1,csv_text:csv,metadata:JSON.parse(metadata),mapping:JSON.parse(mapping)});if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 return <section aria-label="Importación CSV R11"><h3>R11 · Importar tabla CSV declarada</h3><p>Elegí columnas, unidades por canal y reloj. No detecta placa ni convierte amplitudes; índices de columna repetidos o reiniciados se rechazan. Numerar filas es opt-in y no detecta pérdidas del contador físico. Guardar importación conserva el CSV original, mapeo y conversión en esta máquina.</p>
 <label>Archivo CSV UTF-8 R11<input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const token=++generation.current;setBusy(true);setError('');setResult(null);setOpened('');setVerification(null);void(async()=>{try{if(file.size>16*1024*1024)throw Error('CSV excede 16 MiB');const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());if(token===generation.current)setCSV(text);}catch(err){if(token===generation.current)setError(String(err));}finally{if(token===generation.current)setBusy(false);}})();}}/></label>
 <label>Texto CSV R11<textarea rows={6} disabled={busy} value={csv} onChange={e=>{clear();setCSV(e.target.value);}}/></label>
 <label>Metadatos de observación CSV R11 (JSON)<textarea rows={8} disabled={busy} value={metadata} onChange={e=>{clear();setMetadata(e.target.value);}}/></label>
 <CSVTimeControls text={mapping} onChange={value=>{clear();setMapping(value)}} disabled={busy} scope="R11"/>
 <label>Mapeo de columnas CSV R11 (JSON)<textarea rows={8} disabled={busy} value={mapping} onChange={e=>{clear();setMapping(e.target.value);}}/></label>
 <button disabled={busy||!csv} onClick={()=>void convert()}>Convertir CSV R11</button>
 <button disabled={busy||!result} onClick={()=>void save()}>Guardar importación CSV R11</button>
 <button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>Actualizar importaciones CSV R11</button>
 {rows.map(row=><div key={row.id}>{row.source_id} · {row.samples} muestras · {row.read_verification}<button disabled={busy} onClick={()=>void open(row.id)}>Abrir importación CSV R11</button>{['source.csv','request.json','result.json','manifest.json'].map(name=><a key={name} href={`/api/research/r11/csv-imports/${row.id}/artifacts/${name}`} download>{name} </a>)}</div>)}
 {opened&&<><p>Importación CSV recuperable: {opened}</p><button disabled={busy} onClick={()=>void recheck()}>Recalcular importación CSV R11</button></>}
 {verification&&<p>Verificación CSV: {verification.read_verification} · implementación {verification.current_code_matches?'coincidente':'distinta'}</p>}
 <button disabled={busy} onClick={()=>{try{download(portableCSVMapping(JSON.parse(mapping)),'r11-csv-mapping.json');}catch(e){setError(String(e));}}}>Exportar mapeo CSV R11</button>
 <label>Importar mapeo CSV R11<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const token=++generation.current;setBusy(true);setResult(null);setOpened('');setVerification(null);setError('');void(async()=>{try{if(file.size>1024*1024)throw Error('Mapeo excede 1 MiB');const value=portableCSVMapping(JSON.parse(await file.text()));if(token===generation.current)setMapping(JSON.stringify(value,null,2));}catch(err){if(token===generation.current)setError(String(err));}finally{if(token===generation.current)setBusy(false);}})();}}/></label>
 {error&&<p role="alert">{error}</p>}{result&&<><p>CSV convertido: {result.stream.samples.length} muestras · {result.index_gaps.length} saltos de índice · columnas ignoradas: {result.import_provenance.ignored_columns.join(', ')||'ninguna'}</p><p>Tiempo convertido de {result.import_provenance.mapping.time_units} a segundos; amplitudes y unidades declaradas conservadas.</p><button disabled={busy} onClick={()=>onConverted(result)}>Usar observaciones CSV en R11</button><button onClick={()=>download(result,'r11-csv-conversion.json')}>Exportar conversión y procedencia CSV R11</button><details><summary>Procedencia CSV</summary><pre>{JSON.stringify(result.import_provenance,null,2)}</pre></details></>}
 </section>;
}
