import {useEffect,useRef,useState} from 'react';
const pendingKey='weaver-r11-snr-pending-v1';
const initial={schema_version:1,line:'R11',kind:'synthetic_known_components',sample_rate_hz:256,sample_count:256,start_index:0,stop_index:256,remove_mean:false,missing_indices:[],excluded_indices:[],signal:{amplitude:2,frequency_hz:8,phase_rad:0,dc_offset:0},noise:{amplitude:1,frequency_hz:16,phase_rad:0,dc_offset:0}};
function download(value:any,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function NeuroSNRPanel({api}:{api:any}){
 const [config,setConfig]=useState<any>(initial),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0);
 const [rows,setRows]=useState<any[]>([]),[opened,setOpened]=useState('');
 const [pending,setPending]=useState<any>(()=>{try{const raw=sessionStorage.getItem(pendingKey);return raw?JSON.parse(raw):null;}catch{return null;}});
 const refresh=async()=>{const token=generation.current;const r=await api('research/r11/snr-records');if(token===generation.current)setRows(r);};
 const save=async(retry=false)=>{const token=++generation.current;setBusy(true);setError('');try{const frozen=retry?pending:JSON.parse(JSON.stringify(config));if(!frozen)throw Error('No hay configuración pendiente');sessionStorage.setItem(pendingKey,JSON.stringify(frozen));setPending(frozen);await api('research/r11/snr-records',frozen);sessionStorage.removeItem(pendingKey);if(token!==generation.current)return;setPending(null);await refresh();}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const open=async(id:string)=>{const token=++generation.current;setBusy(true);setError('');setResult(null);try{const r=await api(`research/r11/snr-records/${id}/artifacts/result.json`);if(token!==generation.current)return;setConfig(r.config);setResult(r);setOpened(id);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 useEffect(()=>()=>{generation.current++;},[]);
 const edit=(next:any)=>{generation.current++;setConfig(next);setResult(null);setOpened('');setError('');};
 const calculate=async()=>{const token=++generation.current;setBusy(true);setResult(null);setError('');try{const r=await api('research/r11/synthetic-snr',config);if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const numeric=(key:string,label:string)=> <label key={key}>{label}<input type="number" step="any" value={config[key]} disabled={busy} onChange={e=>edit({...config,[key]:e.target.value===''?null:Number(e.target.value)})}/></label>;
 return <section aria-label="Control sintético SNR R11"><h3>R11 · Control de señal/ruido conocido</h3><p>Dos tonos dimensionless definidos por separado. El tono designado ruido es un control: no representa ruido fisiológico ni se extrae de una mezcla EEG.</p>
 {numeric('sample_rate_hz','Frecuencia de muestreo sintética (Hz)')}{numeric('sample_count','Cantidad de muestras sintéticas')}{numeric('start_index','Inicio de ventana (índice incluido)')}{numeric('stop_index','Fin de ventana (índice excluido)')}
 {(['signal','noise'] as const).map(component=><fieldset key={component}><legend>{component==='signal'?'Señal conocida':'Ruido designado'}</legend>{[['amplitude','Amplitud'],['frequency_hz','Frecuencia Hz'],['phase_rad','Fase radianes'],['dc_offset','Offset DC']].map(([key,label])=><label key={key}>{label} {component}<input type="number" step="any" disabled={busy} value={config[component]?.[key]??''} onChange={e=>edit({...config,[component]:{...config[component],[key]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</fieldset>)}
 <label><input type="checkbox" checked={config.remove_mean} disabled={busy} onChange={e=>edit({...config,remove_mean:e.target.checked})}/>Retirar media de cada componente sobre soporte común</label>
 {(['missing_indices','excluded_indices'] as const).map(key=><label key={key}>{key==='missing_indices'?'Índices faltantes (JSON)':'Índices excluidos (JSON)'}<input disabled={busy} value={typeof config[key]==='string'?config[key]:JSON.stringify(config[key])} onChange={e=>{let value:any=e.target.value;try{value=JSON.parse(value);}catch{}edit({...config,[key]:value});}}/></label>)}
 <button disabled={busy} onClick={()=>void calculate()}>Calcular control SNR R11</button><button disabled={busy} onClick={()=>download(config,'r11-snr-config.json')}>Exportar configuración SNR R11</button>
 <label>Importar configuración SNR R11<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void(async()=>{setBusy(true);try{if(file.size>1024*1024)throw Error('Configuración excede 1 MiB');const value=JSON.parse(await file.text());if(value.kind!=='synthetic_known_components'||!value.signal||!value.noise)throw Error('Configuración sintética R11 requerida');edit(value);}catch(e){setError(String(e));}finally{setBusy(false);}})();}}/></label>
 <button disabled={busy||!result||pending!==null} onClick={()=>void save()}>Guardar corrida SNR R11</button>
 <button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>Actualizar corridas SNR R11</button>
 {pending!==null&&<><p>Configuración SNR congelada pendiente; reintento explícito sin cambiar el cálculo actual.</p><button disabled={busy} onClick={()=>void save(true)}>Recuperar envío SNR R11</button><button disabled={busy} onClick={()=>download(pending,'r11-snr-pending.json')}>Exportar envío SNR pendiente</button><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(pendingKey);setPending(null);}catch(e){setError(String(e));}}}>Descartar envío SNR pendiente</button></>}
 {rows.map(row=><div key={row.id}>{row.id} · {row.read_verification} · implementación {row.implementation_matches?'coincidente':'distinta'}<button disabled={busy} onClick={()=>void open(row.id)}>Abrir corrida SNR R11</button>{['request.json','result.json','manifest.json'].map(name=><a key={name} href={`/api/research/r11/snr-records/${row.id}/artifacts/${name}`} download>{name} </a>)}</div>)}
 {opened&&<p>Corrida SNR recuperada: {opened}</p>}
 {error&&<p role="alert">{error}</p>}{result&&<><p>Estado SNR: {result.metrics.status} · soporte común: {result.metrics.support_count} muestras · dB: {result.metrics.snr_db??'no definido'}</p><table aria-label="Potencias sintéticas R11"><thead><tr><th>Componente</th><th>Potencia (dimensionless²)</th><th>Media</th></tr></thead><tbody><tr><td>Señal</td><td>{result.metrics.signal_power??'no definida'}</td><td>{result.metrics.signal_mean??'no definida'}</td></tr><tr><td>Ruido</td><td>{result.metrics.noise_power??'no definida'}</td><td>{result.metrics.noise_mean??'no definida'}</td></tr></tbody></table><button onClick={()=>download(result,'r11-snr-control.json')}>Exportar resultado SNR R11</button><details><summary>Muestras, soporte y límites SNR</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}
 </section>;
}
