import {useEffect,useRef,useState} from 'react';
export function NeuroPanel({api}:{api:any}){
 const pendingKey='weaver.r11.observation.pending.v1';
 const [rows,setRows]=useState<any[]>([]),[pending,setPending]=useState<any>(null),[rawPending,setRawPending]=useState<string|null>(null),[opened,setOpened]=useState('');
 const refresh=async()=>setRows(await api('research/r11/observations'));
 useEffect(()=>{try{const raw=sessionStorage.getItem(pendingKey);setRawPending(raw);if(raw){if(raw.length>16*1024*1024)throw Error('Pendiente R11 demasiado grande');const body=JSON.parse(raw);if(body.line!=='R11'||!Array.isArray(body.channels)||!Array.isArray(body.samples)||!body.samples.length)throw Error('Pendiente R11 inválido');setPending(body);}}catch(e){setError(String(e));}void refresh().catch(e=>setError(String(e)));},[api]);
 const [text,setText]=useState('{"channels":[],"samples":[]}'),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 useEffect(()=>()=>{generation.current++;},[]);
 const edit=(value:string)=>{generation.current++;setText(value);setResult(null);setOpened('');};
 const inspect=async()=>{const token=++generation.current;setBusy(true);setError('');setResult(null);setOpened('');try{const r=await api('research/r11/inspect',JSON.parse(text));if(token===generation.current)setResult(r);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const save=async(retry:boolean)=>{setBusy(true);setError('');try{const body=retry?pending:result?.stream;if(!body)throw Error('Inspeccioná observaciones antes de guardar');const raw=JSON.stringify(body);sessionStorage.setItem(pendingKey,raw);setPending(body);setRawPending(raw);await api('research/r11/observations',body);sessionStorage.removeItem(pendingKey);setPending(null);setRawPending(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const open=async(id:string)=>{const token=++generation.current;setBusy(true);setError('');setResult(null);setOpened('');try{const r=await api(`research/r11/observations/${id}/artifacts/result.json`);if(token!==generation.current)return;setText(JSON.stringify(r.stream,null,2));setResult(r);setOpened(id);}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}};
 const exportPending=()=>{if(rawPending===null)return;const url=URL.createObjectURL(new Blob([rawPending],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r11-pending-observation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const download=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r11-declared-observations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Observaciones crudas R11"><h2>R11 · Señales crudas declaradas</h2><p>Importar contrato JSON con unidades, referencia y relojes explícitos. Esto no conecta hardware ni calcula SNR/placer/estados mentales; conserva valores y faltantes sin filtrar.</p><label>Observaciones JSON R11<textarea rows={14} value={text} disabled={busy} onChange={e=>edit(e.target.value)}/></label><label>Importar observaciones R11<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void(async()=>{setBusy(true);setError('');try{if(file.size>16*1024*1024)throw Error('Importación excede 16 MiB');const value=JSON.parse(await file.text());edit(JSON.stringify(value,null,2));}catch(e){setError(String(e));}finally{setBusy(false);}})();}}/></label><button disabled={busy} onClick={()=>void inspect()}>Inspeccionar contrato R11</button><button disabled={busy||!result||rawPending!==null} onClick={()=>void save(false)}>Guardar observaciones R11</button>{rawPending!==null&&<><p>Observaciones pendientes congeladas, sin reanudar adquisición.</p>{pending&&<button disabled={busy} onClick={()=>void save(true)}>Recuperar envío de observaciones R11</button>}<button disabled={busy} onClick={exportPending}>Exportar envío pendiente R11</button><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(pendingKey);setRawPending(null);setPending(null);setError('');}catch(e){setError(String(e));}}}>Descartar envío pendiente R11</button></>}<button disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}>Actualizar registros R11</button>{rows.map(r=><div key={r.id}>{r.id} · {r.read_verification}<button disabled={busy} onClick={()=>void open(r.id)}>Abrir observaciones guardadas R11</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r11/observations/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}{error&&<p role="alert">{error}</p>}{result&&<>{opened&&<p>Observaciones guardadas: {opened}. Ver manifest/estado de verificación en listado.</p>}<p>{result.stream.samples.length} muestras · {result.index_gaps.length} saltos de índice declarados. Rate nominal {result.stream.nominal_sample_rate_hz} Hz; no medición física.</p><table aria-label="Cobertura de canales R11"><thead><tr><th>Canal</th><th>Unidad</th><th>Referencia</th><th>Observados</th><th>Faltantes</th><th>Artefactos anotados</th></tr></thead><tbody>{result.channels.map((c:any)=><tr key={c.id}><td>{c.id}</td><td>{c.units}</td><td>{c.reference}</td><td>{c.observed_count}</td><td>{c.missing_count}</td><td>{c.annotated_artifact_count}</td></tr>)}</tbody></table><button onClick={download}>Exportar inventario R11</button><details><summary>Datos originales y límites R11</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</section>;
}
