import {useEffect,useState,useRef} from 'react';
import {PhysiologyCSV} from './PhysiologyCSV';
type Data=Record<string,any>;
const template:Data={schema_version:1,line:'R12',provider:'synthetic',source_id:'software-control',subject_slot:'synthetic-slot',task:'Control de software, sin participante',constraints:'Valores construidos; no son mediciones humanas',clock:{source_clock:'synthetic',common_clock:'fixture',offset_s:0,rate:1,uncertainty_s:0,method:'declared_assumption'},channels:[{id:'hr',kind:'heart_rate',units:'bpm',sensor_or_method:'Generador sintético',uncertainty_description:'Valores conocidos del fixture'},{id:'p',kind:'mechanical_power',units:'W',sensor_or_method:'Generador sintético',uncertainty_description:'Valores conocidos del fixture',calibration_evidence_id:'software-fixture'}],samples:Array.from({length:6},(_,i)=>({index:i,source_time_s:i,values:{hr:60+10*i,p:2}})),trials:[{id:'control',condition:'Control sintético',start_s:0,end_s:5,useful_outcome:null,outcome_units:'count',outcome_method:'Sin resultado humano'}],max_gap_s:2,common_channel_ids:['hr','p'],evaluation_binding:null};
function download(value:any,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function PhysiologyPanel({api}:{api:any}){
 const key='weaver.r12.measurements.pending.v1';
 const [text,setText]=useState(JSON.stringify(template,null,2)),[result,setResult]=useState<Data|null>(null),[rows,setRows]=useState<Data[]>([]),[pending,setPending]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[evaluation,setEvaluation]=useState(''),[runIndex,setRunIndex]=useState(0);
 const current=useRef(text);current.current=text;
 const confirmContext=(context:string)=>{if(context!==current.current)throw Error('El protocolo R12 cambió durante la carga; repetir la operación sobre el contexto actual')};
 const refresh=async()=>setRows(await api('research/r12/measurements'));
 useEffect(()=>{try{const raw=sessionStorage.getItem(key);if(raw)setPending(JSON.parse(raw))}catch(e){setError(String(e))}void refresh().catch(e=>setError(String(e)))},[api]);
 const action=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const edit=(raw:string)=>{setText(raw);setResult(null)};
 const change=(work:(r:Data)=>void)=>{try{const r=JSON.parse(text);work(r);edit(JSON.stringify(r,null,2));setError('')}catch(e){setError(String(e))}};
 let request:Data|null=null;try{request=JSON.parse(text)}catch{}
 const save=async(retry=false)=>{const body=retry?pending:result?.request;if(!body)throw Error('Inspeccionar antes de guardar');sessionStorage.setItem(key,JSON.stringify(body));setPending(body);await api('research/r12/measurements',body);sessionStorage.removeItem(key);setPending(null);await refresh()};
 return <section aria-label="Mediciones y tarea R12"><h2>R12 · Mediciones, tarea y cobertura</h2>
 <p>Importar mediciones declaradas. No conecta sensores ni obtiene calorías/eficiencia de pose o frecuencia cardíaca. Resultado útil, potencia, esfuerzo y preferencia son observables distintos. La plantilla es un control sintético, sin participante.</p>
 <button disabled={busy} onClick={()=>edit(JSON.stringify(template,null,2))}>Cargar control sintético R12</button>
 <label>Importar mediciones R12<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>16*1024*1024)throw Error('Máximo 16 MiB');edit(JSON.stringify(JSON.parse(await file.text()),null,2))})}}/></label>
 {request && <div><p>Proveedor declarado: {request.provider} · slot {request.subject_slot} · tarea {request.task}</p>
 <label>Gap máximo entre muestras (s)<input type="number" min={.001} max={60} step={.1} value={request.max_gap_s} disabled={busy} onChange={e=>change(r=>r.max_gap_s=+e.target.value)}/></label>
 <fieldset><legend>Canales para soporte común</legend>{(request.channels||[]).map((c:Data)=><label key={c.id}><input type="checkbox" disabled={busy} checked={(request!.common_channel_ids||[]).includes(c.id)} onChange={e=>change(r=>r.common_channel_ids=e.target.checked?[...r.common_channel_ids,c.id]:r.common_channel_ids.filter((id:string)=>id!==c.id))}/>{c.id} · {c.kind} ({c.units}) · {c.sensor_or_method} · incertidumbre: {c.uncertainty_description}</label>)}</fieldset>
 {(['offset_s','rate','uncertainty_s'] as const).map(k=><label key={k}>Reloj {k}<input type="number" step={.001} disabled={busy} value={request?.clock?.[k]??0} onChange={e=>change(r=>r.clock[k]=+e.target.value)}/></label>)}
 {(request.trials||[]).map((t:Data,i:number)=><fieldset key={i}><legend>Intento {t.id}</legend>
 {(['condition','outcome_units','outcome_method'] as const).map(k=><label key={k}>{k}<input disabled={busy} value={t[k]} onChange={e=>change(r=>r.trials[i][k]=e.target.value)}/></label>)}
 {(['start_s','end_s','useful_outcome'] as const).map(k=><label key={k}>{k}<input type="number" step={.01} disabled={busy} value={t[k]??''} onChange={e=>change(r=>r.trials[i][k]=e.target.value===''?null:+e.target.value)}/></label>)}
 <button disabled={busy} onClick={()=>change(r=>r.trials.splice(i,1))}>Quitar intento {t.id}</button></fieldset>)}
 <button disabled={busy} onClick={()=>change(r=>r.trials.push({id:`trial-${r.trials.length+1}`,condition:'Nueva condición',start_s:0,end_s:5,useful_outcome:null,outcome_units:'count',outcome_method:'Declarar método'}))}>Añadir intento R12</button>
 <button disabled={busy} onClick={()=>download({schema_version:1,kind:'r12-analysis-settings',max_gap_s:request?.max_gap_s,common_channel_ids:request?.common_channel_ids},'r12-analysis-settings.json')}>Guardar configuración portable R12</button>
 <label>Importar configuración R12<input type="file" accept="application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>65536)throw Error('Máximo 64 KiB');const settings=JSON.parse(await file.text());if(settings.schema_version!==1||settings.kind!=='r12-analysis-settings'||Object.keys(settings).some(k=>!['schema_version','kind','max_gap_s','common_channel_ids'].includes(k)))throw Error('Configuración incompatible');const r=JSON.parse(text);r.max_gap_s=settings.max_gap_s;r.common_channel_ids=settings.common_channel_ids;edit(JSON.stringify(r,null,2))})}}/></label>
 </div>}
 <PhysiologyCSV api={api} protocol={request} onApply={(value:Data)=>edit(JSON.stringify(value,null,2))}/>
 <details><summary>Vincular explícitamente una evaluación local</summary><p>El vínculo conserva slot y hash del manifest. Es sólo procedencia: no transforma el reloj, no demuestra sincronía y no transfiere calibración. No cambia proveedor ni inventa muestras. Ajustar timestamps/reloj e intentos antes de inspeccionar.</p>
 <label>ID evaluación R12<input value={evaluation} disabled={busy} onChange={e=>setEvaluation(e.target.value)}/></label><label>Índice corrida R12<input type="number" min={0} value={runIndex} disabled={busy} onChange={e=>setRunIndex(+e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void action(async()=>{const context=current.current;const response=await fetch(`/api/evaluations/${evaluation}/artifacts/manifest.json`);if(!response.ok)throw Error(`Manifest HTTP ${response.status}`);const bytes=await response.arrayBuffer();const manifest=JSON.parse(new TextDecoder().decode(bytes));const run=manifest.runs[runIndex];if(!run)throw Error('Corrida inexistente');const source=manifest.request.sources[run.source_index];const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');confirmContext(context);const r=JSON.parse(text);if(r.subject_slot!==source.person_id)throw Error(`El slot importado (${r.subject_slot}) no coincide con ${source.person_id}; declarar correspondencia explícita en los datos`);r.evaluation_binding={evaluation_id:evaluation,manifest_sha256:hash,run_index:runIndex,person_slot:source.person_id};r.clock.common_clock=`evaluation:${evaluation}:source_time_s`;edit(JSON.stringify(r,null,2))})}>Vincular manifest R12</button>
 <button disabled={busy} onClick={()=>change(r=>{r.evaluation_binding=null})}>Quitar vínculo R12</button></details>
 <label>Mediciones y protocolo JSON R12<textarea aria-label="Mediciones y protocolo JSON R12" rows={12} disabled={busy} value={text} onChange={e=>edit(e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void action(async()=>{setResult(null);const context=current.current;const value=await api('research/r12/inspect',JSON.parse(text));confirmContext(context);setResult(value)})}>Analizar mediciones R12</button>
 <button disabled={busy||!result||!!pending} onClick={()=>void action(()=>save())}>Guardar corrida R12</button>
 {pending && <div><p>Envío R12 pendiente congelado. Recuperación explícita, sin adquisición.</p><button disabled={busy} onClick={()=>void action(()=>save(true))}>Recuperar envío R12</button><button disabled={busy} onClick={()=>download(pending,'r12-pending.json')}>Exportar pendiente R12</button><button disabled={busy} onClick={()=>void action(async()=>{sessionStorage.removeItem(key);setPending(null)})}>Descartar pendiente R12</button></div>}
 <button disabled={busy} onClick={()=>void action(refresh)}>Actualizar corridas R12</button>
 {rows.map(r=><div key={r.id}>{r.id} · {r.read_verification}<button disabled={busy} onClick={()=>void action(async()=>{const context=current.current;const saved=await api(`research/r12/measurements/${r.id}/artifacts/result.json`);confirmContext(context);edit(JSON.stringify(saved.request,null,2));setResult(saved)})}>Abrir corrida R12</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} download href={`/api/research/r12/measurements/${r.id}/artifacts/${n}`}>{n} </a>)}</div>)}
 {error&&<p role="alert">{error}</p>}
 {result && <><p>{result.estimator}</p>{result.trials.map((t:Data)=><div key={t.trial.id}><h3>{t.trial.condition} · {t.trial.start_s}–{t.trial.end_s}s</h3><p>Resultado útil declarado: {t.trial.useful_outcome??'Sin dato'} {t.trial.outcome_units} · {t.trial.outcome_method}</p><table aria-label={`Resultados R12 ${t.trial.id}`}><thead><tr><th>Canal / unidad</th><th>Cobertura</th><th>Media</th><th>Soporte común (s)</th><th>Media común</th><th>Trabajo/energía parcial (J)</th><th>Sin soporte (s)</th></tr></thead><tbody>{t.channels.map((c:Data)=><tr key={c.channel.id}><td>{c.channel.id} / {c.channel.units}</td><td>{(100*c.coverage).toFixed(1)}%</td><td>{c.mean??'Sin soporte'}</td><td>{c.common_duration_s}</td><td>{c.common_mean??'Sin soporte'}</td><td>{c.energy_or_work_J??'No calculado'}</td><td>{c.uncovered_duration_s}</td></tr>)}</tbody></table></div>)}
 <button onClick={()=>download(result,'r12-measurement-results.json')}>Exportar resultado R12</button><details><summary>Causas, soporte y límites R12</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}
 </section>;
}
