import {useEffect,useState} from 'react';
type Data=Record<string,any>;
const defaults={schema_version:1,resonators:{fundamental_hz:40.4,ratios:[1,2,3,4,5,6],sample_rate:48000,damping_per_s:[2,2,2,2,2,2],coupling_per_s:0,topology:'isolated',adjacency:null},excitation:{mode:'threshold_crossings',high:1,low:.2,refractory_s:.2,max_gap_s:.1,reference_scale:1,gain:1,max_impulse:1,positive_delta_min:0,voice_weights:Array(6).fill(1/6)},render:{block_size:256,tail_s:.5,missing_policy:'ring'}};
const mappingDefaults={reference_scale:1,gain:1,max_amplitude:1,attack_s:.02,release_s:.08,max_hold_s:.1,voice_weights:Array(6).fill(1/6)};
export function ResonatorPanel({api,run}:Data){
 const [result,setResult]=useState<Data|null>(null);
 const [settings,setSettings]=useState<Data>(defaults),[text,setText]=useState(''),[arrays,setArrays]=useState<Data>({}),[jobs,setJobs]=useState<Data[]>([]),[evaluations,setEvaluations]=useState<Data[]>([]),[evaluation,setEvaluation]=useState(''),[report,setReport]=useState<Data|null>(null),[index,setIndex]=useState(0),[signal,setSignal]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>setEvaluations((await api('evaluations')).filter((j:Data)=>j.status==='complete'));
 useEffect(()=>{let live=true;const poll=async()=>{try{const j=await api('research/r05');if(live)setJobs(j);}catch(e){if(live)setError(String(e));}};void poll();const timer=setInterval(poll,1000);void refresh().catch(e=>setError(String(e)));return()=>{live=false;clearInterval(timer);};},[api]);
 const resetSelection=(r:Data,i:number)=>{setSignal('');const selected=r.manifest.runs[i],source=r.manifest.request.sources[selected.source_index];setStart(source.start_s);setEnd(Math.min(source.end_s,source.start_s+120));};
 useEffect(()=>{let live=true;setReport(null);if(evaluation)void api(`evaluations/${evaluation}/report`).then((r:Data)=>{if(live){resetSelection(r,0);setIndex(0);setReport(r);}}).catch((e:any)=>{if(live)setError(String(e));});return()=>{live=false;};},[evaluation,api]);
 const selected=report?.manifest.runs[index],source=selected && report?.manifest.request.sources[selected.source_index],catalog=selected?.signals || {};
 const config=()=>{const value=structuredClone(settings);for(const [key,text] of Object.entries(arrays)){const [group,name]=key.split('.');value[group][name]=JSON.parse(text as string);}return value;};
 const edit=(group:string,key:string,value:any)=>setSettings({...settings,[group]:{...settings[group],[key]:value}});
 const available=source && catalog[signal] && Number.isFinite(start) && Number.isFinite(end) && start>=source.start_s && end<=source.end_s && end>start && end-start<=120;
 return <section><h2>R05 · Resonadores experimentales</h2>
  <p>Corrida offline sobre features congeladas. No cambia el instrumento en vivo. Acoplamiento puede alterar modos efectivos; esta salida no es un medio cimático físico.</p>
  {error && <p role="alert">{error}</p>}
  <button onClick={()=>run(refresh)}>Actualizar comparaciones R05</button>
  <label>Comparación R05<select value={evaluation} onChange={e=>setEvaluation(e.target.value)}><option value="">Elegir comparación terminada</option>{evaluations.map(j=><option key={j.id} value={j.id}>{j.id}</option>)}</select></label>
  {report && <label>Corrida de origen R05<select value={index} onChange={e=>{const i=+e.target.value;resetSelection(report,i);setIndex(i);}}>{report.manifest.runs.map((r:Data,i:number)=><option key={i} value={i}>Fuente {r.source_index+1} · {r.preset_id}</option>)}</select></label>}
  {source && <p>Persona congelada: {source.person_id} · escala {source.torso_scale ?? 'no disponible'} · procedencia {source.calibration_provenance || 'no disponible'}</p>}
  <label>Señal R05<select value={signal} onChange={e=>setSignal(e.target.value)}><option value="">Elegir señal</option>{Object.entries(catalog).map(([id,s]:[string,any])=><option key={id} value={id}>{id} · {s.unit} · {s.observed_count} observaciones</option>)}</select></label>
  <label>Inicio R05 (s)<input type="number" step="any" value={start} onChange={e=>setStart(+e.target.value)}/></label>
  <label>Fin R05 (s)<input type="number" step="any" value={end} onChange={e=>setEnd(+e.target.value)}/></label>
  {Object.entries(settings).filter(([k])=>k!=='schema_version').map(([group,values]:[string,any])=><fieldset key={group}><legend>{group} R05</legend>{Object.entries(values).map(([key,value])=><label key={key}>{group}.{key} R05{typeof value==='number'?<input type="number" step="any" value={value} onChange={e=>edit(group,key,+e.target.value)}/>:typeof value==='string'?<select value={value} onChange={e=>edit(group,key,e.target.value)}>{(key==='topology'?['isolated','chain','ring','complete','custom']:key==='mode'?['threshold_crossings','positive_delta']:['ring','reset']).map(v=><option key={v}>{v}</option>)}</select>:<textarea value={arrays[`${group}.${key}`] ?? JSON.stringify(value)} onChange={e=>setArrays({...arrays,[`${group}.${key}`]:e.target.value})}/>}</label>)}</fieldset>)}
  <p>Ratios, damping y pesos: 6–32 voces, una entrada por voz. Adjacency JSON sólo para custom: matriz simétrica 0–1, diagonal cero. Escala de referencia en la unidad de la señal elegida, sin ajuste automático. Positive_delta es diferencia positiva, no aceleración. Ring conserva cola; reset puede ser discontinuo.</p>
  <label><input type="checkbox" checked={!!settings.mapping} onChange={e=>{const next={...settings};if(e.target.checked)next.mapping=structuredClone(mappingDefaults);else delete next.mapping;setSettings(next);setArrays(Object.fromEntries(Object.entries(arrays).filter(([key])=>!key.startsWith('mapping.'))));}}/>Comparar con mapeo de amplitud R05</label>
  <p>El mapeo compara portadoras desacopladas con los mismos f1/ratios/reloj, sin cambiar el Shaper. Ganancias y envolventes distintas quedan explícitas; no iguala loudness automáticamente.</p>
  <button onClick={()=>run(async()=>setText(JSON.stringify(await api('research/r05/configuration',config()),null,2)))}>Exportar configuración R05</button>
  <textarea aria-label="Configuración R05 JSON" value={text} onChange={e=>setText(e.target.value)}/>
  <button onClick={()=>run(async()=>{const validated=await api('research/r05/configuration',JSON.parse(text));setSettings(validated);setArrays({});})}>Importar configuración R05</button>
  <p>Preset portable de parámetros; no contiene fuente, persona, calibración ni segmento. Importar no ejecuta ni cambia esa selección.</p>
  <button disabled={!available || busy || jobs.some(j=>['queued','running'].includes(j.status))} onClick={()=>run(async()=>{setBusy(true);try{const validated=await api('research/r05/configuration',config());const {schema_version,...parameters}=validated;await api('research/r05',{...parameters,selection:{evaluation_id:evaluation,run_index:index,signal_id:signal,start_s:start,end_s:end}});setJobs(await api('research/r05'));}finally{setBusy(false);}})}>Correr R05</button>
  {jobs.map(j=><div key={j.id}><p>{j.id} · {j.status} · {j.error_type || j.error || ''}</p>{['queued','running'].includes(j.status) && <button onClick={()=>run(async()=>{await api(`research/r05/${j.id}/cancel`,{});setJobs(await api('research/r05'));})}>Cancelar R05 {j.id}</button>}{j.status==='complete' && <>{j.kind==='mechanism_comparison'?<button onClick={()=>run(async()=>setResult(await api(`research/r05/${j.id}/artifacts/result.json`)))}>Ver comparación R05 {j.id}</button>:<p>Frames {j.levels.frames} · pico {j.levels.peak_abs} · RMS {j.levels.rms} · muestras sobre full scale {j.levels.samples_over_full_scale}.</p>}<p>Audio crudo sin limitador: revisar niveles antes de reproducir.</p>{['request.json','input.json','manifest.json',...(j.kind==='mechanism_comparison'?['result.json','excited-sum.wav','excited-voices.wav','mapped-sum.wav','mapped-voices.wav']:['sum.wav','voices.wav'])].map(name=><a key={name} href={`/api/research/r05/${j.id}/artifacts/${name}`} download>{name} </a>)}</>}</div>)}
  {result && <><h3>Comparación pareada R05</h3><p>Persona congelada: {result.provenance?.source?.person_id || 'sin declaración'} · unidad {result.input_unit} · reloj {result.clock.sample_rate} Hz. RMS sobre soporte válido común; colas y tramos sin soporte son actividad del instrumento.</p><table aria-label="Métricas de mecanismos R05"><thead><tr><th>Mecanismo</th><th>Región</th><th>Muestras</th><th>RMS</th><th>Pico</th></tr></thead><tbody>{Object.entries(result.metrics).flatMap(([name,regions]:[string,any])=>Object.entries(regions).map(([region,m]:[string,any])=><tr key={`${name}.${region}`}><td>{name}</td><td>{region}</td><td>{m.frames}</td><td>{m.rms ?? 'indefinido'}</td><td>{m.peak_abs ?? 'indefinido'}</td></tr>))}</tbody></table><p>Ganancia diagnóstica para igual RMS común: {result.suggested_mapping_gain_for_equal_common_rms ?? 'indefinida'}; no aplicada, no loudness perceptual ni calidad.</p><details><summary>Preparación y límites congelados R05</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}
 </section>;
}
