import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function RopeEditor({media,source,text,onChange,api,onReading}:Data){
 const [curveSources,setCurveSources]=useState<Data[]>([]);
 const [pathJobs,setPathJobs]=useState<Data[]>([]);
 useEffect(()=>{let live=true;void api('research/r08/paths').then((j:Data[])=>{if(live)setPathJobs(j);}).catch((e:unknown)=>{if(live)setError(String(e));});return()=>{live=false;};},[api]);
 const [path,setPath]=useState<Data|null>(null),[pathText,setPathText]=useState(JSON.stringify({component_id:1,start:{x:0,y:0},stop:{x:1,y:1},max_visited:100000,max_points:4096},null,2));
 const [proposals,setProposals]=useState<Data[]>([]);
 useEffect(()=>{let live=true;void api('research/r08/masks').then((j:Data[])=>{if(live)setProposals(j);}).catch((e:unknown)=>{if(live)setError(String(e));});return()=>{live=false;};},[api]);
 const [mask,setMask]=useState<Data|null>(null),[maskBusy,setMaskBusy]=useState(false),[maskText,setMaskText]=useState(JSON.stringify({target_rgb:[255,255,255],distance_rgb:40,roi:[0,0,1,1],min_component_px:8,max_components:32,max_runs:10000},null,2));
 const [tool,setTool]=useState('curve'),[endpoints,setEndpoints]=useState<Data>({});
 const [index,setIndex]=useState(0),[state,setState]=useState('observed'),[causes,setCauses]=useState<string[]>([]),[segments,setSegments]=useState<Data[][]>([[]]),[note,setNote]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{setIndex(0);setReady(false);},[media]);
 useEffect(()=>{try{const a=JSON.parse(text);const f=a.frames.find((f:Data)=>f.frame_index===index);setCurveSources(f?.curve_sources||[]);setEndpoints(f?.endpoints||{});setState(f?.state||'observed');setCauses(f?.causes||[]);setSegments(f?.visible_segments?.length?f.visible_segments:[[]]);setNote(f?.note||'');setError('');}catch{setError('JSON inválido');}setReady(false);},[index,media]);
 const [read,setRead]=useState<Data|null>(null),[image,setImage]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{onReading(maskBusy||read?.status==='starting'||read?.status==='running');return()=>onReading(false);},[onReading,read?.status,maskBusy]);
 useEffect(()=>{
  let live=true,id='';setPath(null);setMask(null);setReady(false);setImage('');setRead({status:'starting'});
  void (async()=>{
   try{
    const job=await api('research/r08/reads',{media_id:source,frame_index:index,sha256:media.media_sha256});id=job.id;
    if(!live){await api(`research/r08/reads/${id}/cancel`,{});return;}
    let status=job;setRead(status);
    while(live&&status.status==='running'){await new Promise(r=>setTimeout(r,100));if(!live)return;status=await api(`research/r08/reads/${id}`);if(live)setRead(status);}
    if(!live)return;
    if(status.status==='complete')setImage(`/api/research/r08/reads/${id}/result`);
    else if(status.status!=='cancelled')setError(status.error||'Falló lectura de imagen');
   }catch(e){if(live){setRead({status:'failed'});setError(String(e));}}
  })();
  return()=>{live=false;if(id)void api(`research/r08/reads/${id}/cancel`,{}).catch(()=>{});};
 },[api,source,index,media.media_sha256,attempt]);
 const apply=()=>{try{const a=JSON.parse(text);if(a.media_sha256!==media.media_sha256)throw Error('La anotación corresponde a otro video');const curves=segments.filter(s=>s.length);if(curves.some(s=>s.length<2))throw Error('Cada tramo requiere al menos dos puntos');if((state==='observed'||state==='partial')&&!curves.length)throw Error('Dibujá un tramo visible');if(state==='observed'&&(curves.length!==1||causes.length))throw Error('Observed requiere un tramo y ninguna causa');if((state==='partial'||state==='unidentifiable')&&!causes.length)throw Error('Elegí una causa');a.frames=a.frames.filter((f:Data)=>f.frame_index!==index);a.frames.push({frame_index:index,time_s:media.frame_times_s[index],state,causes,...(['observed','partial'].includes(state)&&curveSources.length?{curve_sources:curveSources}:{}),...(['observed','partial'].includes(state)&&Object.keys(endpoints).length?{endpoints}:{}),visible_segments:state==='absent'||state==='unidentifiable'?[]:curves,note});a.frames.sort((a:Data,b:Data)=>a.frame_index-b.frame_index);onChange(JSON.stringify(a,null,2));setError('');}catch(e){setError(String(e));}};
 return <div><label>Frame R08<input type="number" disabled={maskBusy||read?.status==='starting'||read?.status==='running'} min={0} max={media.frame_times_s.length-1} value={index} onChange={e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=0&&v<media.frame_times_s.length)setIndex(v);}}/></label><p>Tiempo fuente: {media.frame_times_s[index]} s. {ready?'Imagen decodificada':'Cargando imagen'}</p>
 <p>Durante la lectura, cancelá la imagen para cambiar de fuente o preparar otra anotación.</p>
 <p role="status">Imagen R08: {read?.status}</p><button disabled={read?.status!=='running'} onClick={()=>void api(`research/r08/reads/${read?.id}/cancel`,{}).then((j:Data)=>setRead(j)).catch((e:unknown)=>setError(String(e)))}>Cancelar imagen R08</button><button disabled={read?.status==='starting'||read?.status==='running'} onClick={()=>{setError('');setAttempt(v=>v+1);}}>Reintentar imagen R08</button>
 <div style={{position:'relative',width:'100%',aspectRatio:`${media.width_px}/${media.height_px}`}}><img key={image} src={image||undefined} alt={`Frame R08 ${index}`} onLoad={()=>setReady(true)} onError={()=>{setReady(false);setError('No se pudo decodificar el frame');}} style={{width:'100%',height:'100%'}}/><svg viewBox="0 0 1 1" preserveAspectRatio="none" style={{position:'absolute',inset:0,width:'100%',height:'100%'}} onClick={e=>{if(!ready||!['observed','partial'].includes(state))return;const r=e.currentTarget.getBoundingClientRect();const point={x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};if(tool==='curve'){setCurveSources(v=>v.map(o=>o.segment_index===segments.length-1?{...o,relation:'edited'}:o));setSegments(s=>s.map((v,i)=>i===s.length-1?[...v,point]:v));}else setEndpoints(v=>({...v,[tool]:point}));}}>{path?.supported&&<polyline data-testid="rope-candidate-path" points={path.points.map((p:Data)=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="magenta" strokeWidth={0.004} pointerEvents="none"/>}{mask?.candidate_components.flatMap((c:Data)=>c.runs_y_x_start_x_stop_exclusive.map((r:number[],i:number)=><rect key={`${c.component_id}:${i}`} x={r[1]/media.width_px} y={r[0]/media.height_px} width={(r[2]-r[1])/media.width_px} height={1/media.height_px} fill="lime" fillOpacity={0.45} pointerEvents="none"/>))}{Object.entries(endpoints).map(([label,p])=><g key={label}><circle cx={p.x} cy={p.y} r={0.008} fill="cyan"/><text x={p.x} y={p.y} fontSize={0.03} fill="white">{label}</text></g>)}{segments.map((s,i)=><g key={i}><polyline points={s.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="yellow" strokeWidth={0.003}/>{s.map((p,j)=><circle key={j} cx={p.x} cy={p.y} r={0.004} fill="red"/>)}</g>)}</svg></div>
 <label>Configuración de candidatos R08<textarea rows={8} value={maskText} onChange={e=>setMaskText(e.target.value)}/></label><button disabled={!ready||maskBusy} onClick={()=>{setMaskBusy(true);setError('');void Promise.resolve().then(()=>api('research/r08/mask',{media_id:source,read_id:read?.id,settings:JSON.parse(maskText)})).then((m:Data)=>setMask(m)).catch((e:unknown)=>setError(String(e))).finally(()=>setMaskBusy(false));}}>Calcular candidatos R08</button><button onClick={()=>setMask(null)}>Ocultar candidatos R08</button>{mask&&<><p>Candidatos: {mask.components_returned}/{mask.components_detected}. Revisá manualmente; esta máscara no modifica curvas ni revisiones.</p><details><summary>Parámetros efectivos de candidatos R08</summary><pre>{JSON.stringify({settings:mask.settings,frame_index:mask.frame_index,time_s:mask.time_s,limits:mask.limits},null,2)}</pre></details></>}
 <button disabled={!mask||maskBusy||!ready} onClick={()=>{if(!mask)return;setMaskBusy(true);setError('');const request={media_sha256:mask.media_sha256,frame_index:mask.frame_index,time_s:mask.time_s,width_px:mask.width_px,height_px:mask.height_px,settings:mask.settings};void api('research/r08/masks',{media_id:source,request}).then(()=>api('research/r08/masks')).then((j:Data[])=>setProposals(j)).catch((e:unknown)=>setError(String(e))).finally(()=>setMaskBusy(false));}}>Guardar propuesta R08</button>
 {proposals.filter(j=>j.media_sha256===media.media_sha256).map(j=><div key={j.id}>Propuesta {j.id}, frame {j.frame_index}, {j.time_s} s. <button disabled={maskBusy||!ready||j.frame_index!==index} onClick={()=>{setMaskBusy(true);setError('');void api(`research/r08/masks/${j.id}/reverify`,{media_id:source}).then((m:Data)=>setMask(m)).catch((e:unknown)=>setError(String(e))).finally(()=>setMaskBusy(false));}}>Verificar y mostrar propuesta R08</button><button disabled={maskBusy||!ready||j.frame_index!==index} onClick={()=>{setMaskBusy(true);setError('');setPath(null);void Promise.resolve().then(()=>api('research/r08/path',{media_id:source,mask_id:j.id,settings:JSON.parse(pathText)})).then(async(p:Data)=>{setPath(p);setPathJobs(await api('research/r08/paths'));}).catch((e:unknown)=>setError(String(e))).finally(()=>setMaskBusy(false));}}>Proponer curva guiada R08</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r08/masks/${j.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 <label>Configuración de curva guiada R08<textarea rows={8} value={pathText} onChange={e=>setPathText(e.target.value)}/></label><button onClick={()=>{try{if(!endpoints.a||!endpoints.b)throw Error('Marcá extremos a/b para usar como seeds');setPathText(JSON.stringify({...JSON.parse(pathText),start:endpoints.a,stop:endpoints.b},null,2));}catch(e){setError(String(e));}}}>Usar extremos como seeds R08</button>{path&&<><p>Curva candidata R08: {path.supported?'camino disponible':path.cause}. No identifica centerline real.</p><details><summary>Parámetros efectivos de curva R08</summary><pre>{JSON.stringify(path,null,2)}</pre></details>{path.run_id&&['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r08/paths/${path.run_id}/artifacts/${n}`} download>{n} </a>)}<button disabled={maskBusy||!ready||!path.supported||path.frame_index!==index||path.media_sha256!==media.media_sha256} onClick={()=>{const kept=segments.filter(s=>s.length);setCurveSources(v=>[...v,{segment_index:kept.length,path_run_id:path.run_id,path_manifest_sha256:path.path_manifest_sha256,relation:'exact'}]);setSegments([...kept,path.points]);setPath(null);}}>Usar curva candidata como tramo R08</button></>}
 {pathJobs.filter(j=>j.media_sha256===media.media_sha256).map(j=><div key={j.id}>Curva {j.id}, frame {j.frame_index}, {j.time_s} s. {j.read_verification==='historical_integrity_only'&&'Histórica: descargable, recálculo actual no disponible.'} <button disabled={maskBusy||!ready||j.frame_index!==index||j.read_verification==='historical_integrity_only'} onClick={()=>{setMaskBusy(true);setError('');void api(`research/r08/paths/${j.id}/rebind`,{media_id:source}).then((p:Data)=>setPath(p)).catch((e:unknown)=>setError(String(e))).finally(()=>setMaskBusy(false));}}>Recuperar curva candidata R08</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r08/paths/${j.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 <label>Herramienta R08<select value={tool} onChange={e=>setTool(e.target.value)}><option value="curve">Curva visible</option><option value="a">Extremo a</option><option value="b">Extremo b</option></select></label><button onClick={()=>setEndpoints({})}>Borrar extremos del frame</button><p>Etiquetas a/b declaran correspondencia manual entre frames; no usar izquierda/derecha como identidad.</p>
 <label>Estado R08<select value={state} onChange={e=>setState(e.target.value)}>{['observed','partial','unidentifiable','absent'].map(v=><option key={v}>{v}</option>)}</select></label>{['blur','occlusion','crossing_ambiguity','out_of_frame'].map(c=><label key={c}><input type="checkbox" checked={causes.includes(c)} onChange={e=>setCauses(v=>e.target.checked?[...v,c]:v.filter(x=>x!==c))}/>{c}</label>)}
 <button onClick={()=>setSegments(s=>[...s,[]])}>Nuevo tramo visible</button><button onClick={()=>{setCurveSources([]);setSegments([[]]);}}>Borrar curvas del frame</button><label>Nota R08<input value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!ready} onClick={apply}>Aplicar frame al borrador</button>{error&&<p role="alert">{error}</p>}<p>Aplicar modifica el borrador; guardar revisión lo persiste. Cambiar de frame descarta cambios aún no aplicados.</p></div>;
}
