import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function RopeEditor({media,source,text,onChange}:Data){
 const [index,setIndex]=useState(0),[state,setState]=useState('observed'),[causes,setCauses]=useState<string[]>([]),[segments,setSegments]=useState<Data[][]>([[]]),[note,setNote]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{setIndex(0);setReady(false);},[media]);
 useEffect(()=>{try{const a=JSON.parse(text);const f=a.frames.find((f:Data)=>f.frame_index===index);setState(f?.state||'observed');setCauses(f?.causes||[]);setSegments(f?.visible_segments?.length?f.visible_segments:[[]]);setNote(f?.note||'');setError('');}catch{setError('JSON inválido');}setReady(false);},[index,media]);
 const apply=()=>{try{const a=JSON.parse(text);if(a.media_sha256!==media.media_sha256)throw Error('La anotación corresponde a otro video');const curves=segments.filter(s=>s.length);if(curves.some(s=>s.length<2))throw Error('Cada tramo requiere al menos dos puntos');if((state==='observed'||state==='partial')&&!curves.length)throw Error('Dibujá un tramo visible');if(state==='observed'&&(curves.length!==1||causes.length))throw Error('Observed requiere un tramo y ninguna causa');if((state==='partial'||state==='unidentifiable')&&!causes.length)throw Error('Elegí una causa');a.frames=a.frames.filter((f:Data)=>f.frame_index!==index);a.frames.push({frame_index:index,time_s:media.frame_times_s[index],state,causes,visible_segments:state==='absent'||state==='unidentifiable'?[]:curves,note});a.frames.sort((a:Data,b:Data)=>a.frame_index-b.frame_index);onChange(JSON.stringify(a,null,2));setError('');}catch(e){setError(String(e));}};
 return <div><label>Frame R08<input type="number" min={0} max={media.frame_times_s.length-1} value={index} onChange={e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=0&&v<media.frame_times_s.length)setIndex(v);}}/></label><p>Tiempo fuente: {media.frame_times_s[index]} s. {ready?'Imagen decodificada':'Cargando imagen'}</p>
 <div style={{position:'relative',width:'100%',aspectRatio:`${media.width_px}/${media.height_px}`}}><img key={`${source}:${index}`} src={`/api/research/r08/media/${encodeURIComponent(source)}/frames/${index}?sha256=${media.media_sha256}`} alt={`Frame R08 ${index}`} onLoad={()=>setReady(true)} onError={()=>{setReady(false);setError('No se pudo decodificar el frame');}} style={{width:'100%',height:'100%'}}/><svg viewBox="0 0 1 1" preserveAspectRatio="none" style={{position:'absolute',inset:0,width:'100%',height:'100%'}} onClick={e=>{if(!ready||!['observed','partial'].includes(state))return;const r=e.currentTarget.getBoundingClientRect();const point={x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};setSegments(s=>s.map((v,i)=>i===s.length-1?[...v,point]:v));}}>{segments.map((s,i)=><g key={i}><polyline points={s.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="yellow" strokeWidth={0.003}/>{s.map((p,j)=><circle key={j} cx={p.x} cy={p.y} r={0.004} fill="red"/>)}</g>)}</svg></div>
 <label>Estado R08<select value={state} onChange={e=>setState(e.target.value)}>{['observed','partial','unidentifiable','absent'].map(v=><option key={v}>{v}</option>)}</select></label>{['blur','occlusion','crossing_ambiguity','out_of_frame'].map(c=><label key={c}><input type="checkbox" checked={causes.includes(c)} onChange={e=>setCauses(v=>e.target.checked?[...v,c]:v.filter(x=>x!==c))}/>{c}</label>)}
 <button onClick={()=>setSegments(s=>[...s,[]])}>Nuevo tramo visible</button><button onClick={()=>setSegments([[]])}>Borrar curvas del frame</button><label>Nota R08<input value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!ready} onClick={apply}>Aplicar frame al borrador</button>{error&&<p role="alert">{error}</p>}<p>Aplicar modifica el borrador; guardar revisión lo persiste. Cambiar de frame descarta cambios aún no aplicados.</p></div>;
}
