import {useEffect,useState} from 'react';
const initial={schema_version:1,channels:[[7,0],[7,1],[9,0],[9,1],[8,0],[8,1],[10,0],[10,1]],sample_hz:30,scale:null,scale_unit:'frame_height',scale_provenance:'',min_samples:64,absolute_tolerance_s:.00001,relative_tolerance:.000001,max_gap_s:.25,minimum_confidence:.5,seeds:[7,19,41],preset:{algorithm:{id:'relational'},response:{pluck_enabled:false}}};
export function SaiBodyFourierPanel({api}:{api:any}){
 const [sources,setSources]=useState<any[]>([]),[source,setSource]=useState(''),[person,setPerson]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(10);
 const [text,setText]=useState(JSON.stringify(initial,null,2)),[jobs,setJobs]=useState<any[]>([]),[prepared,setPrepared]=useState<any>(null),[result,setResult]=useState<any>(null),[rowIndex,setRowIndex]=useState(0),[signal,setSignal]=useState('collective.residual'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}};
 useEffect(()=>{let live=true;const poll=()=>api('research/sai-body-fourier').then((rows:any[])=>{if(live)setJobs(rows)}).catch((e:any)=>{if(live)setError(String(e))});void poll();const id=setInterval(poll,1000);return()=>{live=false;clearInterval(id)}},[api]);
 const selection=sources.find(s=>s.job_id===source),active=jobs.some(j=>['queued','running'].includes(j.status));
 const request=()=>({job_id:source,person_id:person,start_s:start,end_s:end,settings:JSON.parse(text)});
 const row=result?.comparison.results[rowIndex],descriptor=row?.descriptors[signal];
 return <section aria-label="Fourier corporal congelado"><h3>Sai–Oliva · Fourier corporal congelado</h3>
 <p>Usa una generación de tracking terminada. Escala, unidades y procedencia se declaran para esta fuente; no importa calibración del instrumento. FFT de bloque completo offline; no cambia video, tracking ni sonido en vivo.</p>
 <button disabled={busy} onClick={()=>void act(async()=>setSources(await api('research/r09/sources')))}>Actualizar fuentes Fourier corporales</button>
 <label>Fuente Fourier corporal<select aria-label="Fuente Fourier corporal" value={source} disabled={busy} onChange={e=>{setSource(e.target.value);setPerson('');setPrepared(null)}}><option value="">Elegir fuente</option>{sources.map(s=><option key={s.job_id} value={s.job_id}>{s.job_id} · {s.effective_device}</option>)}</select></label>
 <label>Persona Fourier corporal<select aria-label="Persona Fourier corporal" value={person} disabled={busy} onChange={e=>{setPerson(e.target.value);setPrepared(null)}}><option value="">Elegir persona</option>{selection?.person_ids.map((p:string)=><option key={p}>{p}</option>)}</select></label>
 <label>Inicio Fourier corporal (s)<input type="number" min={0} value={start} disabled={busy} onChange={e=>{setStart(+e.target.value);setPrepared(null)}}/></label>
 <label>Fin Fourier corporal (s)<input type="number" min={0} value={end} disabled={busy} onChange={e=>{setEnd(+e.target.value);setPrepared(null)}}/></label>
 <label>Ajustes Fourier corporal JSON<textarea aria-label="Ajustes Fourier corporal JSON" disabled={busy} value={text} onChange={e=>{setText(e.target.value);setPrepared(null)}}/></label>
 <p>Completar scale y scale_provenance; declarar sample_hz. channels selecciona [articulación COCO-17, coordenada 0=x/1=y]. preset admite todos sus parámetros; requiere modelo descriptivo y plucks desactivados. Sin interpolar ni corregir poses.</p>
 <button disabled={busy||!source||!person} onClick={()=>void act(async()=>setPrepared(await api('research/sai-body-fourier/prepare',request())))}>Preparar bloques Fourier corporales</button>
 <button disabled={busy||active||!source||!person} onClick={()=>void act(async()=>{await api('research/sai-body-fourier',request());setJobs(await api('research/sai-body-fourier'))})}>Correr Fourier corporal</button>
 <button disabled={busy} onClick={()=>void act(async()=>{const settings=await api('research/sai-body-fourier/settings',JSON.parse(text));setText(JSON.stringify(settings,null,2));const url=URL.createObjectURL(new Blob([JSON.stringify(settings,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sai-body-fourier-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}>Descargar ajustes Fourier corporales</button>
 <label>Importar ajustes Fourier corporales<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void act(async()=>{if(f.size>65536)throw Error('Ajustes demasiado grandes');const settings=await api('research/sai-body-fourier/settings',JSON.parse(await f.text()));setText(JSON.stringify(settings,null,2));setPrepared(null);setPerson('')})}}/></label>
 {prepared&&<><p>Preparación: {prepared.preparation.retained_frames}/{prepared.preparation.input_frames} frames · {prepared.preparation.blocks.length} bloques. Excluidos: {JSON.stringify(prepared.preparation.exclusion_counts)}.</p><details><summary>Soporte y procedencia</summary><pre>{JSON.stringify(prepared,null,2)}</pre></details></>}
 {error&&<p role="alert">{error}</p>}
 {jobs.map(j=><div key={j.id}>{j.id} · {j.status} · {j.error||j.error_type||''}{['queued','running'].includes(j.status)&&<button disabled={busy} onClick={()=>void act(async()=>{await api(`research/sai-body-fourier/${j.id}/cancel`,{});setJobs(await api('research/sai-body-fourier'))})}>Cancelar Fourier corporal</button>}{j.status==='complete'&&<><button disabled={busy} onClick={()=>void act(async()=>{const value=await api(`research/sai-body-fourier/${j.id}/artifacts/result.json`);setResult(value);setRowIndex(0)})}>Abrir Fourier corporal</button>{['request.json','input.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/sai-body-fourier/${j.id}/artifacts/${n}`} download>{n} </a>)}</>}</div>)}
 {result&&<><p>Retenidos: {result.preparation.retained_frames}/{result.preparation.input_frames}. Sólo soporte observado común; geometría no es un puntaje anatómico. Datos locales privados.</p>
 <select aria-label="Bloque y semilla Fourier corporal" value={rowIndex} onChange={e=>setRowIndex(+e.target.value)}>{result.comparison.results.map((r:any,i:number)=><option key={i} value={i}>Bloque {r.block_index} · {r.stream_id} · semilla {r.seed}</option>)}</select>
 <select aria-label="Descriptor Fourier corporal" value={signal} onChange={e=>setSignal(e.target.value)}>{Object.keys(row?.descriptors||{}).map(k=><option key={k}>{k}</option>)}</select>
 {descriptor&&<><p>Soporte común: {descriptor.common_observed}/{descriptor.total}</p><table aria-label="Medias Fourier corporales comunes"><thead><tr><th>Condición</th><th>Media</th><th>Observados</th></tr></thead><tbody>{Object.entries(descriptor.conditions).map(([k,v]:[string,any])=><tr key={k}><td>{k}</td><td>{v.common_mean??'Sin soporte'}</td><td>{v.observed}</td></tr>)}</tbody></table></>}
 <details open><summary>Espectro y longitudes del bloque</summary><pre>{JSON.stringify({spectral_checks:row?.spectral_checks,geometry:row?.geometry},null,2)}</pre></details>
 <details><summary>Exclusiones y límites del resultado</summary><pre>{JSON.stringify({preparation:result.preparation,limits:result.limits},null,2)}</pre></details></>}
 </section>;
}
