import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export function SpatialCompare({api}:{api:any}){
 const [presets,setPresets]=useState<Data[]>([]),[presetName,setPresetName]=useState('Comparación espacial');
 const [mode,setMode]=useState('declared'),[conversions,setConversions]=useState<Data[]>([]),[referenceId,setReferenceId]=useState(''),[candidateId,setCandidateId]=useState('');
 const [reference,setReference]=useState('{}'),[candidate,setCandidate]=useState('{}'),[labels,setLabels]=useState('["joint-0"]');
 const [age,setAge]=useState(.05),[uncertainty,setUncertainty]=useState(.02),[inferred,setInferred]=useState(false),[held,setHeld]=useState(false);
 const [runs,setRuns]=useState<Data[]>([]),[result,setResult]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;void api('research/r09/comparisons').then((r:Data[])=>{if(live)setRuns(r);}).catch((e:unknown)=>{if(live)setError(String(e));});return()=>{live=false;};},[api]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section aria-label="Comparación espacial R09"><h3>Comparar streams R09</h3>
 <p>Mismos marcos, unidades y reloj común declarados. El candidato sólo puede venir del presente o pasado; no ajustamos escala, rotación ni desfase para mejorar error.</p>
 <label>Origen de comparación R09<select disabled={busy} value={mode} onChange={e=>setMode(e.target.value)}><option value="declared">Streams JSON declarados</option><option value="saved">Conversiones guardadas</option></select></label>
 {mode==='saved'?<><button disabled={busy} onClick={()=>void act(async()=>setConversions(await api('research/r09/conversions')))}>Actualizar conversiones para comparar R09</button>{([['Referencia',referenceId,setReferenceId],['Candidato',candidateId,setCandidateId]] as const).map(([name,value,change])=><label key={name}>{name} guardado R09<select disabled={busy} value={value} onChange={e=>change(e.target.value)}><option value="">Elegir conversión</option>{conversions.map(c=><option key={c.id} value={c.id}>{c.id} · {c.read_verification}</option>)}</select></label>)}<p>El servidor conserva IDs y hashes de las conversiones. Sus relojes y calibraciones siguen siendo declaraciones.</p></>:<><label>Stream referencia R09<textarea disabled={busy} rows={8} value={reference} onChange={e=>setReference(e.target.value)}/></label>
 <label>Stream candidato R09<textarea disabled={busy} rows={8} value={candidate} onChange={e=>setCandidate(e.target.value)}/></label></>}
 <label>Etiquetas de comparación R09<textarea disabled={busy} value={labels} onChange={e=>setLabels(e.target.value)}/></label>
 <label>Edad máxima de candidato R09<input disabled={busy} type="number" min={0} max={10} step={.01} value={age} onChange={e=>setAge(Number(e.target.value))}/></label>
 <label>Incertidumbre combinada máxima R09<input disabled={busy} type="number" min={0} max={10} step={.01} value={uncertainty} onChange={e=>setUncertainty(Number(e.target.value))}/></label>
 <label>Admitir puntos inferidos R09<input disabled={busy} type="checkbox" checked={inferred} onChange={e=>setInferred(e.target.checked)}/></label>
 <label>Admitir puntos sostenidos R09<input disabled={busy} type="checkbox" checked={held} onChange={e=>setHeld(e.target.checked)}/></label>
 <label>Nombre preset comparación R09<input disabled={busy} value={presetName} onChange={e=>setPresetName(e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void act(async()=>{await api('research/r09/comparison-presets',{name:presetName,config:{labels:JSON.parse(labels),max_age_s:age,max_combined_clock_uncertainty_s:uncertainty,allow_inferred:inferred,allow_held:held}});setPresets(await api('research/r09/comparison-presets'));})}>Guardar preset comparación R09</button>
 <button disabled={busy} onClick={()=>void act(async()=>setPresets(await api('research/r09/comparison-presets')))}>Actualizar presets comparación R09</button>
 <label>Importar preset comparación R09<input disabled={busy} type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void act(async()=>{if(file.size>65536)throw new Error('Preset supera 64 KiB');await api('research/r09/comparison-presets',JSON.parse(await file.text()));setPresets(await api('research/r09/comparison-presets'));});e.target.value='';}}/></label>
 <p>Presets portables de parámetros y etiquetas; aplicar no cambia fuentes ni ejecuta comparación.</p>
 {presets.map(p=><div key={p.id}>{p.name}<button disabled={busy} onClick={()=>{setLabels(JSON.stringify(p.config.labels));setAge(p.config.max_age_s);setUncertainty(p.config.max_combined_clock_uncertainty_s);setInferred(p.config.allow_inferred);setHeld(p.config.allow_held);}}>Aplicar preset comparación R09</button><a href={`/api/research/r09/comparison-presets/${p.id}`} download>Exportar preset comparación R09</a></div>)}
 {error&&<p role="alert">{error}</p>}
 <button disabled={busy} onClick={()=>void act(async()=>{const settings={labels:JSON.parse(labels),max_age_s:age,max_combined_clock_uncertainty_s:uncertainty,allow_inferred:inferred,allow_held:held};if(mode==='saved'&&(!referenceId||!candidateId))throw new Error('Elegir ambas conversiones');const saved=mode==='saved'?await api('research/r09/compare-conversions',{reference_id:referenceId,candidate_id:candidateId,settings}):await api('research/r09/comparisons',{comparison:{reference:JSON.parse(reference),candidate:JSON.parse(candidate),...settings}});setResult(await api(`research/r09/comparisons/${saved.id}/artifacts/result.json`));setRuns(await api('research/r09/comparisons'));})}>Guardar comparación espacial R09</button>
 {result&&<div>{result.sources&&<p>Conversiones comparadas: referencia {result.sources.reference.id} · candidato {result.sources.candidate.id}. Hashes completos en el resultado descargable.</p>}<p>Soporte espacial: {result.coverage.supported_points}/{result.coverage.eligible_points} puntos elegibles. Unidad: {result.unit}.</p><p>Error medio sobre soporte: {result.mean_error_on_support??'sin soporte'}; máximo: {result.max_error_on_support??'sin soporte'}.</p><details><summary>Causas y entradas de comparación espacial R09</summary><pre>{JSON.stringify(result,null,2)}</pre></details></div>}
 {runs.map(r=><div key={r.id}>{r.id} · {r.read_verification==='recomputed'?'Comparación recalculada':'Histórico: sólo integridad'}<button disabled={busy} onClick={()=>void act(async()=>setResult(await api(`research/r09/comparisons/${r.id}/artifacts/result.json`)))}>Abrir comparación espacial R09</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r09/comparisons/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 </section>;
}
