import {SpatialClockApply} from './SpatialClockApply';
import {useEffect,useState} from 'react';
export function SpatialClockFit({api}:{api:any}){
 const key='weaver.r09.clock-fit.pending.v1';
 const [runs,setRuns]=useState<any[]>([]),[pending,setPending]=useState<any>(null);
 useEffect(()=>{void api('research/r09/clock-fits').then(setRuns).catch(()=>{});try{const raw=sessionStorage.getItem(key);if(raw){if(raw.length>4*1024*1024)throw Error('oversize');const p=JSON.parse(raw);if(!p.fit||!/^[a-f0-9]{32}$/.test(p.idempotency_key))throw Error('invalid');setPending(p);}}catch{sessionStorage.removeItem(key);}},[api]);
 const [text,setText]=useState(JSON.stringify({source_clock:'camera',common_clock:'session',evidence_id:'',anchor_uncertainty_s:.01,anchors:[],validation_anchors:[]},null,2));
 const [result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async()=>{const body=pending||{fit:result.request,idempotency_key:crypto.randomUUID().replaceAll('-','')};sessionStorage.setItem(key,JSON.stringify(body));setPending(body);try{await api('research/r09/clock-fits',body);}catch(e){const status=(e as any)?.status;if(status>=400&&status<500){sessionStorage.removeItem(key);setPending(null);}throw e;}sessionStorage.removeItem(key);setPending(null);setRuns(await api('research/r09/clock-fits'));};
 return <section aria-label="Ajuste de reloj R09"><h3>Sincronización por marcas pareadas</h3><p>Ingresar al menos tres marcas ordenadas de ambos relojes, incertidumbre de lectura y referencia de evidencia. El ajuste usa anchors; validation_anchors permite reservar marcas separadas sin modificarlo. No aplica el reloj automáticamente.</p>
 <label>Marcas de reloj JSON R09<textarea disabled={busy} rows={10} value={text} onChange={e=>{setText(e.target.value);setResult(null);}}/></label>
 <button disabled={busy} onClick={()=>void(async()=>{setBusy(true);setError('');setResult(null);try{setResult(await api('research/r09/clock-fit',JSON.parse(text)));}catch(e){setError(String(e));}finally{setBusy(false);}})()}>Ajustar reloj R09</button>
 {pending&&<p role="status">Ajuste pendiente de confirmar. <button disabled={busy} onClick={()=>void act(save)}>Recuperar ajuste reloj R09</button></p>}
 {error&&<p role="alert">{error}</p>}{result&&<><p>Desfase: {result.clock.offset_s} s · tasa: {result.clock.rate} · residuo máximo: {result.max_abs_residual_s} s.</p><p>Intervalo de marcas: {result.source_interval_s.join('–')} s. Fuera del intervalo no se verificó extrapolación. Incertidumbre empírica, sin garantía estadística.</p><p>Marcas reservadas: {result.validation.count} · residuo máximo reservado: {result.validation.max_abs_residual_s??'sin validación reservada'} s. Extrapolación identificada por marca en JSON.</p><pre>{JSON.stringify(result,null,2)}</pre><button disabled={busy||!!pending} onClick={()=>void act(save)}>Guardar ajuste reloj R09</button><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='r09-clock-fit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Exportar ajuste reloj R09</button></>}
 {runs.map(r=><div key={r.id}>{r.id} · {r.read_verification==='recomputed'?'Ajuste recalculado':'Histórico: sólo integridad'}<button disabled={busy} onClick={()=>void act(async()=>{setResult(await api(`research/r09/clock-fits/${r.id}/artifacts/result.json`));})}>Abrir ajuste reloj R09</button>{['request.json','result.json','manifest.json'].map(n=><a key={n} href={`/api/research/r09/clock-fits/${r.id}/artifacts/${n}`} download>{n} </a>)}</div>)}
 <SpatialClockApply api={api} runs={runs}/>
 </section>;
}
