// Optional local snapshots. No media, server requests or automatic restoration.
export type TransportArchive={id:string,created_at:string,raw:string,sha256:string};
const maxBytes=4*1024*1024,maxTotal=64*1024*1024;
const bytes=(raw:string)=>new TextEncoder().encode(raw);
async function digest(raw:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes(raw)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('weaver-r10-transport-archives',1);r.onupgradeneeded=()=>r.result.createObjectStore('archives',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function validate(row:TransportArchive){if(!row||!/^[a-f0-9]{32}$/.test(row.id)||typeof row.raw!=='string'||bytes(row.raw).length>maxBytes||!/^[a-f0-9]{64}$/.test(row.sha256)||!Number.isFinite(Date.parse(row.created_at)))throw Error('Archivo de transporte local inválido');JSON.parse(row.raw)}
export async function listTransportArchives():Promise<TransportArchive[]>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('archives','readonly'),r=tx.objectStore('archives').getAll();tx.oncomplete=()=>{db.close();resolve(r.result.sort((a:TransportArchive,b:TransportArchive)=>b.created_at.localeCompare(a.created_at)))};tx.onerror=()=>{db.close();reject(tx.error)}})}
export async function readTransportArchive(id:string){const rows=await listTransportArchives();const row=rows.find(r=>r.id===id);if(!row)throw Error('Archivo local no encontrado');validate(row);if(await digest(row.raw)!==row.sha256)throw Error('Contenido del archivo local modificado');return row}
export async function saveTransportArchive(raw:string){if(bytes(raw).length>maxBytes)throw Error('Borrador supera 4 MiB');const parsed=JSON.parse(raw);if(parsed.schema_version!==1||!Array.isArray(parsed.events)||!parsed.events.length)throw Error('Borrador de transporte v1 requerido');const row={id:crypto.randomUUID().replaceAll('-',''),created_at:new Date().toISOString(),raw,sha256:await digest(raw)};const db=await database();return new Promise<TransportArchive>((resolve,reject)=>{const tx=db.transaction('archives','readwrite'),store=tx.objectStore('archives'),r=store.getAll();let selected=row;let failure:Error|null=null;r.onsuccess=()=>{const same=r.result.find((v:TransportArchive)=>v.raw===raw&&v.sha256===row.sha256&&/^[a-f0-9]{32}$/.test(v.id));if(same){selected=same;return}if(r.result.reduce((n:number,v:TransportArchive)=>n+bytes(v.raw).length,0)+bytes(raw).length>maxTotal){failure=Error('Archivo local supera 64 MiB; exportar o borrar borradores anteriores');tx.abort();return}store.put(row)};tx.oncomplete=()=>{db.close();resolve(selected)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(failure||tx.error||Error('Guardado local interrumpido'))}})}
export async function deleteTransportArchive(id:string){const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('archives','readwrite');tx.objectStore('archives').delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
