"""Content-addressed tracking cache with atomic, cancellable generations."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import threading
from uuid import uuid4

from .contracts import MotionFrame, PerceptionSettings


class CacheCancelled(RuntimeError):
    pass


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_json(path, data):
    path = Path(path)
    temp = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        with temp.open("w") as handle:
            json.dump(data, handle, ensure_ascii=False, allow_nan=False, indent=2)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)


def cache_identity(media_hash: str, settings: PerceptionSettings, extractor: dict):
    values = settings.model_dump()
    checkpoint = values.pop("checkpoint")
    for name in ("camera_width", "camera_height", "camera_fps"):
        values.pop(name)
    metadata = {"format": 1, "media_sha256": media_hash, "model_sha256": sha256_file(checkpoint),
                "perception": values, "extractor": extractor}
    encoded = json.dumps(metadata, sort_keys=True, allow_nan=False, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest(), metadata


@dataclass
class CachedTrack:
    manifest_path: Path
    manifest: dict
    frames: list[MotionFrame]


class TrackingCache:
    def __init__(self, data_dir):
        self.data_dir = Path(data_dir)
        self.root = self.data_dir / "tracking"
        self.root.mkdir(parents=True, exist_ok=True)
        self.index_path = self.root / "index.json"
        self._lock = threading.RLock()
        try:
            self._index = json.loads(self.index_path.read_text())
        except (OSError, ValueError):
            self._index = {}
        self.last_problem: str | None = None

    def _directory(self, media_path):
        sidecar = Path(str(media_path) + ".weaver-cache")
        probe = sidecar / f".write-test-{uuid4().hex}"
        try:
            sidecar.mkdir(parents=True, exist_ok=True)
            probe.touch(exist_ok=False)
            return sidecar
        except OSError:
            return self.root
        finally:
            try:
                probe.unlink(missing_ok=True)
            except OSError:
                pass

    def read(self, media_path, key):
        with self._lock:
            candidates = [Path(str(media_path) + ".weaver-cache") / f"{key}.manifest.json",
                          self.root / f"{key}.manifest.json"]
            if key in self._index:
                candidates.append(Path(self._index[key]))
            self.last_problem = None
        for path in dict.fromkeys(candidates):
            if not path.exists():
                continue
            try:
                manifest = json.loads(path.read_text())
                if manifest["key"] != key or manifest["format"] != 1:
                    raise ValueError("incompatible cache manifest")
                # Filenames are generated by us; refuse traversal from edited manifests.
                filename = manifest["frames_file"]
                if Path(filename).name != filename:
                    raise ValueError("invalid frames path")
                data = path.parent / filename
                if sha256_file(data) != manifest["frames_sha256"]:
                    raise ValueError("tracking checksum differs")
                with data.open() as handle:
                    frames = [MotionFrame.model_validate_json(line) for line in handle]
                if not frames or len(frames) != manifest["frame_count"]:
                    raise ValueError("incomplete tracking generation")
                if any(a.source_time_s > b.source_time_s or a.sequence >= b.sequence for a, b in zip(frames, frames[1:])):
                    raise ValueError("tracking time or sequence regressed")
                return CachedTrack(path, manifest, frames)
            except (OSError, ValueError, KeyError, TypeError) as exc:
                self.last_problem = f"corrupt: {exc}"
        return None

    def write(self, media_path, key, metadata, frames, *, cancel=None, progress=None):
        self.last_problem = None
        cancel = cancel or threading.Event()
        directory = self._directory(media_path)
        generation = uuid4().hex
        filename = f"{key}.{generation}.jsonl"
        final = directory / filename
        temporary = directory / (filename + ".partial")
        digest = hashlib.sha256()
        collected = []
        try:
            with temporary.open("wb") as handle:
                for frame in frames:
                    if cancel.is_set():
                        raise CacheCancelled("tracking cancelled; previous cache kept")
                    frame = frame if isinstance(frame, MotionFrame) else MotionFrame.model_validate(frame)
                    if collected and (frame.source_time_s < collected[-1].source_time_s or frame.sequence <= collected[-1].sequence):
                        raise ValueError("extractor produced regressing timestamp/sequence")
                    line = (frame.model_dump_json() + "\n").encode()
                    handle.write(line)
                    digest.update(line)
                    collected.append(frame)
                    if progress is not None:
                        progress(frame, len(collected))
                handle.flush()
                os.fsync(handle.fileno())
            if cancel.is_set():
                raise CacheCancelled("tracking cancelled; previous cache kept")
            if not collected:
                raise ValueError("video contains no decoded frames")
            if sha256_file(media_path) != metadata["media_sha256"]:
                raise ValueError("video changed during extraction")
            if cancel.is_set():
                raise CacheCancelled("tracking cancelled; previous cache kept")
            os.replace(temporary, final)
            first, last = collected[0], collected[-1]
            step = (last.source_time_s - collected[-2].source_time_s) if len(collected) > 1 else 1 / 30
            manifest = {**metadata, "key": key, "generation": generation, "frames_file": filename,
                        "frames_sha256": digest.hexdigest(), "frame_count": len(collected),
                        "width": first.width, "height": first.height, "unit": first.unit,
                        "coordinate_frame": first.coordinate_frame, "dimensions": first.dimensions,
                        "duration_s": metadata.get("media_duration_s") or (last.source_time_s + max(last.duration_s or step, .001)),
                        "timestamp_origins": sorted({f.timestamp_origin for f in collected})}
            path = directory / f"{key}.manifest.json"
            atomic_json(path, manifest)
            with self._lock:
                self._index[key] = str(path)
                try:
                    atomic_json(self.index_path, self._index)
                except OSError as exc:
                    # The authoritative generation is already safely committed.
                    self.last_problem = f"cache valid; rename index unavailable: {exc}"
            return CachedTrack(path, manifest, collected)
        finally:
            temporary.unlink(missing_ok=True)
